import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.112.0";
import Stripe from "npm:stripe@18.5.0";

const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}});
const sha256=async(value:string)=>{const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('')};
const safeEqual=(a:string,b:string)=>{if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0};
type Result={kind:'on_call'|'sos',phase:'settlement'|'transfer',id:string,status:'released'|'reconciled'|'skipped'|'failed',message?:string,transfer_id?:string};

Deno.serve(async req=>{
 if(req.method!=='POST')return json({error:'Method not allowed'},405);
 try{
  const supplied=req.headers.get('x-worker-token')||'';if(!supplied)return json({error:'Unauthorized'},401);
  const url=Deno.env.get('SUPABASE_URL')||'',service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';if(!url||!service)return json({error:'Database runtime unavailable'},503);
  const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});
  const{data:worker,error:workerError}=await admin.from('internal_worker_auth').select('token_hash').eq('worker_name','marketplace_payout_retry').maybeSingle();if(workerError||!worker?.token_hash)return json({error:'Worker authentication is unavailable'},503);
  if(!safeEqual(await sha256(supplied),String(worker.token_hash)))return json({error:'Unauthorized'},401);
  const readSecret=async(name:string)=>{const env=Deno.env.get(name);if(env)return env;const{data,error}=await admin.rpc('sos_get_runtime_secret',{secret_name:name});return error||!data?'':String(data)};
  const stripeKey=await readSecret('STRIPE_SECRET_KEY');if(!stripeKey)return json({error:'Stripe server credential is unavailable'},503);
  const stripe=new Stripe(stripeKey,{httpClient:Stripe.createFetchHttpClient()}),results:Result[]=[];

  const{data:ocCandidates,error:ocErr}=await admin.from('oc_booking_payments').select('*').in('status',['pending_authorization','requires_action','authorized','capture_pending']).limit(50);if(ocErr)throw ocErr;
  for(const p of ocCandidates||[]){try{
    const{data:b}=await admin.from('oc_bookings').select('status,cancelled_by,cancellation_fee_cents,cancellation_provider_compensation_cents').eq('id',p.booking_id).maybeSingle();
    if(!b||b.status!=='canceled'||!['customer','customer_no_show'].includes(String(b.cancelled_by||'')))continue;
    const settlement=b.cancelled_by==='customer_no_show'?'customer_no_show':'customer_cancellation',fee=Math.max(0,Math.round(Number(b.cancellation_fee_cents||0))),provider=Math.max(0,Math.round(Number(b.cancellation_provider_compensation_cents||0))),platform=Math.max(0,fee-provider);
    const patch:any={settlement_type:settlement,cancellation_fee_cents:fee,original_platform_fee:p.original_platform_fee??p.platform_fee,original_provider_amount:p.original_provider_amount??p.provider_amount,platform_fee:platform,provider_amount:provider,updated_at:new Date().toISOString()};if(fee>0)patch.status='capture_pending';const{error}=await admin.from('oc_booking_payments').update(patch).eq('id',p.id);if(error)throw error;
    if(!p.stripe_payment_intent_id){if(fee===0){await admin.from('oc_booking_payments').update({status:'authorization_canceled',updated_at:new Date().toISOString()}).eq('id',p.id);results.push({kind:'on_call',phase:'settlement',id:p.id,status:'reconciled',message:'No PaymentIntent to cancel'});continue}throw new Error('Settlement fee requires a PaymentIntent')}
    let pi=await stripe.paymentIntents.retrieve(p.stripe_payment_intent_id);const prefix=settlement==='customer_no_show'?'oc-no-show':'oc-cancel-booking';
    if(fee===0){if(pi.status!=='canceled'){if(pi.status==='succeeded')throw new Error('Cannot free-cancel an already captured PaymentIntent');pi=await stripe.paymentIntents.cancel(pi.id,{cancellation_reason:'requested_by_customer'},{idempotencyKey:`${prefix}-${p.id}-free-v1`})}await admin.from('oc_booking_payments').update({status:'authorization_canceled',canceled_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',p.id);results.push({kind:'on_call',phase:'settlement',id:p.id,status:'reconciled',message:'Authorization canceled'});continue}
    if(pi.status==='requires_capture')pi=await stripe.paymentIntents.capture(pi.id,{amount_to_capture:fee,final_capture:true,metadata:{settlement_type:settlement,cancellation_fee_cents:String(fee)}},{idempotencyKey:`${prefix}-${p.id}-${fee}-v2`});if(pi.status!=='succeeded')throw new Error(`Settlement PaymentIntent is ${pi.status}`);
    const chargeId=typeof pi.latest_charge==='string'?pi.latest_charge:pi.latest_charge?.id||p.stripe_charge_id||null;await admin.from('oc_booking_payments').update({status:provider>0?'transfer_pending':'captured',amount_captured:pi.amount_received??fee,stripe_charge_id:chargeId,captured_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',p.id);results.push({kind:'on_call',phase:'settlement',id:p.id,status:'reconciled',message:`${settlement} captured`});
  }catch(e){results.push({kind:'on_call',phase:'settlement',id:p.id,status:'failed',message:e instanceof Error?e.message:String(e)})}}

  const{data:sosCandidates,error:sosErr}=await admin.from('sos_payments').select('*').in('payment_status',['pending','requires_action','authorized']).limit(50);if(sosErr)throw sosErr;
  for(const p of sosCandidates||[]){try{
    const{data:m}=await admin.from('sos_missions').select('status,cancel_reason,cancellation_fee,cancellation_hero_compensation').eq('id',p.mission_id).maybeSingle();
    const isCancel=m?.status==='canceled_by_citizen',isNoShow=m?.status==='canceled_by_system'&&m?.cancel_reason==='customer_no_show';if(!m||(!isCancel&&!isNoShow))continue;
    const settlement=isNoShow?'customer_no_show':'customer_cancellation',fee=Math.max(0,Number(m.cancellation_fee||0)),heroComp=Math.max(0,Number(m.cancellation_hero_compensation||0)),platform=Math.max(0,fee-heroComp),feeCents=Math.round(fee*100);
    const{error}=await admin.from('sos_payments').update({settlement_type:settlement,cancellation_fee:fee,original_platform_fee:p.original_platform_fee??p.platform_fee,original_hero_payout:p.original_hero_payout??p.hero_payout,platform_fee:platform,hero_payout:heroComp,updated_at:new Date().toISOString()}).eq('id',p.id);if(error)throw error;
    if(!p.stripe_payment_intent_id){if(feeCents===0){await admin.from('sos_payments').update({payment_status:'canceled',escrow_status:'released_to_customer',updated_at:new Date().toISOString()}).eq('id',p.id);results.push({kind:'sos',phase:'settlement',id:p.id,status:'reconciled',message:'No PaymentIntent to cancel'});continue}throw new Error('Settlement fee requires a PaymentIntent')}
    let pi=await stripe.paymentIntents.retrieve(p.stripe_payment_intent_id);const prefix=settlement==='customer_no_show'?'sos-no-show':'sos-cancel-mission';
    if(feeCents===0){if(pi.status!=='canceled'){if(pi.status==='succeeded')throw new Error('Cannot free-cancel an already captured PaymentIntent');pi=await stripe.paymentIntents.cancel(pi.id,{cancellation_reason:'requested_by_customer'},{idempotencyKey:`${prefix}-${p.id}-free-v1`})}await admin.from('sos_payments').update({payment_status:'canceled',escrow_status:'released_to_customer',updated_at:new Date().toISOString()}).eq('id',p.id);results.push({kind:'sos',phase:'settlement',id:p.id,status:'reconciled',message:'Authorization canceled'});continue}
    if(pi.status==='requires_capture')pi=await stripe.paymentIntents.capture(pi.id,{amount_to_capture:feeCents,final_capture:true,metadata:{settlement_type:settlement,cancellation_fee:String(fee)}},{idempotencyKey:`${prefix}-${p.id}-${feeCents}-v2`});if(pi.status!=='succeeded')throw new Error(`Settlement PaymentIntent is ${pi.status}`);
    const chargeId=typeof pi.latest_charge==='string'?pi.latest_charge:pi.latest_charge?.id||p.stripe_charge_id||null;await admin.from('sos_payments').update({payment_status:heroComp>0?'transfer_pending':'captured',escrow_status:'held_for_release',stripe_charge_id:chargeId,captured_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',p.id);results.push({kind:'sos',phase:'settlement',id:p.id,status:'reconciled',message:`${settlement} captured`});
  }catch(e){results.push({kind:'sos',phase:'settlement',id:p.id,status:'failed',message:e instanceof Error?e.message:String(e)})}}

  const{data:ocTransfers,error:ocTransferErr}=await admin.from('oc_booking_payments').select('id,booking_id,provider_id,provider_amount,currency,stripe_transfer_id,status').eq('status','transfer_pending').limit(50);if(ocTransferErr)throw ocTransferErr;
  for(const p of ocTransfers||[]){try{if(p.stripe_transfer_id){await admin.from('oc_booking_payments').update({status:'transferred',transferred_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',p.id);results.push({kind:'on_call',phase:'transfer',id:p.id,status:'released',transfer_id:p.stripe_transfer_id});continue}if(!p.provider_id){results.push({kind:'on_call',phase:'transfer',id:p.id,status:'skipped',message:'Provider assignment unavailable'});continue}const{data:provider}=await admin.from('oc_provider_profiles').select('stripe_account_id,stripe_payouts_enabled,stripe_account_api_version,stripe_transfer_status').eq('id',p.provider_id).maybeSingle();const ready=provider?.stripe_account_api_version==='v2'?provider?.stripe_transfer_status==='active':Boolean(provider?.stripe_payouts_enabled);if(!provider?.stripe_account_id||!ready){results.push({kind:'on_call',phase:'transfer',id:p.id,status:'skipped',message:'Provider payout account not ready'});continue}const amount=Math.round(Number(p.provider_amount||0));if(amount<=0){await admin.from('oc_booking_payments').update({status:'captured',updated_at:new Date().toISOString()}).eq('id',p.id);continue}const transfer=await stripe.transfers.create({amount,currency:p.currency||'usd',destination:provider.stripe_account_id,transfer_group:`oc_booking_${p.booking_id}`,metadata:{brand:'ON_CALL',booking_id:p.booking_id,payment_id:p.id}},{idempotencyKey:`oc-payment-${p.id}-transfer-v2`});const now=new Date().toISOString();await admin.from('oc_booking_payments').update({status:'transferred',stripe_transfer_id:transfer.id,transferred_at:now,updated_at:now}).eq('id',p.id);results.push({kind:'on_call',phase:'transfer',id:p.id,status:'released',transfer_id:transfer.id})}catch(e){results.push({kind:'on_call',phase:'transfer',id:p.id,status:'failed',message:e instanceof Error?e.message:String(e)})}}

  const{data:sosTransfers,error:sosTransferErr}=await admin.from('sos_payments').select('id,mission_id,hero_id,hero_payout,currency,stripe_transfer_id,stripe_charge_id,payment_status,settlement_type').eq('payment_status','transfer_pending').limit(50);if(sosTransferErr)throw sosTransferErr;
  for(const p of sosTransfers||[]){try{if(p.stripe_transfer_id){const now=new Date().toISOString();await admin.from('sos_payments').update({payment_status:'released',escrow_status:'released_to_hero',released_at:now,updated_at:now}).eq('id',p.id);results.push({kind:'sos',phase:'transfer',id:p.id,status:'released',transfer_id:p.stripe_transfer_id});continue}if(!p.hero_id||!p.stripe_charge_id){results.push({kind:'sos',phase:'transfer',id:p.id,status:'skipped',message:'Hero assignment or captured charge unavailable'});continue}const{data:hero}=await admin.from('sos_heroes').select('stripe_connect_id,stripe_connect_api_version,stripe_transfer_status').eq('id',p.hero_id).maybeSingle();const ready=hero?.stripe_connect_api_version==='v2'?hero?.stripe_transfer_status==='active':Boolean(hero?.stripe_connect_id);if(!hero?.stripe_connect_id||!ready){results.push({kind:'sos',phase:'transfer',id:p.id,status:'skipped',message:'Hero payout account not ready'});continue}const amount=Math.round(Number(p.hero_payout||0)*100);if(amount<=0){await admin.from('sos_payments').update({payment_status:'captured',escrow_status:'held_for_release',updated_at:new Date().toISOString()}).eq('id',p.id);continue}const settlement=String(p.settlement_type||'service'),key=settlement==='customer_cancellation'?`sos-cancel-fee-transfer-${p.mission_id}-v1`:settlement==='customer_no_show'?`sos-customer-no-show-transfer-${p.mission_id}-v1`:`sos-release-${p.mission_id}`,metadata=settlement==='service'||settlement==='hero_reassignment'?{mission_id:p.mission_id}:{mission_id:p.mission_id,settlement_type:settlement};const transfer=await stripe.transfers.create({amount,currency:p.currency||'usd',destination:hero.stripe_connect_id,source_transaction:p.stripe_charge_id,transfer_group:`sos_mission_${p.mission_id}`,metadata},{idempotencyKey:key});const now=new Date().toISOString();await admin.from('sos_payments').update({payment_status:'released',escrow_status:'released_to_hero',stripe_transfer_id:transfer.id,released_at:now,updated_at:now}).eq('id',p.id);results.push({kind:'sos',phase:'transfer',id:p.id,status:'released',transfer_id:transfer.id})}catch(e){results.push({kind:'sos',phase:'transfer',id:p.id,status:'failed',message:e instanceof Error?e.message:String(e)})}}

  return json({ok:true,summary:{on_call:{failures:results.filter(r=>r.kind==='on_call'&&r.status==='failed').length},sos:{failures:results.filter(r=>r.kind==='sos'&&r.status==='failed').length}},results});
 }catch(e){console.error('marketplace payout retry failed',e);return json({error:e instanceof Error?e.message:'Unexpected error'},500)}
});