import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.112.0";
import Stripe from "npm:stripe@18.5.0";

const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}});
const sha256=async(value:string)=>{const bytes=new TextEncoder().encode(value);const digest=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('')};
const safeEqual=(a:string,b:string)=>{if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0};
type RetryResult={kind:'on_call'|'sos',phase:'settlement'|'transfer',id:string,status:'released'|'reconciled'|'skipped'|'failed',message?:string,transfer_id?:string};

Deno.serve(async(req)=>{
 if(req.method!=='POST')return json({error:'Method not allowed'},405);
 try{
  const supplied=req.headers.get('x-worker-token')||'';if(!supplied)return json({error:'Unauthorized'},401);
  const url=Deno.env.get('SUPABASE_URL')||'',service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';if(!url||!service)return json({error:'Database runtime unavailable'},503);
  const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});
  const{data:worker,error:workerError}=await admin.from('internal_worker_auth').select('token_hash').eq('worker_name','marketplace_payout_retry').maybeSingle();
  if(workerError||!worker?.token_hash)return json({error:'Worker authentication is unavailable'},503);
  const candidate=await sha256(supplied);if(!safeEqual(candidate,String(worker.token_hash)))return json({error:'Unauthorized'},401);
  const readSecret=async(name:string)=>{const runtime=Deno.env.get(name);if(runtime)return runtime;const{data,error}=await admin.rpc('sos_get_runtime_secret',{secret_name:name});return error||!data?'':String(data)};
  const stripeKey=await readSecret('STRIPE_SECRET_KEY');if(!stripeKey)return json({error:'Stripe server credential is unavailable'},503);
  const stripe=new Stripe(stripeKey,{httpClient:Stripe.createFetchHttpClient()});const results:RetryResult[]=[];

  const{data:ocCandidates,error:ocCandidateError}=await admin.from('oc_booking_payments')
    .select('id,booking_id,provider_id,amount_authorized,platform_fee,provider_amount,tax_cents,currency,stripe_payment_intent_id,stripe_charge_id,status,settlement_type,cancellation_fee_cents,original_platform_fee,original_provider_amount')
    .in('status',['pending_authorization','requires_action','authorized','capture_pending']).limit(50);
  if(ocCandidateError)throw ocCandidateError;
  for(const payment of ocCandidates||[]){
    try{
      const{data:booking}=await admin.from('oc_bookings').select('status,cancelled_by,cancellation_fee_cents,cancellation_provider_compensation_cents').eq('id',payment.booking_id).maybeSingle();
      if(!booking||booking.status!=='canceled'||booking.cancelled_by!=='customer')continue;
      const fee=Math.max(0,Math.round(Number(booking.cancellation_fee_cents||0))),provider=Math.max(0,Math.round(Number(booking.cancellation_provider_compensation_cents||0))),platform=Math.max(0,fee-provider);
      const patch:any={settlement_type:'customer_cancellation',cancellation_fee_cents:fee,original_platform_fee:payment.original_platform_fee??payment.platform_fee,original_provider_amount:payment.original_provider_amount??payment.provider_amount,platform_fee:platform,provider_amount:provider,updated_at:new Date().toISOString()};if(fee>0)patch.status='capture_pending';
      const{error:prepError}=await admin.from('oc_booking_payments').update(patch).eq('id',payment.id);if(prepError)throw prepError;
      if(!payment.stripe_payment_intent_id){if(fee===0){await admin.from('oc_booking_payments').update({status:'authorization_canceled',updated_at:new Date().toISOString()}).eq('id',payment.id);results.push({kind:'on_call',phase:'settlement',id:payment.id,status:'reconciled',message:'No PaymentIntent to cancel'});continue;}throw new Error('Cancellation fee requires a PaymentIntent')}
      let pi=await stripe.paymentIntents.retrieve(payment.stripe_payment_intent_id);
      if(fee===0){if(pi.status!=='canceled'){if(pi.status==='succeeded')throw new Error('Cannot free-cancel an already captured PaymentIntent');pi=await stripe.paymentIntents.cancel(pi.id,{cancellation_reason:'requested_by_customer'},{idempotencyKey:`oc-cancel-booking-${payment.id}-free-v1`})}await admin.from('oc_booking_payments').update({status:'authorization_canceled',canceled_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',payment.id);results.push({kind:'on_call',phase:'settlement',id:payment.id,status:'reconciled',message:'Authorization canceled'});continue;}
      if(pi.status==='requires_capture')pi=await stripe.paymentIntents.capture(pi.id,{amount_to_capture:fee,final_capture:true,metadata:{settlement_type:'customer_cancellation',cancellation_fee_cents:String(fee)}},{idempotencyKey:`oc-cancel-booking-${payment.id}-${fee}-v2`});
      if(pi.status!=='succeeded')throw new Error(`Cancellation PaymentIntent is ${pi.status}`);const chargeId=typeof pi.latest_charge==='string'?pi.latest_charge:pi.latest_charge?.id||payment.stripe_charge_id||null;await admin.from('oc_booking_payments').update({status:provider>0?'transfer_pending':'captured',amount_captured:pi.amount_received??fee,stripe_charge_id:chargeId,captured_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',payment.id);results.push({kind:'on_call',phase:'settlement',id:payment.id,status:'reconciled',message:'Cancellation fee captured'});
    }catch(error){results.push({kind:'on_call',phase:'settlement',id:payment.id,status:'failed',message:error instanceof Error?error.message:String(error)})}
  }

  const{data:sosCandidates,error:sosCandidateError}=await admin.from('sos_payments')
    .select('id,mission_id,hero_id,amount,platform_fee,hero_payout,currency,stripe_payment_intent_id,stripe_charge_id,payment_status,settlement_type,cancellation_fee,original_platform_fee,original_hero_payout')
    .in('payment_status',['pending','requires_action','authorized']).limit(50);
  if(sosCandidateError)throw sosCandidateError;
  for(const payment of sosCandidates||[]){
    try{
      const{data:mission}=await admin.from('sos_missions').select('status,cancellation_fee,cancellation_hero_compensation').eq('id',payment.mission_id).maybeSingle();if(!mission||mission.status!=='canceled_by_citizen')continue;
      const fee=Math.max(0,Number(mission.cancellation_fee||0)),heroComp=Math.max(0,Number(mission.cancellation_hero_compensation||0)),platform=Math.max(0,fee-heroComp);
      const{error:prepError}=await admin.from('sos_payments').update({settlement_type:'customer_cancellation',cancellation_fee:fee,original_platform_fee:payment.original_platform_fee??payment.platform_fee,original_hero_payout:payment.original_hero_payout??payment.hero_payout,platform_fee:platform,hero_payout:heroComp,updated_at:new Date().toISOString()}).eq('id',payment.id);if(prepError)throw prepError;
      if(!payment.stripe_payment_intent_id){if(fee===0){await admin.from('sos_payments').update({payment_status:'canceled',escrow_status:'released_to_customer',updated_at:new Date().toISOString()}).eq('id',payment.id);results.push({kind:'sos',phase:'settlement',id:payment.id,status:'reconciled',message:'No PaymentIntent to cancel'});continue;}throw new Error('Cancellation fee requires a PaymentIntent')}
      let pi=await stripe.paymentIntents.retrieve(payment.stripe_payment_intent_id);const feeCents=Math.round(fee*100);
      if(feeCents===0){if(pi.status!=='canceled'){if(pi.status==='succeeded')throw new Error('Cannot free-cancel an already captured PaymentIntent');pi=await stripe.paymentIntents.cancel(pi.id,{cancellation_reason:'requested_by_customer'},{idempotencyKey:`sos-cancel-mission-${payment.id}-free-v1`})}await admin.from('sos_payments').update({payment_status:'canceled',escrow_status:'released_to_customer',updated_at:new Date().toISOString()}).eq('id',payment.id);results.push({kind:'sos',phase:'settlement',id:payment.id,status:'reconciled',message:'Authorization canceled'});continue;}
      if(pi.status==='requires_capture')pi=await stripe.paymentIntents.capture(pi.id,{amount_to_capture:feeCents,final_capture:true,metadata:{settlement_type:'customer_cancellation',cancellation_fee:String(fee)}},{idempotencyKey:`sos-cancel-mission-${payment.id}-${feeCents}-v2`});if(pi.status!=='succeeded')throw new Error(`Cancellation PaymentIntent is ${pi.status}`);const chargeId=typeof pi.latest_charge==='string'?pi.latest_charge:pi.latest_charge?.id||payment.stripe_charge_id||null;await admin.from('sos_payments').update({payment_status:heroComp>0?'transfer_pending':'captured',escrow_status:'held_for_release',stripe_charge_id:chargeId,captured_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',payment.id);results.push({kind:'sos',phase:'settlement',id:payment.id,status:'reconciled',message:'Cancellation fee captured'});
    }catch(error){results.push({kind:'sos',phase:'settlement',id:payment.id,status:'failed',message:error instanceof Error?error.message:String(error)})}
  }

  const{data:ocRows,error:ocError}=await admin.from('oc_booking_payments').select('id,booking_id,provider_id,provider_amount,currency,stripe_transfer_id,status').eq('status','transfer_pending').limit(50);if(ocError)throw ocError;
  for(const payment of ocRows||[]){try{if(payment.stripe_transfer_id){await admin.from('oc_booking_payments').update({status:'transferred',transferred_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',payment.id);results.push({kind:'on_call',phase:'transfer',id:payment.id,status:'released',transfer_id:payment.stripe_transfer_id,message:'Existing transfer reconciled'});continue}if(!payment.provider_id){results.push({kind:'on_call',phase:'transfer',id:payment.id,status:'skipped',message:'Provider assignment unavailable'});continue}const{data:provider}=await admin.from('oc_provider_profiles').select('stripe_account_id,stripe_payouts_enabled,stripe_account_api_version,stripe_transfer_status').eq('id',payment.provider_id).maybeSingle();const ready=provider?.stripe_account_api_version==='v2'?provider?.stripe_transfer_status==='active':Boolean(provider?.stripe_payouts_enabled);if(!provider?.stripe_account_id||!ready){results.push({kind:'on_call',phase:'transfer',id:payment.id,status:'skipped',message:'Provider payout account not ready'});continue}const amount=Math.round(Number(payment.provider_amount||0));if(amount<=0){await admin.from('oc_booking_payments').update({status:'captured',updated_at:new Date().toISOString()}).eq('id',payment.id);results.push({kind:'on_call',phase:'transfer',id:payment.id,status:'reconciled',message:'No provider payout due'});continue}const transfer=await stripe.transfers.create({amount,currency:payment.currency||'usd',destination:provider.stripe_account_id,transfer_group:`oc_booking_${payment.booking_id}`,metadata:{brand:'ON_CALL',booking_id:payment.booking_id,payment_id:payment.id}},{idempotencyKey:`oc-payment-${payment.id}-transfer-v2`});const now=new Date().toISOString();await admin.from('oc_booking_payments').update({status:'transferred',stripe_transfer_id:transfer.id,transferred_at:now,updated_at:now}).eq('id',payment.id);results.push({kind:'on_call',phase:'transfer',id:payment.id,status:'released',transfer_id:transfer.id})}catch(error){results.push({kind:'on_call',phase:'transfer',id:payment.id,status:'failed',message:error instanceof Error?error.message:String(error)})}}

  const{data:sosRows,error:sosError}=await admin.from('sos_payments').select('id,mission_id,hero_id,hero_payout,currency,stripe_transfer_id,stripe_charge_id,payment_status,settlement_type').eq('payment_status','transfer_pending').limit(50);if(sosError)throw sosError;
  for(const payment of sosRows||[]){try{if(payment.stripe_transfer_id){const now=new Date().toISOString();await admin.from('sos_payments').update({payment_status:'released',escrow_status:'released_to_hero',released_at:now,updated_at:now}).eq('id',payment.id);results.push({kind:'sos',phase:'transfer',id:payment.id,status:'released',transfer_id:payment.stripe_transfer_id,message:'Existing transfer reconciled'});continue}if(!payment.hero_id){results.push({kind:'sos',phase:'transfer',id:payment.id,status:'skipped',message:'Hero assignment unavailable'});continue}if(!payment.stripe_charge_id){results.push({kind:'sos',phase:'transfer',id:payment.id,status:'skipped',message:'Captured charge ID unavailable'});continue}const{data:hero}=await admin.from('sos_heroes').select('stripe_connect_id,stripe_connect_api_version,stripe_transfer_status').eq('id',payment.hero_id).maybeSingle();const ready=hero?.stripe_connect_api_version==='v2'?hero?.stripe_transfer_status==='active':Boolean(hero?.stripe_connect_id);if(!hero?.stripe_connect_id||!ready){results.push({kind:'sos',phase:'transfer',id:payment.id,status:'skipped',message:'Hero payout account not ready'});continue}const amount=Math.round(Number(payment.hero_payout||0)*100);if(amount<=0){await admin.from('sos_payments').update({payment_status:'captured',escrow_status:'held_for_release',updated_at:new Date().toISOString()}).eq('id',payment.id);results.push({kind:'sos',phase:'transfer',id:payment.id,status:'reconciled',message:'No Hero payout due'});continue}const settlement=String(payment.settlement_type||'service');const idempotencyKey=settlement==='customer_cancellation'?`sos-cancel-fee-transfer-${payment.mission_id}-v1`:settlement==='customer_no_show'?`sos-customer-no-show-transfer-${payment.mission_id}-v1`:`sos-release-${payment.mission_id}`;const metadata=settlement==='service'||settlement==='hero_reassignment'?{mission_id:payment.mission_id}:{mission_id:payment.mission_id,settlement_type:settlement};const transfer=await stripe.transfers.create({amount,currency:payment.currency||'usd',destination:hero.stripe_connect_id,source_transaction:payment.stripe_charge_id,transfer_group:`sos_mission_${payment.mission_id}`,metadata},{idempotencyKey});const now=new Date().toISOString();await admin.from('sos_payments').update({payment_status:'released',escrow_status:'released_to_hero',stripe_transfer_id:transfer.id,released_at:now,updated_at:now}).eq('id',payment.id);results.push({kind:'sos',phase:'transfer',id:payment.id,status:'released',transfer_id:transfer.id})}catch(error){results.push({kind:'sos',phase:'transfer',id:payment.id,status:'failed',message:error instanceof Error?error.message:String(error)})}}
  const summary={on_call:{settlement_failures:results.filter(r=>r.kind==='on_call'&&r.phase==='settlement'&&r.status==='failed').length,transfer_failures:results.filter(r=>r.kind==='on_call'&&r.phase==='transfer'&&r.status==='failed').length},sos:{settlement_failures:results.filter(r=>r.kind==='sos'&&r.phase==='settlement'&&r.status==='failed').length,transfer_failures:results.filter(r=>r.kind==='sos'&&r.phase==='transfer'&&r.status==='failed').length}};return json({ok:true,summary,results});
 }catch(error){console.error('marketplace payout retry failed',error);return json({error:error instanceof Error?error.message:'Unexpected error'},500)}
});