'use client';

import React,{useEffect,useState}from'react';
import { sosSupabase } from '../../../lib/sosSupabaseClient';

export default function PasswordResetPage(){
  const[ready,setReady]=useState(false);const[password,setPassword]=useState('');const[confirm,setConfirm]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[done,setDone]=useState(false);
  const portal=typeof window!=='undefined'&&new URLSearchParams(window.location.search).get('portal')==='hero'?'hero':'app';
  useEffect(()=>{let active=true;(async()=>{try{const code=new URLSearchParams(window.location.search).get('code');if(code){const{error:exchangeError}=await sosSupabase.auth.exchangeCodeForSession(code);if(exchangeError)throw exchangeError}const{data}=await sosSupabase.auth.getSession();if(!data.session)throw new Error('This password reset link is expired or invalid. Request a new one from the S.O.S. login screen.');if(active)setReady(true)}catch(e){if(active)setError(e?.message||'This password reset link is invalid.')}})();return()=>{active=false}},[]);
  const submit=async e=>{e.preventDefault();if(busy)return;setError('');if(password.length<8)return setError('Use at least 8 characters.');if(password!==confirm)return setError('Passwords do not match.');setBusy(true);try{const{error:updateError}=await sosSupabase.auth.updateUser({password});if(updateError)throw updateError;localStorage.removeItem('sos_session');await sosSupabase.auth.signOut();setDone(true)}catch(e){setError(e?.message||'Password could not be updated.')}finally{setBusy(false)}};
  return <main style={{minHeight:'100dvh',background:'radial-gradient(circle at 50% 5%,#263a52,#05080d 62%)',color:'#fff',display:'grid',placeItems:'center',padding:20,fontFamily:'DM Sans, sans-serif'}}><section style={{width:'min(480px,100%)',padding:28,borderRadius:28,background:'rgba(10,17,27,.96)',border:'1px solid rgba(255,138,76,.18)',boxShadow:'0 35px 100px rgba(0,0,0,.5)'}}><div style={{width:62,height:62,borderRadius:20,display:'grid',placeItems:'center',background:'linear-gradient(145deg,#ff7a42,#b72f0c)',fontWeight:900,marginBottom:18}}>SOS</div>{done?<><small style={{color:'#72d69b',fontWeight:900,letterSpacing:'.12em'}}>PASSWORD UPDATED</small><h1 style={{fontSize:36,lineHeight:1,margin:'8px 0'}}>Your account is secure.</h1><p style={{color:'rgba(235,241,248,.62)',lineHeight:1.6}}>Sign in again with your new password.</p><a href={portal==='hero'?'/hero':'/app'} style={{display:'grid',placeItems:'center',height:50,borderRadius:14,background:'#ff7a42',color:'#fff',fontWeight:900,textDecoration:'none'}}>Return to {portal==='hero'?'Hero Command':'S.O.S.'}</a></>:<><small style={{color:'#ffbd63',fontWeight:900,letterSpacing:'.12em'}}>SECURE ACCOUNT RECOVERY</small><h1 style={{fontSize:36,lineHeight:1,margin:'8px 0'}}>Choose a new password.</h1><p style={{color:'rgba(235,241,248,.62)',lineHeight:1.6}}>This reset session is valid only for the account that opened the emailed recovery link.</p>{error&&<div style={{padding:11,borderRadius:12,background:'rgba(239,68,68,.12)',color:'#ff9c92',fontSize:12,margin:'12px 0'}}>{error}</div>}{ready&&<form onSubmit={submit}><label style={{display:'grid',gap:6,marginTop:14,fontSize:10,color:'#ffbd63',fontWeight:900}}>NEW PASSWORD<input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} style={{height:48,borderRadius:13,border:'1px solid rgba(255,255,255,.12)',background:'#07111d',color:'#fff',padding:'0 12px'}}/></label><label style={{display:'grid',gap:6,marginTop:12,fontSize:10,color:'#ffbd63',fontWeight:900}}>CONFIRM PASSWORD<input required minLength={8} type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} style={{height:48,borderRadius:13,border:'1px solid rgba(255,255,255,.12)',background:'#07111d',color:'#fff',padding:'0 12px'}}/></label><button disabled={busy} style={{width:'100%',height:50,marginTop:16,border:0,borderRadius:14,background:'#ff7a42',color:'#fff',fontWeight:900}}>{busy?'Updating…':'Set new password'}</button></form>}</>}</section></main>;
}
