'use client';

import {useEffect,useState} from 'react';

const SB='https://cxdqkjvtpilvouwtbgdy.supabase.co';
const SK='sb_publishable_x_QDbPwZuhbqB1bd58MLvg_ADSiFODN';
const readSession=()=>{try{const s=JSON.parse(localStorage.getItem('sos_session')||'null');return s?.access_token&&s?.user?s:null}catch{return null}};

export default function SOSAccountDeletionHost(){
 const[session,setSession]=useState(null),[open,setOpen]=useState(false),[confirmText,setConfirmText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const sync=()=>setSession(readSession());sync();window.addEventListener('storage',sync);window.addEventListener('sos:session-refreshed',sync);return()=>{window.removeEventListener('storage',sync);window.removeEventListener('sos:session-refreshed',sync)}},[]);
 if(!session||typeof window==='undefined'||window.location.pathname.startsWith('/ops')||window.location.pathname==='/privacy'||window.location.pathname==='/terms'||window.location.pathname==='/legal')return null;
 const remove=async()=>{if(confirmText!=='DELETE'||busy)return;setBusy(true);setError('');try{const current=readSession();if(!current?.access_token)throw new Error('Your S.O.S. session expired. Sign in again before deleting the account.');const r=await fetch(`${SB}/functions/v1/delete-account`,{method:'POST',headers:{apikey:SK,Authorization:`Bearer ${current.access_token}`,'Content-Type':'application/json'},body:'{}'});const d=await r.json().catch(()=>null);if(!r.ok||!d?.ok)throw new Error(d?.error||'Account deletion could not be completed.');localStorage.removeItem('sos_session');localStorage.removeItem('sos_password_recovery');sessionStorage.clear();window.location.replace('/?account=deleted')}catch(e){setError(e instanceof Error?e.message:'Account deletion could not be completed.');setBusy(false)}};
 return <><button type="button" onClick={()=>{setOpen(true);setConfirmText('');setError('')}} style={{position:'fixed',right:14,bottom:145,zIndex:1650,border:'1px solid rgba(255,255,255,.14)',borderRadius:999,padding:'8px 11px',background:'rgba(3,8,14,.9)',backdropFilter:'blur(14px)',color:'rgba(255,255,255,.72)',fontSize:9,fontWeight:850,letterSpacing:'.08em',cursor:'pointer'}}>ACCOUNT & PRIVACY</button>{open&&<div role="dialog" aria-modal="true" onMouseDown={e=>{if(e.currentTarget===e.target&&!busy)setOpen(false)}} style={{position:'fixed',inset:0,zIndex:5200,display:'grid',placeItems:'center',padding:18,background:'rgba(2,6,11,.82)',backdropFilter:'blur(10px)'}}><section style={{width:'min(480px,100%)',borderRadius:24,padding:22,background:'#081421',color:'#fff',border:'1px solid rgba(255,255,255,.11)',boxShadow:'0 30px 90px rgba(0,0,0,.48)'}}><div style={{fontSize:9,fontWeight:950,letterSpacing:'.16em',color:'#ff9d9d'}}>ACCOUNT DELETION</div><h2 style={{margin:'8px 0',fontSize:26,letterSpacing:'-.04em'}}>Delete your S.O.S. account?</h2><p style={{margin:0,color:'rgba(255,255,255,.68)',fontSize:12,lineHeight:1.55}}>This permanently removes your sign-in identity and active personal profile data. Financial, dispute and safety records may remain only in anonymized form where retention is required.</p><label style={{display:'block',marginTop:16,fontSize:10,fontWeight:850,color:'rgba(255,255,255,.72)'}}>Type DELETE to confirm<input autoComplete="off" value={confirmText} onChange={e=>setConfirmText(e.target.value.toUpperCase())} placeholder="DELETE" style={{width:'100%',marginTop:7,padding:'12px 13px',borderRadius:12,border:'1px solid rgba(255,255,255,.13)',background:'#040b13',color:'#fff',outline:0}}/></label>{error&&<div style={{marginTop:11,padding:'10px 11px',borderRadius:11,background:'rgba(194,54,54,.16)',color:'#ffb4b4',fontSize:11}}>{error}</div>}<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:9,marginTop:16}}><button disabled={busy} onClick={()=>setOpen(false)} style={{border:'1px solid rgba(255,255,255,.12)',borderRadius:12,padding:12,background:'transparent',color:'#fff',fontWeight:850}}>Keep account</button><button disabled={busy||confirmText!=='DELETE'} onClick={remove} style={{border:0,borderRadius:12,padding:12,background:confirmText==='DELETE'?'#dc3d4b':'rgba(255,255,255,.08)',color:'#fff',fontWeight:900,cursor:confirmText==='DELETE'?'pointer':'not-allowed'}}>{busy?'Deleting…':'Delete permanently'}</button></div></section></div>}</>;
}
