'use client';

import React,{useEffect,useState}from'react';
const SB='https://cxdqkjvtpilvouwtbgdy.supabase.co';
const SK='sb_publishable_x_QDbPwZuhbqB1bd58MLvg_ADSiFODN';
const stored=()=>{try{const s=JSON.parse(localStorage.getItem('sos_session'));return s?.access_token&&s?.user?s:null}catch{return null}};
const request=async(path,{method='GET',token,body}={})=>{const r=await fetch(`${SB}${path}`,{method,headers:{apikey:SK,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||d?.error_description||d?.error||'Request failed');return d};

export default function SOSCustomerCancellationHost(){
 const[mission,setMission]=useState(null),[quote,setQuote]=useState(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{let disposed=false;const load=async()=>{const s=stored();if(!s)return;const us=await request(`/rest/v1/sos_users?auth_id=eq.${s.user.id}&select=id,role&limit=1`,{token:s.access_token});const u=us?.[0];if(!u||u.role!=='citizen')return;const ms=await request(`/rest/v1/sos_missions?citizen_id=eq.${u.id}&status=in.(assigned,en_route,on_site)&select=id,status,requested_service_name&order=created_at.desc&limit=1`,{token:s.access_token});if(!disposed)setMission(ms?.[0]||null)};load().catch(()=>{});const t=setInterval(()=>load().catch(()=>{}),8000);return()=>{disposed=true;clearInterval(t)}},[]);
 const invoke=async(body)=>{const s=stored();if(!s)throw new Error('Sign in again to continue.');return request('/functions/v1/sos-cancel-mission',{method:'POST',token:s.access_token,body})};
 const start=async()=>{if(!mission||busy)return;setBusy(true);setError('');try{const q=await invoke({missionId:mission.id,action:'quote'});setQuote(q);setOpen(true)}catch(e){setError(e.message)}finally{setBusy(false)}};
 const cancel=async()=>{if(!mission||!quote||busy)return;setBusy(true);setError('');try{const d=await invoke({missionId:mission.id,action:'cancel',expectedFeeAmount:Number(quote.feeAmount||0),reason:quote.reason});setOpen(false);setQuote(null);setMission(null);setNotice(Number(d.feeAmount||0)>0?`Mission canceled. $${Number(d.feeAmount).toFixed(2)} cancellation fee applied.`:'Mission canceled with no fee.');setTimeout(()=>setNotice(''),5000)}catch(e){setError(e.message)}finally{setBusy(false)}};
 if(!mission&&!open&&!notice&&!error)return null;
 return <>
  {mission&&!open&&<button type="button" onClick={start} disabled={busy} style={{position:'fixed',right:16,bottom:142,zIndex:1480,border:'1px solid rgba(255,255,255,.14)',borderRadius:999,padding:'10px 13px',background:'#111b25',color:'#fff',fontSize:9,fontWeight:900,letterSpacing:'.06em',boxShadow:'0 12px 36px rgba(0,0,0,.32)'}}>{busy?'CHECKING…':mission.status==='on_site'?'CANCEL / HERO ARRIVED':'CANCEL MISSION'}</button>}
  {open&&quote&&<div role="dialog" aria-modal="true" style={{position:'fixed',inset:0,zIndex:1800,display:'grid',placeItems:'end center',background:'rgba(3,8,15,.72)',backdropFilter:'blur(8px)',padding:16}}><section style={{width:'min(520px,100%)',borderRadius:24,padding:20,background:'#0d1722',color:'#fff',boxShadow:'0 30px 90px rgba(0,0,0,.52)',border:'1px solid rgba(255,255,255,.10)'}}><div style={{display:'flex',justifyContent:'space-between',gap:16}}><div><small style={{fontSize:9,fontWeight:900,letterSpacing:'.13em',color:'#ff8a5b'}}>MISSION CANCELLATION</small><h2 style={{fontSize:24,margin:'7px 0 5px'}}>Cancel {mission?.requested_service_name||'this mission'}?</h2><p style={{margin:0,color:'rgba(255,255,255,.65)',fontSize:12,lineHeight:1.5}}>{quote.reason}</p></div><button type="button" onClick={()=>{setOpen(false);setQuote(null);setError('')}} style={{width:34,height:34,borderRadius:12,border:0,background:'rgba(255,255,255,.08)',color:'#fff',fontSize:20}}>×</button></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginTop:18}}><div style={{padding:14,borderRadius:16,background:'rgba(255,255,255,.06)'}}><small style={{fontSize:8,color:'rgba(255,255,255,.5)',letterSpacing:'.08em'}}>CANCELLATION FEE</small><strong style={{display:'block',fontSize:26,marginTop:3}}>${Number(quote.feeAmount||0).toFixed(2)}</strong></div><div style={{padding:14,borderRadius:16,background:'rgba(255,255,255,.06)'}}><small style={{fontSize:8,color:'rgba(255,255,255,.5)',letterSpacing:'.08em'}}>HERO COMPENSATION</small><strong style={{display:'block',fontSize:26,marginTop:3}}>${Number(quote.heroCompensation||0).toFixed(2)}</strong></div></div><p style={{fontSize:10,lineHeight:1.55,color:'rgba(255,255,255,.52)',margin:'14px 0'}}>S.O.S. rechecks the mission state and quoted fee when you confirm. The remaining uncaptured authorization is released after a final partial capture.</p>{error&&<div style={{padding:10,borderRadius:12,background:'rgba(255,92,104,.12)',color:'#ff9aa2',fontSize:11,marginBottom:10}}>{error}</div>}<div style={{display:'grid',gridTemplateColumns:'1fr 1.5fr',gap:9}}><button type="button" onClick={()=>{setOpen(false);setQuote(null)}} disabled={busy} style={{padding:13,borderRadius:13,border:'1px solid rgba(255,255,255,.14)',background:'transparent',color:'#fff',fontWeight:800}}>Keep mission</button><button type="button" onClick={cancel} disabled={busy||!quote.canCancel} style={{padding:13,borderRadius:13,border:0,background:'#df4d3f',color:'#fff',fontWeight:900}}>{busy?'Canceling…':Number(quote.feeAmount||0)>0?`Cancel · $${Number(quote.feeAmount).toFixed(2)} fee`:'Cancel with no fee'}</button></div></section></div>}
  {notice&&<div role="status" style={{position:'fixed',right:16,top:78,zIndex:1750,width:'min(380px,calc(100vw - 32px))',padding:'12px 14px',borderRadius:14,background:'#111b25',color:'#fff',fontSize:11,boxShadow:'0 18px 50px rgba(0,0,0,.34)'}}>{notice}</div>}
  {error&&!open&&<div role="alert" style={{position:'fixed',right:16,top:78,zIndex:1750,width:'min(380px,calc(100vw - 32px))',padding:'12px 14px',borderRadius:14,background:'#3b1216',color:'#ffd8dc',fontSize:11}}>{error}</div>}
 </>;
}
