'use client';

import React,{useEffect,useMemo,useState}from'react';
import SOSMissionTracker from './SOSMissionTracker';
import{requestCustomerMission}from'../lib/sosMissionClient';

const SB='https://cxdqkjvtpilvouwtbgdy.supabase.co';
const SK='sb_publishable_x_QDbPwZuhbqB1bd58MLvg_ADSiFODN';
const authHeaders=(token=SK)=>({apikey:SK,Authorization:`Bearer ${token}`,'Content-Type':'application/json'});
const request=async(path,{method='GET',token=SK,body}={})=>{const response=await fetch(`${SB}${path}`,{method,headers:authHeaders(token),body:body===undefined?undefined:JSON.stringify(body)});const payload=await response.json().catch(()=>null);if(!response.ok)throw new Error(payload?.message||payload?.msg||payload?.error_description||payload?.error||'Request failed');return payload};
const storedSession=()=>{try{const value=JSON.parse(localStorage.getItem('sos_session'));if(!value?.access_token||!value?.user)return null;if(value.expires_at&&value.expires_at<Date.now()/1000)return null;return value}catch{return null}};
const locate=()=>new Promise(resolve=>{if(!navigator.geolocation){resolve({lat:null,lng:null,address:'Location unavailable'});return}navigator.geolocation.getCurrentPosition(position=>resolve({lat:position.coords.latitude,lng:position.coords.longitude,address:`${position.coords.latitude.toFixed(5)}, ${position.coords.longitude.toFixed(5)}`}),()=>resolve({lat:null,lng:null,address:'Location permission required'}),{enableHighAccuracy:true,timeout:12000,maximumAge:15000})});
const CATEGORY_META={roadside:{label:'Roadside rescue',icon:'SOS',tone:'orange'},maintenance:{label:'Mobile maintenance',icon:'↻',tone:'teal'},glass:{label:'Glass & body',icon:'◇',tone:'blue'},wash:{label:'Wash & detailing',icon:'✦',tone:'violet'},convenience:{label:'Convenience',icon:'+',tone:'amber'},fleet:{label:'Fleet services',icon:'▦',tone:'cyan'},seasonal:{label:'Seasonal',icon:'❄',tone:'rose'},premium:{label:'Premium concierge',icon:'♛',tone:'gold'}};
const QUICK_NAMES=['Flat Tire Help','Jump Start','Lockout','Towing','Fuel Delivery','Battery Replace'];
const STATUS_LABEL={requested:'Request received',matching:'Finding a verified Hero',assigned:'Hero assigned',en_route:'Hero en route',on_site:'Hero arrived',working:'Service in progress',completed:'Completed',canceled_by_citizen:'Canceled',canceled_by_hero:'Canceled',canceled_by_system:'Canceled',disputed:'Support review'};
const openProfileTool=tool=>window.dispatchEvent(new CustomEvent('sos:open-profile-tool',{detail:{tool}}));
const openShield=()=>window.dispatchEvent(new Event('sos:open-shield'));

function Brand(){return <div className="sos2-brand"><div className="sos2-mark"><span>SOS</span></div><div><strong>SUPERHEROES<br/>ON STANDBY</strong><small>Roadside mobility network</small></div></div>}
function Loading(){return <div className="sos2-loading"><div className="sos2-loading-mark">SOS</div><div className="sos2-loader"/><span>Connecting the response network</span></div>}
function ServiceIcon({service}){const meta=CATEGORY_META[service.category_id]||CATEGORY_META.roadside;return <span className={`sos2-service-icon ${meta.tone}`}>{meta.icon}</span>}

export default function SOSCustomerMobilityApp(){
  const[booting,setBooting]=useState(true);const[session,setSession]=useState(null);const[profile,setProfile]=useState(null);const[authMode,setAuthMode]=useState('signin');
  const[name,setName]=useState('');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[authBusy,setAuthBusy]=useState(false);const[authError,setAuthError]=useState('');
  const[services,setServices]=useState([]);const[servicesError,setServicesError]=useState('');const[tab,setTab]=useState('home');const[query,setQuery]=useState('');const[category,setCategory]=useState('all');
  const[selected,setSelected]=useState(null);const[confirming,setConfirming]=useState(false);const[requestError,setRequestError]=useState('');const[location,setLocation]=useState(null);const[locating,setLocating]=useState(false);
  const[missions,setMissions]=useState([]);const[activeMission,setActiveMission]=useState(null);const[trackerOpen,setTrackerOpen]=useState(false);const[toast,setToast]=useState('');

  const loadProfile=async nextSession=>{const users=await request(`/rest/v1/sos_users?auth_id=eq.${nextSession.user.id}&select=id,role,first_name,last_name,email,shield_plan,status&limit=1`,{token:nextSession.access_token});const user=users?.[0]||null;if(user?.role==='hero'){window.location.replace('/hero');return null}setProfile(user);return user};
  const loadServices=async token=>{try{const data=await request('/rest/v1/sos_subcategories?select=id,category_id,name,description,base_fee,min_fee,max_fee,eta_band,price_model,is_active&is_active=eq.true&order=sort_order.asc,name.asc',{token});setServices(data||[])}catch(error){setServicesError(error.message)}};
  const loadMissions=async(nextSession,user)=>{if(!user?.id)return;try{const data=await request(`/rest/v1/sos_missions?citizen_id=eq.${user.id}&select=id,status,pickup_address,pickup_lat,pickup_lng,estimated_price,final_price,pricing_status,requested_service_name,eta_minutes,hero_id,created_at,accepted_at,en_route_at,arrived_at,started_at,completed_at&order=created_at.desc&limit=20`,{token:nextSession.access_token});setMissions(data||[]);const live=(data||[]).find(mission=>!['completed','canceled_by_citizen','canceled_by_hero','canceled_by_system'].includes(mission.status));if(live)setActiveMission(live)}catch{}};

  useEffect(()=>{let active=true;(async()=>{const existing=storedSession();if(existing){try{const user=await loadProfile(existing);if(active&&user){setSession(existing);await Promise.all([loadServices(existing.access_token),loadMissions(existing,user)])}}catch{localStorage.removeItem('sos_session')}}if(active)setBooting(false)})();return()=>{active=false}},[]);
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),2200);return()=>clearTimeout(timer)},[toast]);

  const categories=useMemo(()=>{const counts=new Map();services.forEach(service=>counts.set(service.category_id,(counts.get(service.category_id)||0)+1));return[...counts.entries()]},[services]);
  const quick=useMemo(()=>QUICK_NAMES.map(name=>services.find(service=>service.name===name)).filter(Boolean),[services]);
  const filtered=useMemo(()=>services.filter(service=>(category==='all'||service.category_id===category)&&(!query||`${service.name} ${service.description||''} ${service.category_id}`.toLowerCase().includes(query.toLowerCase()))),[services,category,query]);

  const authenticate=async event=>{event.preventDefault();if(authBusy)return;setAuthBusy(true);setAuthError('');try{if(authMode==='signup'){await request('/auth/v1/signup',{method:'POST',body:{email,password,data:{full_name:name.trim(),role:'citizen',app:'sos'}}})}const next=await request('/auth/v1/token?grant_type=password',{method:'POST',body:{email,password}});localStorage.setItem('sos_session',JSON.stringify(next));const user=await loadProfile(next);if(user){setSession(next);await Promise.all([loadServices(next.access_token),loadMissions(next,user)])}}catch(error){setAuthError(error.message.includes('Invalid login')?'Wrong email or password':error.message)}finally{setAuthBusy(false)}};
  const resolveLocation=async()=>{setLocating(true);const next=await locate();setLocation(next);setLocating(false);if(next.lat==null)setRequestError('Allow precise location so S.O.S. can dispatch the nearest qualified Hero.');return next};
  const openService=async service=>{setRequestError('');setSelected(service);if(!location)await resolveLocation()};
  const sendRequest=async()=>{if(!selected||!session||confirming)return;setConfirming(true);setRequestError('');try{const current=location?.lat!=null?location:await resolveLocation();if(current.lat==null)throw new Error('Precise location is required for roadside dispatch.');const result=await requestCustomerMission({token:session.access_token,serviceId:selected.id,serviceName:selected.name,location:current});setActiveMission(result.mission);setSelected(null);setTrackerOpen(true);setToast(result.dispatch?.offer_count?`${result.dispatch.offer_count} verified Heroes notified`:'Mission active — dispatch is searching');await loadMissions(session,profile)}catch(error){setRequestError(error.message)}finally{setConfirming(false)}};
  const signOut=()=>{localStorage.removeItem('sos_session');setSession(null);setProfile(null);setMissions([]);setActiveMission(null);setTab('home')};

  if(booting)return <Loading/>;
  if(!session)return <div className="sos2-auth"><div className="sos2-auth-art"><div className="sos2-road-lines"><i/><i/><i/></div><div className="sos2-signal"><span/><b/><em/></div><Brand/><div className="sos2-auth-copy"><span>ROADSIDE HELP. REBUILT.</span><h1>Your next move<br/><em>starts with SOS.</em></h1><p>Request verified roadside help, see real matching status, and track confirmed service progress.</p></div></div><form onSubmit={authenticate} className="sos2-auth-panel"><div className="sos2-segmented"><button type="button" className={authMode==='signin'?'active':''} onClick={()=>{setAuthMode('signin');setAuthError('')}}>Sign in</button><button type="button" className={authMode==='signup'?'active':''} onClick={()=>{setAuthMode('signup');setAuthError('')}}>Create account</button></div>{authMode==='signup'&&<label>Full name<input required value={name} onChange={event=>setName(event.target.value)} placeholder="Your name"/></label>}<label>Email<input required type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="you@email.com"/></label><label>Password<input required minLength={8} type="password" value={password} onChange={event=>setPassword(event.target.value)} placeholder="8+ characters"/></label>{authError&&<div className="sos2-error">{authError}</div>}<button className="sos2-primary" disabled={authBusy}>{authBusy?'Connecting…':authMode==='signin'?'Enter SOS':'Create citizen account'}</button><p className="sos2-disclaimer">S.O.S. is roadside assistance—not 911. For a life-threatening emergency, call 911.</p></form></div>;

  return <div className="sos2-app"><header className="sos2-topbar"><Brand/><button className="sos2-avatar" onClick={()=>setTab('profile')}>{profile?.first_name?.[0]||session.user?.email?.[0]||'U'}</button></header><main className="sos2-content">
    {tab==='home'&&<><section className="sos2-map-hero"><iframe title="S.O.S. area map" src="https://www.openstreetmap.org/export/embed.html?bbox=-84.50%2C33.66%2C-84.28%2C33.86&layer=mapnik"/><div className="sos2-map-shade"/><div className="sos2-home-greeting"><span>GOOD {new Date().getHours()<12?'MORNING':new Date().getHours()<18?'AFTERNOON':'EVENING'}</span><h1>What happened?</h1><p>Choose the help you need. We’ll notify qualified Heroes near your real location.</p></div><button className="sos2-location-pill" onClick={resolveLocation}><span className={location?.lat!=null?'ready':''}/>{locating?'Finding you…':location?.lat!=null?'Current location ready':'Use current location'}</button></section>{activeMission&&<button className="sos2-active-banner" onClick={()=>setTrackerOpen(true)}><div><span>LIVE MISSION</span><strong>{activeMission.requested_service_name||'Roadside request'}</strong><small>{STATUS_LABEL[activeMission.status]||activeMission.status}</small></div><em>OPEN</em></button>}<section className="sos2-quick"><div className="sos2-section-title"><span>QUICK RESCUE</span><h2>Get help now</h2></div><div className="sos2-quick-grid">{quick.map(service=><button key={service.id} onClick={()=>openService(service)}><ServiceIcon service={service}/><strong>{service.name.replace(' Help','').replace(' Delivery','')}</strong><small>{service.eta_band||'Nearby response'}</small><em>{Number(service.base_fee||0)>0?`$${Number(service.base_fee).toFixed(0)}+`:'Quote'}</em></button>)}</div></section><section className="sos2-membership"><div><span>SHIELD MEMBERSHIP</span><h2>Roadside coverage<br/>without the runaround.</h2><p>Priority matching, member rates, and one-tap access for your household.</p></div><button onClick={openShield}>Explore Shield</button></section><section className="sos2-categories"><div className="sos2-section-title"><span>ALL SERVICES</span><h2>More ways we help</h2></div><div className="sos2-category-grid">{categories.map(([id,count])=>{const meta=CATEGORY_META[id]||CATEGORY_META.roadside;return <button key={id} onClick={()=>{setCategory(id);setTab('services')}}><span className={`sos2-category-symbol ${meta.tone}`}>{meta.icon}</span><strong>{meta.label}</strong><small>{count} services</small></button>})}</div></section></>}
    {tab==='services'&&<section className="sos2-screen"><div className="sos2-screen-head"><span>SERVICE NETWORK</span><h1>Choose your rescue.</h1><p>{filtered.length} live services available.</p></div><div className="sos2-search"><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search towing, battery, detail…"/>{query&&<button onClick={()=>setQuery('')}>×</button>}</div><div className="sos2-filter-rail"><button className={category==='all'?'active':''} onClick={()=>setCategory('all')}>All</button>{categories.map(([id])=><button key={id} className={category===id?'active':''} onClick={()=>setCategory(id)}>{CATEGORY_META[id]?.label||id}</button>)}</div><div className="sos2-service-list">{filtered.map(service=><button key={service.id} onClick={()=>openService(service)}><ServiceIcon service={service}/><div><strong>{service.name}</strong><p>{service.description||'Verified roadside and vehicle support.'}</p><small>{service.eta_band||'Response time confirmed after matching'}</small></div><em>{Number(service.base_fee||0)>0?`$${Number(service.base_fee).toFixed(0)}+`:'QUOTE'}</em></button>)}</div></section>}
    {tab==='missions'&&<section className="sos2-screen"><div className="sos2-screen-head"><span>MY MISSIONS</span><h1>Roadside history.</h1><p>Real requests, payments, and status.</p></div>{missions.length===0?<div className="sos2-empty"><span>◎</span><h2>No missions yet.</h2><p>Your active and completed roadside requests will appear here.</p><button onClick={()=>setTab('home')}>Request help</button></div>:<div className="sos2-mission-list">{missions.map(mission=><button key={mission.id} onClick={()=>{setActiveMission(mission);setTrackerOpen(true)}}><span className={`sos2-status-dot ${mission.status}`}/><div><strong>{mission.requested_service_name||'Roadside request'}</strong><p>{mission.pickup_address||'GPS location'}</p><small>{new Date(mission.created_at).toLocaleString()} · {STATUS_LABEL[mission.status]||mission.status}</small></div><em>{Number(mission.final_price||mission.estimated_price||0)>0?`$${Number(mission.final_price||mission.estimated_price).toFixed(0)}`:'VIEW'}</em></button>)}</div>}</section>}
    {tab==='profile'&&<section className="sos2-screen"><div className="sos2-profile-card"><div className="sos2-profile-avatar">{profile?.first_name?.[0]||'U'}</div><span>CITIZEN ACCOUNT</span><h1>{[profile?.first_name,profile?.last_name].filter(Boolean).join(' ')||session.user.email}</h1><p>{session.user.email}</p></div><div className="sos2-profile-menu"><button onClick={()=>openProfileTool('vehicles')}><span>♢</span><div><strong>Vehicles</strong><small>Add your vehicles for faster requests</small></div><em>›</em></button><button onClick={()=>openProfileTool('payments')}><span>▣</span><div><strong>Payment methods</strong><small>View secure payment activity and readiness</small></div><em>›</em></button><button onClick={openShield}><span>♛</span><div><strong>Shield membership</strong><small>{profile?.shield_plan||'Free'} plan</small></div><em>›</em></button><button onClick={()=>openProfileTool('support')}><span>?</span><div><strong>Safety & support</strong><small>Contact S.O.S. operations</small></div><em>›</em></button><button className="danger" onClick={signOut}><span>↪</span><div><strong>Sign out</strong><small>End this session</small></div><em>›</em></button></div></section>}
  </main><nav className="sos2-nav">{[['home','⌂','Home'],['services','◇','Services'],['missions','◎','Missions'],['profile','○','Profile']].map(([id,icon,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><span>{icon}</span><small>{label}</small></button>)}</nav>
  {selected&&<div className="sos2-sheet-backdrop" onMouseDown={()=>setSelected(null)}><section className="sos2-service-sheet" onMouseDown={event=>event.stopPropagation()}><div className="sos2-sheet-handle"/><button className="sos2-sheet-close" onClick={()=>setSelected(null)}>×</button><ServiceIcon service={selected}/><span>{CATEGORY_META[selected.category_id]?.label||'S.O.S. SERVICE'}</span><h2>{selected.name}</h2><p>{selected.description||'A verified Hero will assess the situation, confirm the service, and keep your mission status updated.'}</p><div className="sos2-service-facts"><div><small>STARTING ESTIMATE</small><strong>{Number(selected.base_fee||0)>0?`$${Number(selected.base_fee).toFixed(0)}`:'Quote required'}</strong></div><div><small>EXPECTED RESPONSE</small><strong>{selected.eta_band||'After matching'}</strong></div></div><div className={`sos2-location-check ${location?.lat!=null?'ready':''}`}><span>{location?.lat!=null?'✓':'⌖'}</span><div><strong>{location?.lat!=null?'Location ready':'Location required'}</strong><small>{location?.address||'Allow precise GPS for dispatch'}</small></div><button onClick={resolveLocation}>{locating?'…':'Update'}</button></div>{requestError&&<div className="sos2-error">{requestError}</div>}<button className="sos2-primary" disabled={confirming} onClick={sendRequest}>{confirming?'Notifying nearby Heroes…':'Request verified Hero'}</button><p className="sos2-disclaimer">Your request is not assigned until one qualified Hero accepts. ETA appears only from live mission data.</p></section></div>}
  {trackerOpen&&activeMission&&<SOSMissionTracker token={session.access_token} missionId={activeMission.id} initialMission={activeMission} onClose={()=>{setTrackerOpen(false);loadMissions(session,profile)}}/>}{servicesError&&<div className="sos2-toast error">{servicesError}</div>}{toast&&<div className="sos2-toast">{toast}</div>}</div>;
}
