'use client';

import React,{useEffect,useState}from'react';
const SB='https://cxdqkjvtpilvouwtbgdy.supabase.co';
const SK='sb_publishable_x_QDbPwZuhbqB1bd58MLvg_ADSiFODN';
const stored=()=>{try{const s=JSON.parse(localStorage.getItem('sos_session'));if(!s?.access_token||!s?.user)return null;if(s.expires_at&&s.expires_at<Date.now()/1000)return null;return s}catch{return null}};
const request=async(path,{method='GET',token,body}={})=>{const r=await fetch(`${SB}${path}`,{method,headers:{apikey:SK,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||d?.error_description||d?.error||'Request failed');return d};
const money=v=>`$${Number(v||0).toFixed(2)}`;
const status=v=>String(v||'').replaceAll('_',' ').toUpperCase();

export default function SOSCustomerReceiptHost(){
 const[missions,setMissions]=useState([]),[open,setOpen]=useState(false),[receipt,setReceipt]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{const s=stored();if(!s){setMissions([]);return}const us=await request(`/rest/v1/sos_users?auth_id=eq.${s.user.id}&select=id,role&limit=1`,{token:s.access_token});const u=us?.[0];if(!u||u.role==='hero'){setMissions([]);return}const rows=await request(`/rest/v1/sos_missions?citizen_id=eq.${u.id}&status=in.(completed,canceled_by_citizen,canceled_by_hero,canceled_by_system)&select=id,status,requested_service_name,completed_at,canceled_at,created_at&order=created_at.desc&limit=30`,{token:s.access_token});setMissions(rows||[])};
 useEffect(()=>{let disposed=false;const run=()=>{if(!disposed)load().catch(()=>{})};run();const t=setInterval(run,20000);return()=>{disposed=true;clearInterval(t)}},[]);
 const view=async id=>{const s=stored();if(!s)return;setBusy(true);setError('');try{const d=await request('/rest/v1/rpc/sos_customer_receipt',{method:'POST',token:s.access_token,body:{p_mission_id:id}});setReceipt(d)}catch(e){setError(e.message)}finally{setBusy(false)}};
 if(missions.length===0&&!open)return null;
 return <>
  {missions.length>0&&<button type="button" onClick={()=>setOpen(true)} style={{position:'fixed',left:16,top:76,zIndex:1640,border:'1px solid rgba(255,255,255,.13)',borderRadius:999,padding:'9px 12px',background:'rgba(17,27,37,.95)',color:'#fff',fontSize:9,fontWeight:900,letterSpacing:'.08em',boxShadow:'0 12px 34px rgba(0,0,0,.3)',backdropFilter:'blur(12px)'}}>RECEIPTS</button>}
  {open&&<div role="dialog" aria-modal="true" style={{position:'fixed',inset:0,zIndex:2380,background:'rgba(3,8,15,.58)',display:'grid',justifyItems:'start',backdropFilter:'blur(7px)'}}><section style={{width:'min(520px,96vw)',height:'100dvh',background:'#f7f9fc',boxShadow:'24px 0 80px rgba(0,0,0,.4)',display:'grid',gridTemplateRows:'auto 1fr'}}>
   <header style={{padding:'18px 16px 14px',background:'#101922',color:'#fff'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><small style={{fontSize:9,fontWeight:900,letterSpacing:'.13em',color:'#ff8a5b'}}>S.O.S. HISTORY</small><h2 style={{fontSize:23,margin:'4px 0 0'}}>{receipt?'Mission receipt':'Receipts & timelines'}</h2></div><div style={{display:'flex',gap:7}}>{receipt&&<button type="button" onClick={()=>setReceipt(null)} style={{border:0,borderRadius:11,padding:'8px 10px',background:'rgba(255,255,255,.08)',color:'#fff',fontSize:9,fontWeight:900}}>BACK</button>}<button type="button" onClick={()=>{setOpen(false);setReceipt(null)}} style={{width:36,height:36,border:0,borderRadius:12,background:'rgba(255,255,255,.09)',color:'#fff',fontSize:20}}>×</button></div></div></header>
   <div style={{overflowY:'auto',padding:13}}>{error&&<div style={{padding:10,borderRadius:12,background:'#fff0f0',color:'#b42318',fontSize:10,marginBottom:9}}>{error}</div>}{busy?<div style={{padding:50,textAlign:'center',color:'#7c8798',fontSize:11}}>Opening receipt…</div>:receipt?<ReceiptView receipt={receipt}/>:missions.map(m=><button key={m.id} type="button" onClick={()=>view(m.id)} style={{width:'100%',textAlign:'left',border:'1px solid #e2e8f0',borderRadius:16,padding:'13px 14px',background:'#fff',marginBottom:8,cursor:'pointer'}}><small style={{fontSize:8,fontWeight:900,letterSpacing:'.1em',color:m.status==='completed'?'#16875b':'#b45309'}}>{status(m.status)}</small><strong style={{display:'block',fontSize:14,color:'#172033',marginTop:4}}>{m.requested_service_name||'S.O.S. mission'}</strong><span style={{display:'block',fontSize:9,color:'#8a95a7',marginTop:5}}>{new Date(m.completed_at||m.canceled_at||m.created_at).toLocaleString([],{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})}</span></button>)}</div>
  </section></div>}
 </>;
}
function ReceiptView({receipt}){const p=receipt.payment||{},m=receipt.mission||{};const rows=[['Mission total',money(p.amount||m.final_price)],['Refunded',money(p.refund_amount)],['Cancellation / no-show fee',money(p.cancellation_fee)],['Platform fee',money(p.platform_fee)],['Hero payout',money(p.hero_payout)]];return <div><section style={{padding:16,borderRadius:18,background:'#fff',border:'1px solid #e2e8f0'}}><small style={{fontSize:8,fontWeight:900,letterSpacing:'.1em',color:'#e85826'}}>{status(m.status)}</small><h3 style={{fontSize:20,margin:'5px 0 3px',color:'#172033'}}>{m.service_name||'S.O.S. mission'}</h3><p style={{fontSize:10.5,color:'#718096',lineHeight:1.5,margin:0}}>{m.pickup_address||'Mission location'}{receipt.hero?.name?` · ${receipt.hero.name}`:''}</p><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:7,marginTop:14}}>{rows.map(([k,v])=><div key={k} style={{padding:10,borderRadius:12,background:'#f5f8fc'}}><small style={{fontSize:7.5,color:'#8995a7'}}>{k.toUpperCase()}</small><strong style={{display:'block',fontSize:14,color:'#243247',marginTop:2}}>{v}</strong></div>)}</div><div style={{marginTop:11,fontSize:9,color:'#8290a4'}}>Settlement: {status(p.settlement_type||'service')} · Payment: {status(p.status||'not created')}</div></section><h4 style={{fontSize:10,letterSpacing:'.11em',color:'#67758a',margin:'17px 4px 9px'}}>MISSION TIMELINE</h4><div>{(receipt.timeline||[]).length===0?<div style={{fontSize:10,color:'#94a0b1',padding:12}}>No recorded events.</div>:(receipt.timeline||[]).map((e,i)=><div key={`${e.created_at}-${i}`} style={{display:'grid',gridTemplateColumns:'10px 1fr',gap:9,padding:'8px 4px'}}><i style={{width:8,height:8,borderRadius:'50%',background:'#ff6b35',marginTop:3}}/><div><strong style={{fontSize:10,color:'#26344a'}}>{status(e.new_status||e.type||'update')}</strong>{e.old_status&&<span style={{display:'block',fontSize:9.5,color:'#758197',marginTop:2}}>{status(e.old_status)} → {status(e.new_status)}</span>}<small style={{fontSize:8,color:'#a0a8b6'}}>{e.created_at?new Date(e.created_at).toLocaleString():''}</small></div></div>)}</div></div>}
