'use client';

import {useEffect,useMemo,useState} from 'react';
import styles from './SOSHeroVerificationOpsHost.module.css';

const SB='https://cxdqkjvtpilvouwtbgdy.supabase.co';
const SK='sb_publishable_x_QDbPwZuhbqB1bd58MLvg_ADSiFODN';
const headers=token=>({apikey:SK,Authorization:`Bearer ${token}`,'Content-Type':'application/json'});
const label=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());

export default function SOSHeroVerificationOpsHost({session}){
 const[rows,setRows]=useState([]),[notes,setNotes]=useState({}),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=async()=>{if(!session?.access_token)return;const r=await fetch(`${SB}/rest/v1/rpc/sos_ops_verification_queue`,{method:'POST',headers:headers(session.access_token),body:'{}'});const d=await r.json().catch(()=>[]);if(!r.ok)throw new Error(d?.message||d?.error||'Verification queue unavailable');setRows(Array.isArray(d)?d:[])};
 useEffect(()=>{load().catch(e=>setError(e.message));const t=setInterval(()=>load().catch(()=>{}),15000);return()=>clearInterval(t)},[session?.access_token]);
 const groups=useMemo(()=>{const map=new Map();for(const row of rows){const list=map.get(row.hero_id)||[];list.push(row);map.set(row.hero_id,list)}return[...map.entries()]},[rows]);
 const pending=rows.filter(r=>r.required&&r.status!=='passed').length;
 const review=async(row,status)=>{if(row.check_type==='payout_account')return;const key=`${row.hero_id}:${row.check_type}`;setBusy(key);setError('');setNotice('');try{const r=await fetch(`${SB}/rest/v1/rpc/sos_ops_review_verification_check`,{method:'POST',headers:headers(session.access_token),body:JSON.stringify({p_hero_id:row.hero_id,p_check_type:row.check_type,p_status:status,p_notes:notes[key]||null})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||d?.error||'Verification update failed');setNotice(`${label(row.check_type)} → ${label(status)}`);await load()}catch(e){setError(e.message)}finally{setBusy('')}};
 return <section className={styles.wrap}><div className={styles.heading}><div><span>VERIFICATION QUEUE</span><h2>Checks before patrol.</h2><p>Approved applicants stay off dispatch until all nine required checks pass. Payout readiness is synchronized directly from Stripe.</p></div><b>{pending}</b></div>{error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}{groups.length===0?<div className={styles.empty}>No approved real Heroes are waiting on verification.</div>:groups.map(([heroId,checks])=>{const first=checks[0];const passed=checks.filter(c=>c.required&&c.status==='passed').length;const required=checks.filter(c=>c.required).length;return <article className={styles.hero} key={heroId}><div className={styles.heroHead}><div><small>{first.auth_linked?'ACCOUNT CLAIMED':'AWAITING ACCOUNT CLAIM'}</small><strong>{first.first_name} {first.last_name}</strong><span>{first.email}</span></div><div><b>{passed}/{required}</b><span>{label(first.verification_status)}</span></div></div><div className={styles.checks}>{checks.map(row=>{const key=`${row.hero_id}:${row.check_type}`;const stripe=row.check_type==='payout_account';const done=row.status==='passed';return <div className={`${styles.check} ${done?styles.done:''}`} key={key}><div className={styles.checkName}><i>{done?'✓':stripe?'$':'!'}</i><span><strong>{label(row.check_type)}</strong><small>{stripe?'STRIPE-MANAGED':row.required?'REQUIRED':'OPTIONAL'} · {label(row.status)}</small></span></div>{stripe?<p className={styles.stripeNote}>Changes only when Stripe transfers become active.</p>:<><input value={notes[key]||''} onChange={e=>setNotes(v=>({...v,[key]:e.target.value}))} placeholder="Evidence or review note"/><div className={styles.actions}><button disabled={busy===key} onClick={()=>review(row,'under_review')}>Review</button><button className={styles.pass} disabled={busy===key||done} onClick={()=>review(row,'passed')}>Pass</button><button className={styles.fail} disabled={busy===key||row.status==='failed'} onClick={()=>review(row,'failed')}>Fail</button></div></>}</div>})}</div></article>})}<p className={styles.truth}>Required Hero verification cannot be waived. “Verified” now means the same thing as “allowed to start patrol.”</p></section>;
}
