'use client';

import {useEffect,useState} from 'react';
import styles from './SOSHeroVerificationReadinessHost.module.css';

const SB='https://cxdqkjvtpilvouwtbgdy.supabase.co';
const SK='sb_publishable_x_QDbPwZuhbqB1bd58MLvg_ADSiFODN';
const headers=token=>({apikey:SK,Authorization:`Bearer ${token}`,'Content-Type':'application/json'});
const session=()=>{try{const s=JSON.parse(localStorage.getItem('sos_session'));return s?.access_token?s:null}catch{return null}};
const label=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const allowedTypes=new Set(['application/pdf','image/jpeg','image/png','image/webp','image/heic','image/heif']);
const extension=file=>{const fromName=file.name?.split('.').pop()?.toLowerCase().replace(/[^a-z0-9]/g,'');if(fromName)return fromName;return file.type==='application/pdf'?'pdf':file.type.includes('png')?'png':file.type.includes('webp')?'webp':file.type.includes('heic')?'heic':file.type.includes('heif')?'heif':'jpg'};

export default function SOSHeroVerificationReadinessHost(){
 const[state,setState]=useState(null),[open,setOpen]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[uploading,setUploading]=useState('');
 const load=async()=>{const s=session();if(!s)return;const r=await fetch(`${SB}/rest/v1/rpc/sos_hero_verification_status`,{method:'POST',headers:headers(s.access_token),body:'{}'});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||d?.error||'Hero verification status unavailable');setState(d)};
 useEffect(()=>{const refresh=()=>load().catch(()=>{});refresh();const t=setInterval(refresh,12000);return()=>clearInterval(t)},[]);
 const ready=Boolean(state?.dispatch_ready);
 useEffect(()=>{if(state?.state!=='hero')return;document.documentElement.dataset.sosHeroVerificationUi='1';document.documentElement.dataset.sosHeroDispatchReady=ready?'true':'false';if(!ready)setOpen(true);return()=>{delete document.documentElement.dataset.sosHeroVerificationUi;delete document.documentElement.dataset.sosHeroDispatchReady}},[state?.state,ready]);
 if(state?.state!=='hero'||ready)return null;
 const checks=state.checks||[];const payout=checks.find(c=>c.check_type==='payout_account');
 const onboard=async()=>{const s=session();if(!s)return;setBusy(true);setError('');try{const r=await fetch(`${SB}/functions/v1/hero-payouts`,{method:'POST',headers:headers(s.access_token),body:JSON.stringify({action:'onboard'})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||'Payout setup unavailable');if(d.onboarding_url)window.location.assign(d.onboarding_url);else await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const upload=async(check,file)=>{if(!file||check.check_type==='payout_account')return;const s=session();if(!s||!state?.hero_id)return;setError('');if(file.size>10*1024*1024){setError('Verification files must be 10 MB or smaller.');return}if(!allowedTypes.has(file.type)){setError('Use PDF, JPEG, PNG, WebP, HEIC, or HEIF files.');return}setUploading(check.check_type);try{let userId=s.user?.id;if(!userId){const ur=await fetch(`${SB}/auth/v1/user`,{headers:{apikey:SK,Authorization:`Bearer ${s.access_token}`}});const ud=await ur.json().catch(()=>({}));if(!ur.ok||!ud.id)throw new Error('Sign in again before uploading verification files.');userId=ud.id}const path=`sos/${userId}/${state.hero_id}/${check.check_type}/${crypto.randomUUID()}.${extension(file)}`;const r=await fetch(`${SB}/storage/v1/object/marketplace-verification/${path}`,{method:'POST',headers:{apikey:SK,Authorization:`Bearer ${s.access_token}`,'Content-Type':file.type,'x-upsert':'false'},body:file});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||d?.error||'Verification file upload failed');const rr=await fetch(`${SB}/rest/v1/rpc/sos_hero_submit_verification_evidence`,{method:'POST',headers:headers(s.access_token),body:JSON.stringify({p_check_type:check.check_type,p_path:path})});const rd=await rr.json().catch(()=>({}));if(!rr.ok)throw new Error(rd?.message||rd?.error||'Verification submission failed');await load()}catch(e){setError(e.message||'Verification evidence could not be uploaded.')}finally{setUploading('')}};
 return <><button className={styles.launch} onClick={()=>setOpen(true)}><span>HERO SETUP REQUIRED</span><b>{state.passed_checks||0}/{state.required_checks||9}</b><small>{label(state.verification_status||'pending')}</small></button>{open&&<div className={styles.backdrop} onMouseDown={()=>setOpen(false)}><section className={styles.sheet} onMouseDown={e=>e.stopPropagation()}><header><div><span>HERO LAUNCH READINESS</span><h2>Complete 9/9 before patrol.</h2><p>These are the exact checks enforced by S.O.S. when you try to go on patrol. There is no separate “verified” shortcut.</p></div><button onClick={()=>setOpen(false)}>×</button></header>{error&&<div className={styles.error}>{error}</div>}<div className={styles.progress}><strong>{state.passed_checks||0}</strong><span>of {state.required_checks||9} required checks passed</span></div><div className={styles.checks}>{checks.map(check=>{const done=check.status==='passed';const stripe=check.check_type==='payout_account';const submitted=(check.evidence_urls||[]).length;return <div className={done?styles.done:''} key={check.check_type}><i>{done?'✓':stripe?'$':submitted?'↑':'!'}</i><span><strong>{label(check.check_type)}</strong><small>{stripe?'STRIPE-MANAGED':check.required?'REQUIRED':'OPTIONAL'} · {label(check.status)}</small>{submitted>0&&<em>{submitted} private file{submitted===1?'':'s'} submitted</em>}{check.notes&&<em>{check.notes}</em>}</span>{!stripe&&!done&&<label className={styles.upload}><input type="file" accept="application/pdf,image/jpeg,image/png,image/webp,image/heic,image/heif" disabled={uploading===check.check_type} onChange={e=>{const file=e.target.files?.[0];void upload(check,file);e.currentTarget.value=''}}/><b>{uploading===check.check_type?'Uploading…':submitted?'Add evidence':'Upload evidence'}</b></label>}</div>})}</div>{payout?.status!=='passed'&&<button className={styles.primary} disabled={busy} onClick={onboard}>{busy?'Opening Stripe…':'Finish payout setup →'}</button>}<p className={styles.truth}>Verification documents are private. Uploading evidence moves a check to submitted; only operations or Stripe can pass it.</p></section></div>}</>;
}
