'use client';

import React,{useCallback,useEffect,useMemo,useRef,useState}from'react';
import './sos-hero-command.css';

const SB='https://cxdqkjvtpilvouwtbgdy.supabase.co';
const SK='sb_publishable_x_QDbPwZuhbqB1bd58MLvg_ADSiFODN';
const headers=token=>({apikey:SK,Authorization:`Bearer ${token||SK}`,'Content-Type':'application/json'});
const storedSession=()=>{try{const v=JSON.parse(localStorage.getItem('sos_session'));if(!v?.access_token||!v?.user)return null;if(v.expires_at&&v.expires_at<Date.now()/1000)return null;return v}catch{return null}};
const request=async(path,{method='GET',token,body}={})=>{const r=await fetch(`${SB}${path}`,{method,headers:headers(token),body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||d?.error_description||d?.error||'Request failed');return d};
const rpc=(token,name,body={})=>request(`/rest/v1/rpc/${name}`,{method:'POST',token,body});
const edge=(token,name,body={})=>request(`/functions/v1/${name}`,{method:'POST',token,body});
const locate=()=>new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('GPS is not available on this device.'));navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,heading:p.coords.heading,speed:p.coords.speed}),()=>reject(new Error('Precise location permission is required for Hero operations.')),{enableHighAccuracy:true,timeout:12000,maximumAge:10000})});
const activeMission=m=>!['completed','canceled_by_citizen','canceled_by_hero','canceled_by_system'].includes(m.status);
const money=v=>`$${Number(v||0).toFixed(2)}`;
const when=v=>v?new Date(v).toLocaleString([],{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Now';
const statusLabel=s=>({requested:'Requested',matching:'Matching',assigned:'Accepted',en_route:'En route',on_site:'On site',working:'In service',completed:'Completed',authorized:'Authorized',captured:'Captured',released:'Paid'}[s]||String(s||'Unknown').replaceAll('_',' '));
const paymentReady=s=>['authorized','captured','released'].includes(s||'');
const nextStatus={assigned:['en_route','Start route'],en_route:['on_site','I arrived'],on_site:['working','Start service']};

function Brand(){return <div className="shc-brand"><div className="shc-mark">SOS</div><div><strong>HERO COMMAND</strong><span>SUPERHEROES ON STANDBY</span></div></div>}
function Button({children,onClick,disabled=false,tone='orange',className=''}){return <button type="button" className={`shc-button ${tone} ${className}`} disabled={disabled} onClick={onClick}>{children}</button>}

function Login({onLogin,error,setError}){
  const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);
  const submit=async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{const next=await request('/auth/v1/token?grant_type=password',{method:'POST',body:{email,password}});localStorage.setItem('sos_session',JSON.stringify(next));await onLogin(next)}catch(e){setError(e.message.includes('Invalid login')?'Wrong email or password':e.message)}finally{setBusy(false)}};
  return <main className="shc-auth"><section className="shc-auth-art"><a href="/" className="shc-back">← S.O.S. customer app</a><Brand/><div className="shc-auth-copy"><span>FIELD OPERATIONS</span><h1>Go on patrol.<br/>Own the mission.</h1><p>Hero Command is the live workspace for verified S.O.S. providers: offers, customer authorization, navigation, proof, completion, and payouts.</p></div><div className="shc-auth-steps"><div><b>01</b><span>Verified Hero access</span></div><div><b>02</b><span>Stripe payout ready</span></div><div><b>03</b><span>Patrol + accept missions</span></div></div></section><form className="shc-auth-card" onSubmit={submit}><div className="shc-auth-badge">VERIFIED HERO PORTAL</div><h2>Enter Hero Command</h2><p>Use the credentials attached to your approved Hero profile.</p><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="hero@email.com"/></label><label>Password<input required type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Your password"/></label>{error&&<div className="shc-message error">{error}</div>}<button className="shc-primary" disabled={busy}>{busy?'Connecting…':'Enter Hero Command'}</button><small>Hero access is activated only after provider verification.</small></form></main>
}

function Readiness({hero,payout,onboard}){
  const checks=[['Hero verification',hero?.verification_status==='verified'],['Background',Boolean(hero?.background_cleared)],['Identity',Boolean(hero?.id_verified)],['License',Boolean(hero?.license_verified)],['Insurance',Boolean(hero?.insurance_verified)],['Test mission',Boolean(hero?.test_mission_passed)],['Payout account',Boolean(payout?.payout_ready)]];
  return <section className="shc-readiness"><div className="shc-section-head"><div><span>LAUNCH READINESS</span><h2>Ready for patrol?</h2></div><b>{checks.filter(x=>x[1]).length}/{checks.length}</b></div><div className="shc-check-grid">{checks.map(([label,ok])=><div key={label} className={ok?'done':''}><i>{ok?'✓':'!'}</i><span>{label}</span></div>)}</div>{!payout?.payout_ready&&<Button onClick={onboard} className="full">Finish payout setup →</Button>}</section>
}

function OfferCard({offer,clock,busy,onAnswer}){
  const expires=offer.expires_at?Math.max(0,Math.floor((new Date(offer.expires_at).getTime()-clock)/1000)):null;
  return <article className="shc-offer"><div className="shc-offer-head"><div><span>MISSION OFFER</span><h3>{offer.mission?.requested_service_name||'Roadside mission'}</h3><p>{offer.mission?.pickup_address||'Customer pickup location'}</p></div><div className="shc-offer-pay"><strong>{money(offer.payout_amount)}</strong><small>HERO PAYOUT</small></div></div><div className="shc-offer-facts"><div><span>ETA</span><strong>{offer.eta_minutes?`${offer.eta_minutes} min`:'Calculated after GPS'}</strong></div><div><span>EXPIRES</span><strong>{expires===null?'Offer window':expires>0?`${expires}s`:'Expired'}</strong></div></div><div className="shc-offer-actions"><Button tone="dark" disabled={busy||expires===0} onClick={()=>onAnswer(false)}>Decline</Button><Button disabled={busy||expires===0} onClick={()=>onAnswer(true)}>{busy?'Responding…':'Accept mission'}</Button></div></article>
}

function MissionCommand({mission,payment,customer,busy,onAdvance,onPrice,onComplete,onClose}){
  const routeReady=paymentReady(payment?.payment_status)&&mission.pricing_status==='confirmed'&&Number(mission.final_price||0)>0;
  const next=nextStatus[mission.status];
  const destination=mission.pickup_lat!=null&&mission.pickup_lng!=null?`${mission.pickup_lat},${mission.pickup_lng}`:encodeURIComponent(mission.pickup_address||'');
  return <div className="shc-overlay"><section className="shc-command"><header><div><span>ACTIVE MISSION</span><h2>{mission.requested_service_name||'Roadside mission'}</h2><p>{statusLabel(mission.status)} · {money(mission.final_price||mission.estimated_price)}</p></div><button onClick={onClose}>×</button></header><div className="shc-command-map"><div className="shc-map-grid"/><div className="shc-radar"><i/><b>SOS</b></div><div className="shc-destination"><span>PICKUP</span><strong>{mission.pickup_address||'Customer location'}</strong></div></div><div className="shc-command-grid"><div><span>CUSTOMER</span><strong>{customer?.display_name||'Assigned customer'}</strong>{customer?.phone&&<a href={`tel:${customer.phone}`}>{customer.phone}</a>}</div><div><span>PAYMENT</span><strong>{statusLabel(payment?.payment_status||'pending')}</strong><small>{payment?.hero_payout?`${money(payment.hero_payout)} Hero payout`:'Waiting for authorization'}</small></div></div><div className="shc-command-actions"><a href={`https://www.google.com/maps/dir/?api=1&destination=${destination}`} target="_blank" rel="noreferrer">Open directions</a>{customer?.phone&&<a href={`sms:${customer.phone}`}>Message customer</a>}</div>{mission.pricing_status!=='confirmed'&&['assigned'].includes(mission.status)&&<div className="shc-price-gate"><div><span>FINAL PRICE</span><strong>Confirm before travel</strong><small>Customer authorization cannot protect the mission until pricing is confirmed.</small></div><Button onClick={onPrice}>Confirm price</Button></div>}{mission.status==='assigned'&&!routeReady&&<div className="shc-payment-gate"><b>DO NOT TRAVEL YET</b><span>{mission.pricing_status!=='confirmed'?'Confirm the final price first.':'Waiting for customer payment authorization.'}</span></div>}{next&&<div className="shc-next"><div><span>NEXT STEP</span><strong>{next[1]}</strong><small>{mission.status==='assigned'?'Unlocks only after confirmed price + customer authorization.':'GPS is recorded with each field transition.'}</small></div><Button disabled={busy||(mission.status==='assigned'&&!routeReady)} onClick={()=>onAdvance(next[0])}>{busy?'Updating…':next[1]}</Button></div>}{mission.status==='working'&&<div className="shc-next complete"><div><span>PROOF + COMPLETION</span><strong>Finish the mission</strong><small>Completion records proof, captures the authorized payment, and releases the Hero payout when the payout account is ready.</small></div><Button tone="green" disabled={busy} onClick={onComplete}>{busy?'Completing…':'Complete mission'}</Button></div>}{mission.status==='completed'&&<div className="shc-done"><b>✓ Mission completed</b><span>{payment?.payment_status==='released'?'Hero payout released.':'Payment processing status: '+statusLabel(payment?.payment_status)}</span></div>}</section></div>
}

function ProofModal({mission,busy,onCancel,onSubmit}){
  const[notes,setNotes]=useState('');
  return <div className="shc-overlay proof"><section className="shc-proof"><span>PROOF OF SERVICE</span><h2>What did you complete?</h2><p>This note becomes part of the authenticated mission completion record. GPS is captured automatically.</p><textarea autoFocus value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Example: Jump-started vehicle, verified engine restart, customer confirmed vehicle was running."/><div><Button tone="dark" onClick={onCancel}>Cancel</Button><Button tone="green" disabled={busy||notes.trim().length<3} onClick={()=>onSubmit(notes.trim())}>{busy?'Completing…':'Submit proof + complete'}</Button></div><small>{mission?.requested_service_name}</small></section></div>
}

export default function SOSHeroMobilityApp(){
  const[booting,setBooting]=useState(true);const[session,setSession]=useState(null);const[user,setUser]=useState(null);const[hero,setHero]=useState(null);
  const[offers,setOffers]=useState([]);const[missions,setMissions]=useState([]);const[payments,setPayments]=useState([]);const[payout,setPayout]=useState({connected:false,payout_ready:false,requirements_due:[]});
  const[tab,setTab]=useState('home');const[selectedMission,setSelectedMission]=useState(null);const[customer,setCustomer]=useState(null);const[proofMission,setProofMission]=useState(null);
  const[busy,setBusy]=useState('');const[error,setError]=useState('');const[notice,setNotice]=useState('');const[clock,setClock]=useState(Date.now());const heartbeat=useRef(null);

  const load=useCallback(async(nextSession,{quiet=false}={})=>{if(!nextSession?.access_token)return;try{const users=await request(`/rest/v1/sos_users?auth_id=eq.${nextSession.user.id}&select=id,role,first_name,last_name,email,status&limit=1`,{token:nextSession.access_token});const u=users?.[0];if(!u)throw new Error('S.O.S. profile not found.');if(u.role!=='hero'){window.location.replace('/app');return}const heroes=await request(`/rest/v1/sos_heroes?user_id=eq.${u.id}&select=id,level,rating,total_missions,on_duty,verification_status,stripe_connect_id,license_verified,insurance_verified,background_cleared,id_verified,test_mission_passed,last_lat,last_lng,last_gps_at,services_enabled&limit=1`,{token:nextSession.access_token});const h=heroes?.[0];if(!h)throw new Error('Hero profile not found.');const[o,m,p,payoutStatus]=await Promise.all([request(`/rest/v1/sos_mission_offers?hero_id=eq.${h.id}&status=eq.pending&select=id,mission_id,eta_minutes,payout_amount,expires_at,offered_at,mission:sos_missions!sos_mission_offers_mission_id_fkey(id,status,requested_service_name,pickup_address,estimated_price,final_price,pricing_status)&order=offered_at.desc`,{token:nextSession.access_token}),request(`/rest/v1/sos_missions?hero_id=eq.${h.id}&select=id,status,requested_service_name,pickup_address,pickup_lat,pickup_lng,estimated_price,final_price,pricing_status,eta_minutes,created_at,accepted_at,en_route_at,arrived_at,started_at,completed_at&order=created_at.desc&limit=50`,{token:nextSession.access_token}),request(`/rest/v1/sos_payments?hero_id=eq.${h.id}&select=id,mission_id,payment_status,escrow_status,amount,hero_payout,released_at,captured_at,created_at&order=created_at.desc`,{token:nextSession.access_token}),edge(nextSession.access_token,'hero-payouts',{action:'status'}).catch(()=>({connected:Boolean(h.stripe_connect_id),payout_ready:false,requirements_due:[]}))]);setUser(u);setHero(h);setOffers(o||[]);setMissions(m||[]);setPayments(p||[]);setPayout(payoutStatus||{});if(!quiet)setError('')}catch(e){if(!quiet)setError(e.message||'Hero network unavailable')}},[]);

  useEffect(()=>{let active=true;(async()=>{const existing=storedSession();if(existing){setSession(existing);await load(existing)}if(active)setBooting(false)})();return()=>{active=false;if(heartbeat.current)clearInterval(heartbeat.current)}},[load]);
  useEffect(()=>{const t=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(t)},[]);
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),2600);return()=>clearTimeout(t)},[notice]);
  useEffect(()=>{if(!session||!hero?.on_duty){if(heartbeat.current)clearInterval(heartbeat.current);heartbeat.current=null;return}const beat=async()=>{try{const pos=await locate();await rpc(session.access_token,'sos_set_hero_presence',{p_on_duty:true,p_lat:pos.lat,p_lng:pos.lng,p_zone_id:null,p_device_session_id:`web-${session.user.id}`});await load(session,{quiet:true})}catch{}};heartbeat.current=setInterval(beat,15000);return()=>{if(heartbeat.current)clearInterval(heartbeat.current)}},[session,hero?.on_duty,load]);
  useEffect(()=>{if(!session)return;const t=setInterval(()=>load(session,{quiet:true}),12000);return()=>clearInterval(t)},[session,load]);

  const login=async next=>{setSession(next);await load(next)};
  const logout=async()=>{if(heartbeat.current)clearInterval(heartbeat.current);if(session&&hero?.on_duty){await rpc(session.access_token,'sos_set_hero_presence',{p_on_duty:false,p_lat:null,p_lng:null,p_zone_id:null,p_device_session_id:`web-${session.user.id}`}).catch(()=>{})}localStorage.removeItem('sos_session');setSession(null);setUser(null);setHero(null);setOffers([]);setMissions([]);setPayments([]);setSelectedMission(null)};
  const onboard=async()=>{setBusy('payout');setError('');try{const d=await edge(session.access_token,'hero-payouts',{action:'onboard'});setPayout(d);if(d.onboarding_url)window.location.assign(d.onboarding_url);else if(d.payout_ready)setNotice('Payout account is active. You can go on patrol.')}catch(e){setError(e.message)}finally{setBusy('')}};
  const togglePatrol=async()=>{setBusy('patrol');setError('');try{if(!hero.on_duty&&!payout.payout_ready)throw new Error('Finish payout setup before going on patrol.');let pos={lat:null,lng:null};if(!hero.on_duty)pos=await locate();await rpc(session.access_token,'sos_set_hero_presence',{p_on_duty:!hero.on_duty,p_lat:pos.lat,p_lng:pos.lng,p_zone_id:null,p_device_session_id:`web-${session.user.id}`});await load(session);setNotice(hero.on_duty?'You are off patrol.':'You are live and eligible for mission offers.')}catch(e){setError(e.message)}finally{setBusy('')}};
  const answer=async(offer,accept)=>{setBusy(`offer-${offer.id}`);setError('');try{if(accept&&!payout.payout_ready)throw new Error('Payout setup must be active before accepting paid missions.');const mission=await rpc(session.access_token,accept?'sos_accept_mission_offer':'sos_decline_mission_offer',accept?{p_offer_id:offer.id}:{p_offer_id:offer.id,p_reason:'Hero declined from Hero Command'});await load(session);setNotice(accept?'Mission accepted. Confirm pricing and customer authorization before travel.':'Offer declined.');if(accept){setTab('missions');await openMission(mission.id||offer.mission_id)}}catch(e){setError(e.message)}finally{setBusy('')}};
  const confirmPrice=async mission=>{const suggested=Number(mission.final_price||mission.estimated_price||0);const raw=window.prompt('Confirm the final customer price before travel.',suggested>0?suggested.toFixed(2):'');if(raw===null)return;const price=Number(raw);if(!Number.isFinite(price)||price<=0){setError('Enter a valid final price.');return}setBusy(`price-${mission.id}`);setError('');try{await edge(session.access_token,'hero-confirm-price',{mission_id:mission.id,final_price:price});await load(session);const updated=missions.find(m=>m.id===mission.id)||mission;setSelectedMission({...updated,final_price:price,pricing_status:'confirmed'});setNotice('Price confirmed. Waiting for customer authorization.')}catch(e){setError(e.message)}finally{setBusy('')}};
  const advance=async(mission,status)=>{setBusy(`mission-${mission.id}`);setError('');try{const pos=await locate();const updated=await rpc(session.access_token,'sos_transition_assigned_mission',{p_mission_id:mission.id,p_new_status:status,p_lat:pos.lat,p_lng:pos.lng,p_note:null});setSelectedMission(updated);await load(session);setNotice(status==='en_route'?'Route started.':status==='on_site'?'Arrival recorded.':'Service started.')}catch(e){setError(e.message)}finally{setBusy('')}};
  const complete=async(mission,notes)=>{setBusy(`complete-${mission.id}`);setError('');try{const pos=await locate();const d=await edge(session.access_token,'hero-complete-mission',{mission_id:mission.id,notes,lat:pos.lat,lng:pos.lng,media_urls:[]});setProofMission(null);await load(session);const refreshed={...mission,status:'completed',completed_at:new Date().toISOString()};setSelectedMission(refreshed);setNotice(d?.payment?.released?'Mission complete. Hero payout released.':'Mission complete. Payment captured; payout requires operations review.')}catch(e){setError(e.message)}finally{setBusy('')}};
  const openMission=async id=>{let found=missions.find(x=>x.id===id)||((selectedMission&&selectedMission.id===id)?selectedMission:null);if(!found){try{const rows=await request(`/rest/v1/sos_missions?id=eq.${id}&select=id,status,requested_service_name,pickup_address,pickup_lat,pickup_lng,estimated_price,final_price,pricing_status,eta_minutes,created_at,accepted_at,en_route_at,arrived_at,started_at,completed_at&limit=1`,{token:session.access_token});found=Array.isArray(rows)?rows[0]||null:null}catch{found=null}}if(!found){setError('Mission could not be loaded. Refresh Hero Command and try again.');return}setSelectedMission(found);setCustomer(null);try{const rows=await rpc(session.access_token,'sos_get_assigned_customer_summary',{p_mission_id:id});setCustomer(Array.isArray(rows)?rows[0]||null:rows||null)}catch{setCustomer(null)}};

  const payByMission=useMemo(()=>Object.fromEntries(payments.map(p=>[p.mission_id,p])),[payments]);
  const liveMissions=useMemo(()=>missions.filter(activeMission),[missions]);
  const completed=useMemo(()=>missions.filter(m=>m.status==='completed'),[missions]);
  const released=useMemo(()=>payments.filter(p=>p.payment_status==='released').reduce((n,p)=>n+Number(p.hero_payout||0),0),[payments]);
  const today=useMemo(()=>payments.filter(p=>p.payment_status==='released'&&new Date(p.released_at||p.created_at).toDateString()===new Date().toDateString()).reduce((n,p)=>n+Number(p.hero_payout||0),0),[payments]);
  const week=useMemo(()=>{const d=new Date();const start=new Date(d);start.setDate(d.getDate()-d.getDay());start.setHours(0,0,0,0);return payments.filter(p=>p.payment_status==='released'&&new Date(p.released_at||p.created_at)>=start).reduce((n,p)=>n+Number(p.hero_payout||0),0)},[payments]);
  const pending=useMemo(()=>payments.filter(p=>['authorized','captured'].includes(p.payment_status)).reduce((n,p)=>n+Number(p.hero_payout||0),0),[payments]);
  const verified=hero&&hero.verification_status==='verified'&&hero.license_verified&&hero.insurance_verified&&hero.background_cleared&&hero.id_verified&&hero.test_mission_passed;

  if(booting)return <main className="shc-loading"><div className="shc-loading-mark">SOS</div><div className="shc-loading-line"/><span>Connecting Hero Command</span></main>;
  if(!session)return <Login onLogin={login} error={error} setError={setError}/>;
  if(!hero)return <main className="shc-gate"><div><Brand/><span>HERO ACCESS</span><h1>Hero profile not active.</h1><p>{error||'This login does not have an activated Hero profile yet.'}</p><Button tone="dark" onClick={logout}>Sign out</Button></div></main>;

  return <div className="shc-app"><header className="shc-top"><Brand/><div className="shc-top-right"><div className={`shc-patrol-pill ${hero.on_duty?'live':''}`}><i/>{hero.on_duty?'ON PATROL':'OFF PATROL'}</div><button onClick={()=>setTab('account')}>{user?.first_name?.[0]||'H'}</button></div></header><aside className="shc-side"><Brand/>{[['home','⌂','Home'],['offers','◎','Offers'],['missions','▤','Missions'],['earnings','$','Earnings'],['account','◉','Account']].map(([id,icon,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><b>{icon}</b><span>{label}</span>{id==='offers'&&offers.length>0&&<em>{offers.length}</em>}</button>)}</aside><main className="shc-content">{error&&<div className="shc-global-error">{error}<button onClick={()=>setError('')}>×</button></div>}{notice&&<div className="shc-toast">{notice}</div>}
    {tab==='home'&&<><section className="shc-hero"><div className="shc-hero-grid"/><div className="shc-hero-copy"><span>{hero.on_duty?'LIVE PATROL':'HERO COMMAND'}</span><h1>{hero.on_duty?'You’re live. Stay ready.':`Ready when you are${user?.first_name?`, ${user.first_name}`:''}.`}</h1><p>{hero.on_duty?`${offers.length} live mission offers · ${liveMissions.length} active missions`:'Complete readiness, turn on patrol, and Hero Command will surface verified roadside missions.'}</p></div><button className={`shc-patrol ${hero.on_duty?'live':''}`} onClick={togglePatrol} disabled={busy==='patrol'||(!hero.on_duty&&(!verified||!payout.payout_ready))}><i/><span>{busy==='patrol'?'UPDATING':hero.on_duty?'END PATROL':verified&&payout.payout_ready?'START PATROL':'SETUP REQUIRED'}</span></button></section><section className="shc-metrics"><div><span>TODAY</span><strong>{money(today)}</strong><small>released earnings</small></div><div><span>THIS WEEK</span><strong>{money(week)}</strong><small>released earnings</small></div><div><span>RATING</span><strong>{Number(hero.rating||5).toFixed(1)}</strong><small>{hero.total_missions||0} missions</small></div></section>{liveMissions.length>0&&<section className="shc-live"><div className="shc-section-head"><div><span>ACTIVE NOW</span><h2>Mission in motion.</h2></div><b>{liveMissions.length}</b></div>{liveMissions.map(m=><button key={m.id} onClick={()=>openMission(m.id)}><i className={`status ${m.status}`}/><div><strong>{m.requested_service_name}</strong><span>{statusLabel(m.status)} · {m.pickup_address}</span></div><em>OPEN</em></button>)}</section>}{(!verified||!payout.payout_ready)&&<Readiness hero={hero} payout={payout} onboard={onboard}/>}<section className="shc-home-grid"><button onClick={()=>setTab('offers')}><span>MISSION OFFERS</span><strong>{offers.length}</strong><small>Available now</small></button><button onClick={()=>setTab('missions')}><span>ACTIVE MISSIONS</span><strong>{liveMissions.length}</strong><small>Assigned to you</small></button><button onClick={()=>setTab('earnings')}><span>PENDING PAYOUT</span><strong>{money(pending)}</strong><small>Authorized / captured</small></button><button onClick={()=>setTab('account')}><span>SERVICES</span><strong>{hero.services_enabled?.length||0}</strong><small>Approved capabilities</small></button></section></>}
    {tab==='offers'&&<section className="shc-screen"><div className="shc-screen-head"><span>LIVE MISSION OFFERS</span><h1>See it. Choose it. Move.</h1><p>Offers are generated from verified on-duty matching. Accept only what you can safely complete.</p></div>{!hero.on_duty?<div className="shc-empty"><b>OFF PATROL</b><h2>Start patrol to receive offers.</h2><p>GPS presence and payout readiness are required before mission offers can be accepted.</p><Button disabled={!verified||!payout.payout_ready} onClick={togglePatrol}>{verified&&payout.payout_ready?'Start patrol':'Complete setup first'}</Button></div>:offers.length===0?<div className="shc-empty"><b>LIVE</b><h2>No mission offers right now.</h2><p>Hero Command refreshes automatically while you stay on patrol.</p></div>:<div className="shc-offer-grid">{offers.map(o=><OfferCard key={o.id} offer={o} clock={clock} busy={busy===`offer-${o.id}`} onAnswer={accept=>answer(o,accept)}/>)}</div>}</section>}
    {tab==='missions'&&<section className="shc-screen"><div className="shc-screen-head"><span>MISSIONS</span><h1>Run the field cleanly.</h1><p>Every transition is payment-aware, GPS-backed, and tied to your authenticated Hero identity.</p></div>{liveMissions.length>0&&<><div className="shc-subhead">ACTIVE</div><div className="shc-mission-list">{liveMissions.map(m=><button key={m.id} onClick={()=>openMission(m.id)}><i className={`status ${m.status}`}/><div><strong>{m.requested_service_name}</strong><span>{statusLabel(m.status)} · {m.pickup_address}</span><small>{when(m.accepted_at||m.created_at)}</small></div><em>→</em></button>)}</div></>}{completed.length>0&&<><div className="shc-subhead">COMPLETED</div><div className="shc-mission-list completed">{completed.map(m=><button key={m.id} onClick={()=>openMission(m.id)}><i className="status completed"/><div><strong>{m.requested_service_name}</strong><span>{m.pickup_address}</span><small>{when(m.completed_at)}</small></div><em>{money(payByMission[m.id]?.hero_payout)}</em></button>)}</div></>}{missions.length===0&&<div className="shc-empty"><b>0</b><h2>No missions yet.</h2><p>Accepted mission offers will appear here.</p></div>}</section>}
    {tab==='earnings'&&<section className="shc-screen"><div className="shc-screen-head"><span>HERO EARNINGS</span><h1>Real payout numbers only.</h1><p>Earnings come directly from the mission payment ledger and Stripe release state.</p></div><div className="shc-earnings-hero"><span>RELEASED TO DATE</span><strong>{money(released)}</strong><div><b>{money(week)}</b><small>This week</small><b>{money(pending)}</b><small>Pending</small></div></div>{payments.length===0?<div className="shc-empty"><b>$0</b><h2>No payment history yet.</h2><p>Paid missions will populate this ledger automatically.</p></div>:<div className="shc-earning-list">{payments.map(p=>{const m=missions.find(x=>x.id===p.mission_id);return <article key={p.id}><div><strong>{m?.requested_service_name||'S.O.S. mission'}</strong><span>{when(p.released_at||p.captured_at||p.created_at)}</span></div><div><b>{money(p.hero_payout)}</b><small>{statusLabel(p.payment_status)}</small></div></article>})}</div>}</section>}
    {tab==='account'&&<section className="shc-screen"><div className="shc-profile"><div className="shc-profile-avatar">{user?.first_name?.[0]||'H'}</div><span>VERIFIED HERO</span><h1>{[user?.first_name,user?.last_name].filter(Boolean).join(' ')||'S.O.S. Hero'}</h1><p>{user?.email}</p><div><section><strong>{Number(hero.rating||5).toFixed(1)}</strong><span>Rating</span></section><section><strong>{hero.total_missions||0}</strong><span>Missions</span></section><section><strong>{hero.level||'Rookie'}</strong><span>Level</span></section></div></div><Readiness hero={hero} payout={payout} onboard={onboard}/><div className="shc-account-list"><button onClick={togglePatrol}><div><strong>{hero.on_duty?'End patrol':'Patrol availability'}</strong><span>{hero.on_duty?'You are currently visible to dispatch':'Go live when you are ready for work'}</span></div><em>→</em></button><button onClick={onboard}><div><strong>Payout account</strong><span>{payout.payout_ready?'Connected and ready':'Complete Stripe payout setup'}</span></div><em>→</em></button><button onClick={()=>setTab('earnings')}><div><strong>Earnings & payouts</strong><span>{money(released)} released to date</span></div><em>→</em></button><button className="danger" onClick={logout}><div><strong>Sign out</strong><span>End this Hero Command session</span></div><em>→</em></button></div></section>}
  </main><nav className="shc-mobile-nav">{[['home','⌂','Home'],['offers','◎','Offers'],['missions','▤','Missions'],['earnings','$','Earn'],['account','◉','Account']].map(([id,icon,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><b>{icon}</b><span>{label}</span>{id==='offers'&&offers.length>0&&<em>{offers.length}</em>}</button>)}</nav>{selectedMission&&<MissionCommand mission={selectedMission} payment={payByMission[selectedMission.id]} customer={customer} busy={busy===`mission-${selectedMission.id}`||busy===`complete-${selectedMission.id}`||busy===`price-${selectedMission.id}`} onAdvance={status=>advance(selectedMission,status)} onPrice={()=>confirmPrice(selectedMission)} onComplete={()=>setProofMission(selectedMission)} onClose={()=>{setSelectedMission(null);setCustomer(null)}}/>}{proofMission&&<ProofModal mission={proofMission} busy={busy===`complete-${proofMission.id}`} onCancel={()=>setProofMission(null)} onSubmit={notes=>complete(proofMission,notes)}/>}</div>
}
