'use client';

import React,{useCallback,useEffect,useMemo,useRef,useState}from'react';

const SB='https://cxdqkjvtpilvouwtbgdy.supabase.co';
const SK='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4ZHFranZ0cGlsdm91d3RiZ2R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0OTg4MzgsImV4cCI6MjA4NzA3NDgzOH0.pIOX5kzkY6X-lpQjrGkQN7BWSMQSUFVVIvyZ2RA31-4';
const colors={bg:'#071018',card:'#0d1722',card2:'#111f2d',line:'rgba(255,255,255,.10)',text:'#f7fbff',muted:'rgba(232,242,249,.62)',orange:'#ff6b35',green:'#14c98b',gold:'#ffb347',red:'#ff5c68',blue:'#5bbcff'};
const headers=token=>({apikey:SK,Authorization:`Bearer ${token}`,'Content-Type':'application/json'});
const storedSession=()=>{try{const v=JSON.parse(localStorage.getItem('sos_session'));if(!v?.access_token||!v?.user)return null;if(v.expires_at&&v.expires_at<Date.now()/1000)return null;return v}catch{return null}};
const request=async(path,{method='GET',token,body}={})=>{const r=await fetch(`${SB}${path}`,{method,headers:headers(token||SK),body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||d?.error||'Request failed');return d};
const rpc=(token,name,body)=>request(`/rest/v1/rpc/${name}`,{method:'POST',token,body});
const edge=(token,name,body)=>request(`/functions/v1/${name}`,{method:'POST',token,body});
const locate=()=>new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('GPS is not available on this device.'));navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude}),()=>reject(new Error('Precise location permission is required for Hero operations.')),{enableHighAccuracy:true,timeout:12000,maximumAge:10000})});
const paymentReady=status=>['authorized','captured','released'].includes(status||'');
const activeMission=m=>!['completed','canceled_by_citizen','canceled_by_hero','canceled_by_system'].includes(m.status);

function Logo(){return <div style={{display:'flex',alignItems:'center',gap:10}}><div style={{width:42,height:42,borderRadius:13,background:colors.orange,display:'grid',placeItems:'center',fontWeight:1000,fontSize:13,color:'#fff',boxShadow:'0 10px 30px rgba(255,107,53,.25)'}}>SOS</div><div><strong style={{display:'block',fontSize:13,letterSpacing:'.06em'}}>HERO COMMAND</strong><small style={{color:colors.muted,fontSize:10,letterSpacing:'.1em'}}>SUPERHEROES ON STANDBY</small></div></div>}
function Pill({children,tone='default'}){const c=tone==='green'?colors.green:tone==='gold'?colors.gold:tone==='red'?colors.red:colors.blue;return <span style={{fontSize:10,fontWeight:900,letterSpacing:'.08em',padding:'6px 9px',borderRadius:999,color:c,background:`${c}16`,border:`1px solid ${c}35`}}>{children}</span>}
function Button({children,onClick,disabled=false,tone='orange',style={}}){const c=tone==='green'?colors.green:tone==='dark'?colors.card2:tone==='red'?colors.red:colors.orange;return <button disabled={disabled} onClick={onClick} style={{border:tone==='dark'?`1px solid ${colors.line}`:'none',borderRadius:12,padding:'12px 14px',background:c,color:'#fff',fontWeight:850,fontSize:12,cursor:disabled?'not-allowed':'pointer',opacity:disabled?.55:1,...style}}>{children}</button>}

export default function SOSHeroMobilityApp(){
  const[booting,setBooting]=useState(true);const[session,setSession]=useState(null);const[user,setUser]=useState(null);const[hero,setHero]=useState(null);
  const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[authBusy,setAuthBusy]=useState(false);
  const[offers,setOffers]=useState([]);const[missions,setMissions]=useState([]);const[payments,setPayments]=useState([]);const[payout,setPayout]=useState({connected:false,payout_ready:false,requirements_due:[]});
  const[busy,setBusy]=useState('');const[error,setError]=useState('');const[notice,setNotice]=useState('');const heartbeat=useRef(null);

  const load=useCallback(async(nextSession,{quiet=false}={})=>{
    if(!nextSession?.access_token)return;
    try{
      const users=await request(`/rest/v1/sos_users?auth_id=eq.${nextSession.user.id}&select=id,role,first_name,last_name,email,status&limit=1`,{token:nextSession.access_token});
      const u=users?.[0];if(!u)throw new Error('S.O.S. profile not found.');if(u.role!=='hero'){window.location.replace('/app');return}
      const heroes=await request(`/rest/v1/sos_heroes?user_id=eq.${u.id}&select=id,level,rating,total_missions,on_duty,verification_status,stripe_connect_id,license_verified,insurance_verified,background_cleared,id_verified,test_mission_passed&limit=1`,{token:nextSession.access_token});
      const h=heroes?.[0];if(!h)throw new Error('Hero profile not found.');
      const [o,m,p,payoutStatus]=await Promise.all([
        request(`/rest/v1/sos_mission_offers?hero_id=eq.${h.id}&status=eq.pending&select=id,mission_id,eta_minutes,payout_amount,expires_at,offered_at,mission:sos_missions!sos_mission_offers_mission_id_fkey(id,status,requested_service_name,pickup_address,estimated_price,final_price,pricing_status)&order=offered_at.desc`,{token:nextSession.access_token}),
        request(`/rest/v1/sos_missions?hero_id=eq.${h.id}&select=id,status,requested_service_name,pickup_address,pickup_lat,pickup_lng,estimated_price,final_price,pricing_status,eta_minutes,created_at,accepted_at,en_route_at,arrived_at,started_at,completed_at&order=created_at.desc&limit=30`,{token:nextSession.access_token}),
        request(`/rest/v1/sos_payments?hero_id=eq.${h.id}&select=id,mission_id,payment_status,escrow_status,amount,hero_payout,released_at,created_at&order=created_at.desc`,{token:nextSession.access_token}),
        edge(nextSession.access_token,'hero-payouts',{action:'status'}).catch(()=>({connected:Boolean(h.stripe_connect_id),payout_ready:false,requirements_due:[]})),
      ]);
      setUser(u);setHero(h);setOffers(o||[]);setMissions(m||[]);setPayments(p||[]);setPayout(payoutStatus||{});if(!quiet)setError('');
    }catch(e){if(!quiet)setError(e.message||'Hero network unavailable')}
  },[]);

  useEffect(()=>{let active=true;(async()=>{const existing=storedSession();if(existing){setSession(existing);await load(existing)}if(active)setBooting(false)})();return()=>{active=false;if(heartbeat.current)clearInterval(heartbeat.current)}},[load]);
  useEffect(()=>{if(!session||!hero?.on_duty){if(heartbeat.current)clearInterval(heartbeat.current);heartbeat.current=null;return}const beat=async()=>{try{const pos=await locate();await rpc(session.access_token,'sos_set_hero_presence',{p_on_duty:true,p_lat:pos.lat,p_lng:pos.lng,p_zone_id:null,p_device_session_id:`web-${session.user.id}`});await load(session,{quiet:true})}catch{}};heartbeat.current=setInterval(beat,15000);return()=>{if(heartbeat.current)clearInterval(heartbeat.current)}},[session,hero?.on_duty,load]);

  const login=async e=>{e.preventDefault();if(authBusy)return;setAuthBusy(true);setError('');try{const next=await request('/auth/v1/token?grant_type=password',{method:'POST',body:{email,password}});localStorage.setItem('sos_session',JSON.stringify(next));setSession(next);await load(next)}catch(e){setError(e.message.includes('Invalid login')?'Wrong email or password':e.message)}finally{setAuthBusy(false)}};
  const signOut=()=>{if(heartbeat.current)clearInterval(heartbeat.current);localStorage.removeItem('sos_session');setSession(null);setUser(null);setHero(null);setOffers([]);setMissions([]);setPayments([])};
  const refresh=async()=>{setBusy('refresh');await load(session);setBusy('')};
  const onboard=async()=>{setBusy('payout');setError('');try{const d=await edge(session.access_token,'hero-payouts',{action:'onboard'});setPayout(d);if(d.onboarding_url)window.location.assign(d.onboarding_url);else if(d.payout_ready)setNotice('Payout account is active. You can go on patrol.')}catch(e){setError(e.message)}finally{setBusy('')}};
  const togglePatrol=async()=>{setBusy('patrol');setError('');try{if(!hero.on_duty&&!payout.payout_ready)throw new Error('Finish Stripe payout setup before going on patrol.');let pos={lat:null,lng:null};if(!hero.on_duty)pos=await locate();await rpc(session.access_token,'sos_set_hero_presence',{p_on_duty:!hero.on_duty,p_lat:pos.lat,p_lng:pos.lng,p_zone_id:null,p_device_session_id:`web-${session.user.id}`});await load(session);setNotice(hero.on_duty?'You are off patrol.':'You are live and eligible for mission offers.')}catch(e){setError(e.message)}finally{setBusy('')}};
  const answer=async(offer,accept)=>{setBusy(`offer-${offer.id}`);setError('');try{if(accept&&!payout.payout_ready)throw new Error('Payout setup must be active before accepting paid missions.');await rpc(session.access_token,accept?'sos_accept_mission_offer':'sos_decline_mission_offer',accept?{p_offer_id:offer.id}:{p_offer_id:offer.id,p_reason:'Hero declined from app'});await load(session);setNotice(accept?'Mission accepted. Confirm pricing and customer authorization before travel.':'Offer declined.')}catch(e){setError(e.message)}finally{setBusy('')}};
  const confirmPrice=async mission=>{const suggested=Number(mission.final_price||mission.estimated_price||0);const raw=window.prompt('Confirm the final customer price before travel.',suggested>0?suggested.toFixed(2):'');if(raw===null)return;const price=Number(raw);if(!Number.isFinite(price)||price<=0){setError('Enter a valid final price.');return}setBusy(`price-${mission.id}`);setError('');try{await edge(session.access_token,'hero-confirm-price',{mission_id:mission.id,final_price:price});await load(session);setNotice('Price confirmed. Waiting for customer authorization.')}catch(e){setError(e.message)}finally{setBusy('')}};
  const advance=async(mission,status)=>{setBusy(`mission-${mission.id}`);setError('');try{const pos=await locate();await rpc(session.access_token,'sos_transition_assigned_mission',{p_mission_id:mission.id,p_new_status:status,p_lat:pos.lat,p_lng:pos.lng,p_note:null});await load(session);setNotice(status==='en_route'?'Route started.':status==='on_site'?'Arrival recorded.':'Service started.')}catch(e){setError(e.message)}finally{setBusy('')}};
  const complete=async mission=>{const notes=window.prompt('Completion proof note (what was done):','Service completed successfully.');if(notes===null)return;setBusy(`complete-${mission.id}`);setError('');try{const pos=await locate();const d=await edge(session.access_token,'hero-complete-mission',{mission_id:mission.id,notes,lat:pos.lat,lng:pos.lng,media_urls:[]});await load(session);setNotice(d?.payment?.released?'Mission complete. Payment captured and Hero payout released.':'Mission complete. Payment captured; payout is queued for operations review.')}catch(e){setError(e.message)}finally{setBusy('')}};

  const payByMission=useMemo(()=>Object.fromEntries(payments.map(p=>[p.mission_id,p])),[payments]);
  const liveMissions=missions.filter(activeMission);
  const released=payments.filter(p=>p.payment_status==='released').reduce((n,p)=>n+Number(p.hero_payout||0),0);
  const pending=payments.filter(p=>['authorized','captured'].includes(p.payment_status)).reduce((n,p)=>n+Number(p.hero_payout||0),0);
  const verified=hero&&['verified'].includes(hero.verification_status)&&hero.license_verified&&hero.insurance_verified&&hero.background_cleared&&hero.id_verified&&hero.test_mission_passed;

  if(booting)return <div style={{minHeight:'100vh',background:colors.bg,color:colors.text,display:'grid',placeItems:'center',fontFamily:'Inter,system-ui'}}><div style={{textAlign:'center'}}><Logo/><p style={{color:colors.muted}}>Connecting Hero Command…</p></div></div>;
  if(!session)return <div style={{minHeight:'100vh',background:`radial-gradient(circle at 20% 10%,rgba(255,107,53,.16),transparent 32%),${colors.bg}`,color:colors.text,fontFamily:'Inter,system-ui',display:'grid',placeItems:'center',padding:24}}><form onSubmit={login} style={{width:'100%',maxWidth:420,background:colors.card,border:`1px solid ${colors.line}`,borderRadius:24,padding:28,boxShadow:'0 30px 90px rgba(0,0,0,.4)'}}><Logo/><div style={{margin:'36px 0 24px'}}><Pill tone="orange">VERIFIED PROVIDERS</Pill><h1 style={{fontSize:34,lineHeight:1.05,margin:'14px 0 8px'}}>Clock in.<br/>Move fast. Get paid.</h1><p style={{color:colors.muted,lineHeight:1.55,fontSize:13}}>Hero Command is the live field workspace for S.O.S. missions, customer authorization, proof, and payouts.</p></div><label style={{display:'block',fontSize:11,color:colors.muted,marginBottom:14}}>EMAIL<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} style={{display:'block',width:'100%',boxSizing:'border-box',marginTop:7,padding:14,borderRadius:12,border:`1px solid ${colors.line}`,background:colors.card2,color:colors.text}}/></label><label style={{display:'block',fontSize:11,color:colors.muted,marginBottom:14}}>PASSWORD<input required type="password" value={password} onChange={e=>setPassword(e.target.value)} style={{display:'block',width:'100%',boxSizing:'border-box',marginTop:7,padding:14,borderRadius:12,border:`1px solid ${colors.line}`,background:colors.card2,color:colors.text}}/></label>{error&&<div style={{color:colors.red,fontSize:12,marginBottom:12}}>{error}</div>}<Button disabled={authBusy} style={{width:'100%',padding:15}}>{authBusy?'Connecting…':'Enter Hero Command'}</Button><p style={{color:colors.muted,fontSize:10,lineHeight:1.5,marginTop:16}}>Hero accounts are activated only after S.O.S. provider verification.</p></form></div>;

  return <div style={{minHeight:'100vh',background:colors.bg,color:colors.text,fontFamily:'Inter,system-ui',paddingBottom:60}}>
    <header style={{position:'sticky',top:0,zIndex:20,backdropFilter:'blur(18px)',background:'rgba(7,16,24,.88)',borderBottom:`1px solid ${colors.line}`,padding:'14px max(18px,env(safe-area-inset-left))',display:'flex',alignItems:'center',justifyContent:'space-between'}}><Logo/><div style={{display:'flex',gap:8}}><Button tone="dark" onClick={refresh} disabled={busy==='refresh'}>{busy==='refresh'?'…':'Refresh'}</Button><Button tone="dark" onClick={signOut}>Sign out</Button></div></header>
    <main style={{maxWidth:980,margin:'0 auto',padding:'22px 18px'}}>
      <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:12,marginBottom:16}}>
        <div style={{background:colors.card,border:`1px solid ${colors.line}`,borderRadius:18,padding:18}}><small style={{color:colors.muted}}>HERO</small><h2 style={{margin:'5px 0'}}>{[user?.first_name,user?.last_name].filter(Boolean).join(' ')||'S.O.S. Hero'}</h2><div style={{display:'flex',gap:7,flexWrap:'wrap'}}><Pill tone={verified?'green':'red'}>{verified?'VERIFIED':'VERIFICATION NEEDED'}</Pill><Pill tone="gold">★ {Number(hero?.rating||5).toFixed(1)}</Pill></div></div>
        <div style={{background:colors.card,border:`1px solid ${colors.line}`,borderRadius:18,padding:18}}><small style={{color:colors.muted}}>PATROL STATUS</small><h2 style={{margin:'5px 0',color:hero?.on_duty?colors.green:colors.muted}}>{hero?.on_duty?'ON PATROL':'OFF PATROL'}</h2><Button tone={hero?.on_duty?'red':'green'} disabled={busy==='patrol'||(!hero?.on_duty&&!payout.payout_ready)} onClick={togglePatrol}>{busy==='patrol'?'Updating…':hero?.on_duty?'Go off patrol':'Go on patrol'}</Button></div>
        <div style={{background:colors.card,border:`1px solid ${colors.line}`,borderRadius:18,padding:18}}><small style={{color:colors.muted}}>EARNINGS</small><h2 style={{margin:'5px 0',color:colors.green}}>${released.toFixed(2)}</h2><div style={{fontSize:11,color:colors.muted}}>${pending.toFixed(2)} authorized / captured</div></div>
      </section>

      {!payout.payout_ready&&<section style={{background:'linear-gradient(135deg,rgba(255,179,71,.12),rgba(255,107,53,.08))',border:`1px solid ${colors.gold}42`,borderRadius:20,padding:20,marginBottom:16,display:'flex',gap:18,alignItems:'center',justifyContent:'space-between',flexWrap:'wrap'}}><div><Pill tone="gold">REQUIRED TO ACCEPT MISSIONS</Pill><h2 style={{margin:'10px 0 5px'}}>Activate Hero payouts.</h2><p style={{margin:0,color:colors.muted,fontSize:12,maxWidth:560,lineHeight:1.5}}>Stripe verifies identity and banking securely. S.O.S. does not store your bank credentials. You cannot go on patrol until transfers are active.</p>{payout.requirements_due?.length>0&&<small style={{display:'block',color:colors.gold,marginTop:8}}>{payout.requirements_due.length} Stripe requirement{payout.requirements_due.length===1?'':'s'} remaining.</small>}</div><Button tone="orange" onClick={onboard} disabled={busy==='payout'}>{busy==='payout'?'Opening Stripe…':payout.connected?'Continue payout setup':'Set up payouts'}</Button></section>}
      {payout.payout_ready&&<section style={{background:'rgba(20,201,139,.07)',border:`1px solid ${colors.green}35`,borderRadius:14,padding:'12px 15px',marginBottom:16,color:'#a5f3d9',fontSize:12,fontWeight:800}}>✓ Stripe payouts active — your account can receive S.O.S. mission transfers.</section>}
      {error&&<div style={{background:'rgba(255,92,104,.08)',border:`1px solid ${colors.red}35`,color:'#ffabb2',borderRadius:14,padding:13,marginBottom:12,fontSize:12}}>{error}</div>}
      {notice&&<div style={{background:'rgba(91,188,255,.08)',border:`1px solid ${colors.blue}35`,color:'#bde4ff',borderRadius:14,padding:13,marginBottom:12,fontSize:12}}>{notice}</div>}

      <section style={{background:colors.card,border:`1px solid ${colors.line}`,borderRadius:20,padding:20,marginBottom:16}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:10,marginBottom:15}}><div><small style={{color:colors.orange,fontWeight:900,letterSpacing:'.1em'}}>LIVE INBOX</small><h2 style={{margin:'3px 0'}}>Mission offers</h2></div><Pill tone={offers.length?'green':'default'}>{offers.length} OPEN</Pill></div>{offers.length===0?<div style={{padding:'26px 8px',color:colors.muted,textAlign:'center',fontSize:13}}>{hero?.on_duty?'No open offers right now. GPS heartbeat remains active.':'Go on patrol to receive nearby verified mission offers.'}</div>:offers.map(o=><div key={o.id} style={{background:colors.card2,border:`1px solid ${colors.line}`,borderRadius:16,padding:16,marginBottom:10}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><strong>{o.mission?.requested_service_name||'Roadside mission'}</strong><div style={{fontSize:11,color:colors.muted,marginTop:5}}>{o.mission?.pickup_address||'Pickup shown after acceptance'} · ETA {o.eta_minutes||'—'} min</div></div><strong style={{color:colors.green}}>${Number(o.payout_amount||0).toFixed(2)}</strong></div><div style={{display:'flex',gap:8,marginTop:12}}><Button tone="green" style={{flex:1}} disabled={Boolean(busy)||!payout.payout_ready} onClick={()=>answer(o,true)}>Accept mission</Button><Button tone="dark" style={{flex:1}} disabled={Boolean(busy)} onClick={()=>answer(o,false)}>Decline</Button></div></div>)}</section>

      <section style={{background:colors.card,border:`1px solid ${colors.line}`,borderRadius:20,padding:20}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:15}}><div><small style={{color:colors.blue,fontWeight:900,letterSpacing:'.1em'}}>FIELD OPERATIONS</small><h2 style={{margin:'3px 0'}}>Active missions</h2></div><Pill>{liveMissions.length} LIVE</Pill></div>{liveMissions.length===0?<div style={{padding:'26px 8px',color:colors.muted,textAlign:'center',fontSize:13}}>No active assigned missions.</div>:liveMissions.map(m=>{const pay=payByMission[m.id];const authorized=paymentReady(pay?.payment_status);const needsPrice=m.pricing_status!=='confirmed'||!Number(m.final_price||0);const working=busy.includes(m.id);return <article key={m.id} style={{background:colors.card2,border:`1px solid ${colors.line}`,borderRadius:18,padding:17,marginBottom:12}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-start'}}><div><strong style={{fontSize:15}}>{m.requested_service_name||'Roadside mission'}</strong><p style={{fontSize:11,color:colors.muted,margin:'6px 0'}}>{m.pickup_address||'GPS pickup'}</p><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><Pill tone="gold">{m.status.replaceAll('_',' ').toUpperCase()}</Pill><Pill tone={authorized?'green':'red'}>{authorized?`PAYMENT ${pay.payment_status.toUpperCase()}`:'PAYMENT REQUIRED'}</Pill></div></div><div style={{textAlign:'right'}}><small style={{color:colors.muted}}>FINAL</small><strong style={{display:'block',fontSize:21,color:colors.text}}>{Number(m.final_price||0)>0?`$${Number(m.final_price).toFixed(2)}`:'—'}</strong></div></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:8,marginTop:14}}>{m.status==='assigned'&&needsPrice&&<Button disabled={working} onClick={()=>confirmPrice(m)}>Confirm final price</Button>}{m.status==='assigned'&&!needsPrice&&!authorized&&<Button tone="dark" disabled>Waiting for customer authorization</Button>}{m.status==='assigned'&&authorized&&<Button tone="green" disabled={working} onClick={()=>advance(m,'en_route')}>Start route</Button>}{m.status==='en_route'&&<Button tone="green" disabled={working} onClick={()=>advance(m,'on_site')}>Mark arrived</Button>}{m.status==='on_site'&&<Button tone="green" disabled={working} onClick={()=>advance(m,'working')}>Start service</Button>}{m.status==='working'&&<Button tone="green" disabled={working} onClick={()=>complete(m)}>Complete + capture payment</Button>}</div></article>})}</section>
    </main>
  </div>;
}
