'use client';

import React,{useEffect,useState}from'react';
const SB='https://cxdqkjvtpilvouwtbgdy.supabase.co';
const SK='sb_publishable_x_QDbPwZuhbqB1bd58MLvg_ADSiFODN';
const stored=()=>{try{const s=JSON.parse(localStorage.getItem('sos_session'));if(!s?.access_token||!s?.user)return null;if(s.expires_at&&s.expires_at<Date.now()/1000)return null;return s}catch{return null}};
const request=async(path,{method='GET',token,body}={})=>{const r=await fetch(`${SB}${path}`,{method,headers:{apikey:SK,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||d?.error_description||d?.error||'Request failed');return d};
const TAGS=['ready','clear_location','respectful','safe_location','unresponsive','access_issue'];
const label=tag=>({ready:'Ready',clear_location:'Clear location',respectful:'Respectful',safe_location:'Safe location',unresponsive:'Unresponsive',access_issue:'Access issue'}[tag]||tag);

export default function SOSHeroCitizenTrustHost(){
 const[offer,setOffer]=useState(null),[trust,setTrust]=useState(null),[pending,setPending]=useState(null),[rating,setRating]=useState(5),[tags,setTags]=useState([]),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[dismissed,setDismissed]=useState(false),[notice,setNotice]=useState('');
 const load=async()=>{const s=stored();if(!s){setOffer(null);setTrust(null);setPending(null);return}const us=await request(`/rest/v1/sos_users?auth_id=eq.${s.user.id}&select=id,role&limit=1`,{token:s.access_token});const u=us?.[0];if(!u||u.role!=='hero'){setOffer(null);setTrust(null);setPending(null);return}const hs=await request(`/rest/v1/sos_heroes?user_id=eq.${u.id}&select=id&limit=1`,{token:s.access_token});const h=hs?.[0];if(!h)return;const offers=await request(`/rest/v1/sos_mission_offers?hero_id=eq.${h.id}&status=eq.pending&select=id,mission_id&order=offered_at.desc&limit=1`,{token:s.access_token});const next=offers?.[0]||null;setOffer(next);if(next){const t=await request('/rest/v1/rpc/sos_hero_offer_citizen_trust',{method:'POST',token:s.access_token,body:{p_offer_id:next.id}}).catch(()=>[]);setTrust(t?.[0]||null)}else setTrust(null);const review=await request('/rest/v1/rpc/sos_hero_pending_citizen_review',{method:'POST',token:s.access_token,body:{}}).catch(()=>[]);setPending(review?.[0]||null)};
 useEffect(()=>{let disposed=false;const run=()=>{if(!disposed)load().catch(()=>{})};run();const t=setInterval(run,10000);const focus=()=>run();window.addEventListener('focus',focus);return()=>{disposed=true;clearInterval(t);window.removeEventListener('focus',focus)}},[]);
 const toggle=tag=>setTags(prev=>prev.includes(tag)?prev.filter(x=>x!==tag):prev.length>=8?prev:[...prev,tag]);
 const submit=async()=>{const s=stored();if(!s||!pending||busy)return;setBusy(true);setNotice('');try{await request('/rest/v1/rpc/sos_hero_rate_citizen',{method:'POST',token:s.access_token,body:{p_mission_id:pending.mission_id,p_rating:rating,p_tags:tags,p_note:note.trim()||null}});setNotice('Citizen reliability rating saved.');setPending(null);setDismissed(false);setTags([]);setNote('');setRating(5);await load();setTimeout(()=>setNotice(''),3500)}catch(e){setNotice(e.message)}finally{setBusy(false)}};
 return <>
  {offer&&trust&&<div style={{position:'fixed',right:16,top:122,zIndex:1720,padding:'9px 11px',borderRadius:14,background:'rgba(17,27,37,.95)',border:'1px solid rgba(255,255,255,.12)',color:'#fff',boxShadow:'0 12px 34px rgba(0,0,0,.3)',backdropFilter:'blur(12px)'}}><small style={{display:'block',fontSize:8,fontWeight:900,letterSpacing:'.1em',color:'#ff9d77'}}>CUSTOMER RELIABILITY</small><strong style={{display:'block',fontSize:16,marginTop:2}}>★ {Number(trust.trust_score||5).toFixed(1)}</strong><span style={{display:'block',fontSize:8,color:'rgba(255,255,255,.52)'}}>{trust.rating_count||0} Hero rating{Number(trust.rating_count||0)===1?'':'s'}</span></div>}
  {pending&&!dismissed&&<div role="dialog" aria-modal="false" style={{position:'fixed',left:'50%',transform:'translateX(-50%)',bottom:18,zIndex:2150,width:'min(560px,calc(100vw - 28px))',padding:18,borderRadius:22,background:'#101922',color:'#fff',boxShadow:'0 26px 80px rgba(0,0,0,.46)',border:'1px solid rgba(255,255,255,.11)'}}><div style={{display:'flex',justifyContent:'space-between',gap:14}}><div><small style={{fontSize:9,fontWeight:900,letterSpacing:'.12em',color:'#ff8a5b'}}>CUSTOMER RELIABILITY</small><h3 style={{fontSize:20,margin:'5px 0 4px'}}>How was {pending.citizen_first_name||'the customer'}?</h3><p style={{fontSize:10.5,color:'rgba(255,255,255,.6)',margin:0}}>{pending.service_name||'S.O.S. mission'} · one locked rating for this completed mission.</p></div><button type="button" onClick={()=>setDismissed(true)} style={{width:32,height:32,border:0,borderRadius:11,background:'rgba(255,255,255,.08)',color:'#fff',fontSize:18}}>×</button></div><div style={{display:'flex',gap:6,marginTop:14}}>{[1,2,3,4,5].map(n=><button key={n} type="button" onClick={()=>setRating(n)} style={{flex:1,border:0,borderRadius:12,padding:'10px 0',background:n<=rating?'#ff6b35':'rgba(255,255,255,.07)',color:'#fff',fontSize:18}}>★</button>)}</div><div style={{display:'flex',flexWrap:'wrap',gap:6,marginTop:11}}>{TAGS.map(tag=><button key={tag} type="button" onClick={()=>toggle(tag)} style={{border:`1px solid ${tags.includes(tag)?'#ff8a5b':'rgba(255,255,255,.12)'}`,borderRadius:999,padding:'7px 9px',background:tags.includes(tag)?'rgba(255,107,53,.14)':'transparent',color:'#fff',fontSize:9,fontWeight:800}}>{label(tag)}</button>)}</div><textarea value={note} onChange={e=>setNote(e.target.value.slice(0,1000))} placeholder="Optional private mission note" style={{width:'100%',boxSizing:'border-box',minHeight:58,marginTop:10,border:'1px solid rgba(255,255,255,.12)',borderRadius:12,padding:10,background:'rgba(255,255,255,.06)',color:'#fff',font:'inherit',fontSize:10,resize:'vertical'}}/>{notice&&<div style={{fontSize:9,color:'#ffc4c8',marginTop:7}}>{notice}</div>}<button type="button" onClick={submit} disabled={busy} style={{width:'100%',border:0,borderRadius:13,padding:12,marginTop:10,background:'#ff6b35',color:'#fff',fontSize:10,fontWeight:900}}>{busy?'SAVING…':'SUBMIT CUSTOMER RATING'}</button></div>}
  {notice&&!pending&&<div role="status" style={{position:'fixed',right:16,bottom:92,zIndex:2200,padding:'10px 12px',borderRadius:12,background:'#111b25',color:'#fff',fontSize:10}}>{notice}</div>}
 </>;
}
