'use client';

const p={margin:'8px 0',color:'rgba(255,255,255,.72)',fontSize:14,lineHeight:1.72};
const h2={margin:'26px 0 8px',fontSize:20,letterSpacing:'-.02em'};
const ul={margin:'8px 0',paddingLeft:22,color:'rgba(255,255,255,.72)',fontSize:14,lineHeight:1.72};

function Privacy(){return <>
  <p style={p}>This Privacy Policy explains how S.O.S. — Superheroes On Standby handles information when customers request roadside service and when Heroes apply, verify, go on duty, accept missions, complete work, communicate, receive payouts, or use account features.</p>
  <h2 style={h2}>Information we handle</h2><ul style={ul}><li>Account and contact information such as name, email, phone number and profile details.</li><li>Vehicle information you provide, including make, model, year, color, plate or VIN when needed for the service.</li><li>Pickup, destination and device location data used for matching, routing, active mission tracking and safety.</li><li>Mission details, photos, proof of service, messages, ratings, disputes, support tickets and safety records.</li><li>Hero application, identity, background, licensing, insurance, equipment and service-area verification information.</li><li>Payment and payout identifiers and transaction status. Card entry is processed through Stripe; S.O.S. does not need to store a customer’s full payment-card number.</li><li>Push-notification and device information used to deliver account and mission alerts.</li></ul>
  <h2 style={h2}>How information is used</h2><p style={p}>Information is used to authenticate accounts, calculate or confirm service pricing, match eligible Heroes, coordinate missions, process payments and payouts, send status updates, provide support, investigate disputes or safety issues, prevent abuse, comply with law, and improve reliability.</p>
  <h2 style={h2}>Location and mission sharing</h2><p style={p}>Precise location is used when you permit it or provide a service location. During an active mission, necessary location and service details may be shared between the assigned customer and Hero. Mission-sharing links, when offered, should disclose only the limited tracking information needed for that feature and can be revoked where supported.</p>
  <h2 style={h2}>Service providers and disclosures</h2><p style={p}>S.O.S. may use infrastructure, payment, communications, storage, security and verification providers to operate the service. Information may also be disclosed when reasonably necessary for safety, fraud prevention, dispute handling, legal compliance, or valid legal process.</p>
  <h2 style={h2}>Account deletion and retention</h2><p style={p}>Signed-in users can use the account-deletion tools provided in S.O.S. to remove their sign-in identity and active personal profile. Certain transaction, accounting, fraud-prevention, dispute or safety records may be retained where reasonably necessary or legally required, with personal information removed or anonymized where the system can safely do so.</p>
  <h2 style={h2}>Security and choices</h2><p style={p}>S.O.S. uses access controls, restricted server credentials, verification gates and signed payment/webhook flows designed to protect marketplace data. You can manage supported notification, vehicle and account preferences in the app. No online system can guarantee absolute security.</p>
  <h2 style={h2}>Children</h2><p style={p}>S.O.S. accounts are intended for people legally able to request or provide roadside services and are not directed to children under 13.</p>
  <h2 style={h2}>Contact</h2><p style={p}>Privacy or account questions can be sent to <a href="mailto:thedoctordorsey@gmail.com" style={{color:'#8fd6ff'}}>thedoctordorsey@gmail.com</a>.</p>
</>}

function Terms(){return <>
  <p style={p}>These Terms govern use of S.O.S. — Superheroes On Standby. By creating an account, requesting a mission, accepting Hero work, or using a paid feature, you agree to these terms and to the pricing, cancellation and service details shown for the specific transaction.</p>
  <h2 style={h2}>S.O.S. is not 911</h2><p style={p}>S.O.S. is a roadside mobility and assistance marketplace. It is not an emergency-response authority and must not replace 911, police, fire, ambulance or other emergency services when there is immediate danger, a medical emergency, fire or crime in progress.</p>
  <h2 style={h2}>Marketplace role</h2><p style={p}>S.O.S. coordinates roadside requests with eligible Heroes and service operators. Catalog listings describe services the platform supports; they do not guarantee that a Hero is currently available in every market. A mission is not assigned until an eligible Hero accepts or is otherwise confirmed through the marketplace.</p>
  <h2 style={h2}>Accounts and eligibility</h2><p style={p}>Users must provide accurate information, protect account credentials and use the service lawfully. Hero access may require identity, background, licensing, insurance, equipment, service-area, test-mission and payout verification before missions can be accepted.</p>
  <h2 style={h2}>Pricing and payments</h2><p style={p}>Estimates, confirmed prices, service minimums and applicable fees are shown through the mission flow. S.O.S. may authorize a payment method before work and capture the appropriate amount after completion or under the cancellation/no-show terms presented for that mission. Payment processing is provided through Stripe.</p>
  <h2 style={h2}>Hero payouts</h2><p style={p}>Eligible Hero earnings may be transferred through the connected payout system after the underlying mission and payment conditions are satisfied. Verification, payout availability, disputes, reversals or account restrictions can delay or prevent transfer.</p>
  <h2 style={h2}>Cancellations, disputes and refunds</h2><p style={p}>Cancellation or no-show charges may apply when disclosed in the mission flow. Pricing, service-quality or completion disputes should be submitted through S.O.S. support or dispute tools so the transaction can be reviewed against mission records and available evidence.</p>
  <h2 style={h2}>Safety and lawful service</h2><p style={p}>Customers and Heroes must use reasonable safety precautions and may not request or perform unlawful, dangerous or unauthorized work. A Hero should not perform a service that requires licensing, equipment, training or authority the Hero does not possess.</p>
  <h2 style={h2}>Prohibited use</h2><p style={p}>Do not use S.O.S. for fraud, harassment, impersonation, unauthorized access, payment abuse, unsafe conduct, illegal activity, interference with the platform, false verification evidence or misuse of customer/Hero information.</p>
  <h2 style={h2}>Suspension and termination</h2><p style={p}>Account or marketplace access may be restricted for safety, fraud, nonpayment, verification failure, repeated policy violations or unlawful activity. Users may delete their account using the available account tools.</p>
  <h2 style={h2}>Service limitations</h2><p style={p}>Hero availability, arrival times, traffic, weather, parts, vehicle condition and service outcomes can vary. To the extent permitted by applicable law, S.O.S. is not responsible for delays or failures caused by circumstances outside its reasonable control. Nothing in these terms removes rights that cannot legally be waived.</p>
  <h2 style={h2}>Contact</h2><p style={p}>Questions about these terms or a mission can be sent to <a href="mailto:thedoctordorsey@gmail.com" style={{color:'#8fd6ff'}}>thedoctordorsey@gmail.com</a>.</p>
</>}

export default function SOSLegalDocument({kind}){
  const privacy=kind==='privacy';
  return <main style={{minHeight:'100dvh',background:'radial-gradient(circle at 15% 5%,rgba(0,169,255,.16),transparent 28%),linear-gradient(155deg,#05080d,#0a1725 55%,#030509)',color:'#fff',fontFamily:'DM Sans,system-ui,sans-serif',padding:'30px 18px 70px'}}><div style={{width:'min(860px,100%)',margin:'0 auto'}}><a href="/" style={{display:'inline-flex',alignItems:'center',gap:9,color:'#fff',textDecoration:'none',fontWeight:900,fontSize:12}}><span style={{width:36,height:36,borderRadius:12,display:'grid',placeItems:'center',background:'#fff',color:'#05080d'}}>SOS</span>SUPERHEROES ON STANDBY</a><header style={{margin:'56px 0 30px'}}><div style={{fontSize:10,fontWeight:950,letterSpacing:'.17em',color:'#81d8ff'}}>LEGAL · EFFECTIVE AUGUST 9, 2026</div><h1 style={{fontFamily:'Barlow Condensed,system-ui,sans-serif',fontSize:'clamp(44px,8vw,72px)',lineHeight:.95,letterSpacing:'-.035em',margin:'10px 0 14px'}}>{privacy?'PRIVACY POLICY':'TERMS OF SERVICE'}</h1><p style={{...p,maxWidth:720,fontSize:15}}>{privacy?'How S.O.S. handles customer, vehicle, location, mission, Hero verification and payment information.':'Operating rules for customers, Heroes, roadside missions, payments, safety and marketplace access.'}</p></header><article style={{padding:'clamp(21px,4vw,38px)',borderRadius:26,border:'1px solid rgba(255,255,255,.1)',background:'rgba(7,17,28,.82)',boxShadow:'0 32px 100px rgba(0,0,0,.3)'}}>{privacy?<Privacy/>:<Terms/>}</article><nav style={{display:'flex',gap:17,flexWrap:'wrap',marginTop:24,fontSize:12}}><a href="/privacy" style={{color:'#91d9ff'}}>Privacy</a><a href="/terms" style={{color:'#91d9ff'}}>Terms</a><a href="/legal" style={{color:'#91d9ff'}}>Safety / Not 911</a><a href="mailto:thedoctordorsey@gmail.com" style={{color:'#91d9ff'}}>Support</a><a href="/" style={{color:'#91d9ff'}}>Back to S.O.S.</a></nav></div></main>
}
