'use client';

import React,{useEffect,useMemo,useRef,useState}from'react';
import{authorizeSosRealtime}from'../lib/sosRealtimeClient';
const SB='https://cxdqkjvtpilvouwtbgdy.supabase.co';
const SK='sb_publishable_x_QDbPwZuhbqB1bd58MLvg_ADSiFODN';
const stored=()=>{try{const s=JSON.parse(localStorage.getItem('sos_session'));if(!s?.access_token||!s?.user)return null;if(s.expires_at&&s.expires_at<Date.now()/1000)return null;return s}catch{return null}};
const request=async(path,{method='GET',token,body}={})=>{const r=await fetch(`${SB}${path}`,{method,headers:{apikey:SK,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||d?.error_description||d?.error||'Request failed');return d};

export default function SOSMissionChatHost(){
 const[mission,setMission]=useState(null),[userId,setUserId]=useState(''),[messages,setMessages]=useState([]),[open,setOpen]=useState(false),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const scrollRef=useRef(null);
 const loadMessages=async(s,id)=>{const rows=await request(`/rest/v1/sos_mission_messages?mission_id=eq.${id}&select=id,mission_id,sender_user_id,sender_role,content,is_read,read_at,created_at&order=created_at.asc&limit=200`,{token:s.access_token});setMessages(rows||[])};
 const findMission=async()=>{const s=stored();if(!s){setMission(null);setMessages([]);setUserId('');return null}const us=await request(`/rest/v1/sos_users?auth_id=eq.${s.user.id}&select=id,role&limit=1`,{token:s.access_token});const u=us?.[0];if(!u){setMission(null);setMessages([]);return null}setUserId(u.id);let rows=[];if(u.role==='hero'){const hs=await request(`/rest/v1/sos_heroes?user_id=eq.${u.id}&select=id&limit=1`,{token:s.access_token});const h=hs?.[0];if(!h){setMission(null);setMessages([]);return null}rows=await request(`/rest/v1/sos_missions?hero_id=eq.${h.id}&status=in.(assigned,en_route,on_site,working,completed)&select=id,status,requested_service_name,completed_at&order=created_at.desc&limit=10`,{token:s.access_token})}else{rows=await request(`/rest/v1/sos_missions?citizen_id=eq.${u.id}&status=in.(assigned,en_route,on_site,working,completed)&select=id,status,requested_service_name,completed_at&order=created_at.desc&limit=10`,{token:s.access_token})}const now=Date.now();const current=(rows||[]).find(row=>row.status!=='completed'||Boolean(row.completed_at&&now-new Date(row.completed_at).getTime()<=86400000))||null;setMission(current);if(current)await loadMessages(s,current.id);else setMessages([]);return current};
 useEffect(()=>{let disposed=false;const run=()=>{if(!disposed)findMission().catch(()=>{})};run();const t=setInterval(run,12000);const focus=()=>run();window.addEventListener('focus',focus);return()=>{disposed=true;clearInterval(t);window.removeEventListener('focus',focus)}},[]);
 useEffect(()=>{if(!mission)return;const s=stored();if(!s)return;let disposed=false;let channel=null;const realtime=authorizeSosRealtime(s.access_token);channel=realtime.channel(`sos-mission-chat:${mission.id}`).on('postgres_changes',{event:'*',schema:'public',table:'sos_mission_messages',filter:`mission_id=eq.${mission.id}`},()=>{const next=stored();if(next&&!disposed)loadMessages(next,mission.id).catch(()=>{})}).subscribe();return()=>{disposed=true;if(channel)realtime.removeChannel(channel)}},[mission?.id]);
 useEffect(()=>{if(!open||!mission)return;const s=stored();if(!s)return;request('/rest/v1/rpc/sos_mark_mission_messages_read',{method:'POST',token:s.access_token,body:{p_mission_id:mission.id}}).then(()=>loadMessages(s,mission.id)).catch(()=>{});setTimeout(()=>scrollRef.current?.scrollTo({top:scrollRef.current.scrollHeight,behavior:'smooth'}),60)},[open,mission?.id,messages.length]);
 const unread=useMemo(()=>messages.filter(m=>m.sender_user_id!==userId&&!m.is_read).length,[messages,userId]);
 const send=async()=>{const s=stored();if(!s||!mission||busy||!draft.trim())return;const text=draft.trim();setBusy(true);setError('');setDraft('');try{await request('/rest/v1/rpc/sos_send_mission_message',{method:'POST',token:s.access_token,body:{p_mission_id:mission.id,p_content:text}});await loadMessages(s,mission.id)}catch(e){setError(e.message);setDraft(text)}finally{setBusy(false)}};
 if(!mission)return null;
 return <>
  <button type="button" onClick={()=>setOpen(true)} style={{position:'fixed',right:16,bottom:92,zIndex:1580,border:0,borderRadius:999,padding:'11px 14px',background:'#111b25',color:'#fff',fontSize:10,fontWeight:900,letterSpacing:'.06em',boxShadow:'0 14px 40px rgba(0,0,0,.32)'}}>CHAT{unread>0?<span style={{marginLeft:7,padding:'2px 6px',borderRadius:999,background:'#ff6b35',fontSize:9}}>{unread}</span>:null}</button>
  {open&&<div role="dialog" aria-modal="true" style={{position:'fixed',inset:0,zIndex:2300,background:'rgba(3,8,15,.68)',display:'grid',placeItems:'end center',padding:12,backdropFilter:'blur(8px)'}}><section style={{width:'min(620px,100%)',height:'min(680px,82dvh)',borderRadius:24,background:'#f7f9fc',boxShadow:'0 32px 100px rgba(0,0,0,.48)',display:'grid',gridTemplateRows:'auto 1fr auto',overflow:'hidden'}}>
   <header style={{padding:'15px 17px',background:'#101922',color:'#fff',display:'flex',alignItems:'center',justifyContent:'space-between',gap:12}}><div><small style={{fontSize:9,fontWeight:900,letterSpacing:'.12em',color:'#ff8a5b'}}>S.O.S. MISSION CHAT · {mission.status.replaceAll('_',' ').toUpperCase()}</small><strong style={{display:'block',fontSize:15,marginTop:3}}>{mission.requested_service_name||'Roadside mission'}</strong></div><button type="button" onClick={()=>setOpen(false)} style={{width:34,height:34,border:0,borderRadius:12,background:'rgba(255,255,255,.09)',color:'#fff',fontSize:20}}>×</button></header>
   <div ref={scrollRef} style={{overflowY:'auto',padding:'16px 14px',display:'flex',flexDirection:'column',gap:9}}>{messages.length===0?<div style={{margin:'auto',textAlign:'center',color:'#8490a5',fontSize:12}}><strong style={{display:'block',fontSize:16,color:'#334155'}}>Message your mission partner.</strong><span style={{display:'block',marginTop:5}}>Coordinate arrival and roadside details without leaving S.O.S.</span></div>:messages.map(m=>{const mine=m.sender_user_id===userId;return <div key={m.id} style={{alignSelf:mine?'flex-end':'flex-start',maxWidth:'82%'}}><div style={{padding:'10px 12px',borderRadius:mine?'15px 15px 4px 15px':'15px 15px 15px 4px',background:mine?'#ff6b35':'#fff',color:mine?'#fff':'#1f2937',fontSize:12,lineHeight:1.48,boxShadow:mine?'none':'0 6px 20px rgba(15,23,42,.08)',border:mine?'0':'1px solid #e5eaf1'}}>{m.content}</div><small style={{display:'block',marginTop:3,textAlign:mine?'right':'left',color:'#9aa4b5',fontSize:8}}>{mine?'YOU':m.sender_role.toUpperCase()} · {new Date(m.created_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</small></div>})}</div>
   <footer style={{padding:'10px 12px',borderTop:'1px solid #e5eaf1',background:'#fff'}}>{error&&<div style={{fontSize:10,color:'#c52b2b',marginBottom:7}}>{error}</div>}<div style={{display:'grid',gridTemplateColumns:'1fr auto',gap:8}}><textarea value={draft} onChange={e=>setDraft(e.target.value.slice(0,2000))} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Message customer/Hero…" style={{resize:'none',minHeight:42,maxHeight:110,border:'1px solid #dbe2ec',borderRadius:14,padding:'11px 12px',font:'inherit',fontSize:12,outline:'none'}}/><button type="button" onClick={send} disabled={busy||!draft.trim()} style={{border:0,borderRadius:14,padding:'0 17px',background:'#ff6b35',color:'#fff',fontSize:11,fontWeight:900,opacity:busy||!draft.trim()?0.6:1}}>SEND</button></div><small style={{display:'block',marginTop:6,color:'#9aa4b5',fontSize:8}}>Only participants in this mission can read or send messages. Access closes 24 hours after completion.</small></footer>
  </section></div>}
 </>;
}
