'use client';

import React,{useEffect,useMemo,useState}from'react';

const SB='https://cxdqkjvtpilvouwtbgdy.supabase.co';
const SK='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4ZHFranZ0cGlsdm91d3RiZ2R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0OTg4MzgsImV4cCI6MjA4NzA3NDgzOH0.pIOX5kzkY6X-lpQjrGkQN7BWSMQSUFVVIvyZ2RA31-4';
const headers=token=>({apikey:SK,Authorization:`Bearer ${token||SK}`,'Content-Type':'application/json'});
const getSession=()=>{try{const value=JSON.parse(localStorage.getItem('sos_session'));if(!value?.access_token)return null;if(value.expires_at&&value.expires_at<Date.now()/1000)return null;return value}catch{return null}};

export default function SOSMembershipHost(){
  const[open,setOpen]=useState(false);const[plans,setPlans]=useState([]);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[readiness,setReadiness]=useState(null);
  const activePlan=useMemo(()=>plans.find(plan=>plan.featured)||plans[1]||plans[0],[plans]);

  useEffect(()=>{const handler=e=>{const button=e.target?.closest?.('.sos2-membership button');if(button){e.preventDefault();e.stopPropagation();setOpen(true)}};document.addEventListener('click',handler,true);return()=>document.removeEventListener('click',handler,true)},[]);
  useEffect(()=>{let active=true;(async()=>{try{const [plansRes,readyRes]=await Promise.all([fetch(`${SB}/rest/v1/sos_membership_plans?select=id,name,tagline,monthly_price,included_services,discount_percent,priority_matching,household_members,features&is_active=eq.true&order=sort_order.asc`,{headers:headers()}),fetch(`${SB}/rest/v1/rpc/sos_get_public_network_readiness`,{method:'POST',headers:headers(),body:'{}'})]);const nextPlans=await plansRes.json();const nextReadiness=await readyRes.json();if(active){setPlans((nextPlans||[]).map((p,index)=>({...p,featured:index===1})));setReadiness(nextReadiness)}}catch{}const params=new URLSearchParams(window.location.search);if(params.get('membership')==='success'&&params.get('session_id')){const session=getSession();if(session?.access_token){setLoading(true);try{const response=await fetch(`${SB}/functions/v1/sos-membership`,{method:'POST',headers:headers(session.access_token),body:JSON.stringify({action:'verify',sessionId:params.get('session_id')})});const data=await response.json();if(!response.ok)throw new Error(data?.error||'Membership verification failed');if(active&&data.verified){setNotice(`${data.plan?.name||'Shield'} is active.`);setOpen(true);history.replaceState({},'',window.location.pathname)}}catch(e){if(active){setError(e.message);setOpen(true)}}finally{if(active)setLoading(false)}}}})();return()=>{active=false}},[]);

  const checkout=async plan=>{const session=getSession();if(!session?.access_token){setError('Sign in or create your SOS account first, then activate Shield from the home screen.');return}setLoading(true);setError('');try{const response=await fetch(`${SB}/functions/v1/sos-membership`,{method:'POST',headers:headers(session.access_token),body:JSON.stringify({action:'checkout',planId:plan.id})});const data=await response.json();if(!response.ok||!data?.url)throw new Error(data?.error||'Membership checkout is unavailable');window.location.assign(data.url)}catch(e){setError(e.message)}finally{setLoading(false)}};

  return <>
    {readiness&&<div className="sosx-readiness"><span className={readiness.on_duty_heroes>0?'live':'building'}/><div><strong>{readiness.on_duty_heroes>0?`${readiness.on_duty_heroes} Heroes online`:'Network activation in progress'}</strong><small>{readiness.recruiting_candidates||0} candidates · {readiness.passed_checks||0}/{readiness.verification_checks||0} verification checks passed</small></div></div>}
    {open&&<div className="sosx-backdrop" onMouseDown={()=>setOpen(false)}><section className="sosx-sheet" onMouseDown={e=>e.stopPropagation()}><div className="sosx-handle"/><header><div><span>SHIELD MEMBERSHIP</span><h2>Roadside confidence,<br/>built around you.</h2><p>Priority matching, member pricing, and included roadside coverage.</p></div><button onClick={()=>setOpen(false)}>×</button></header>{loading&&<div className="sosx-progress">Opening secure membership…</div>}{error&&<div className="sosx-error">{error}</div>}{notice&&<div className="sosx-notice">{notice}</div>}<div className="sosx-plans">{plans.map(plan=><article key={plan.id} className={plan===activePlan?'featured':''}>{plan===activePlan&&<b>MOST POPULAR</b>}<small>SOS {plan.name.toUpperCase()}</small><h3>{plan.name}</h3><p>{plan.tagline}</p><div className="sosx-price"><strong>${Number(plan.monthly_price).toFixed(0)}</strong><span>/month</span></div><ul>{(plan.features||[]).map(feature=><li key={feature}>✓ {feature}</li>)}</ul><button disabled={loading} onClick={()=>checkout(plan)}>Choose {plan.name}</button></article>)}</div><p className="sosx-truth">Membership does not replace emergency services. For a life-threatening emergency, call 911.</p></section></div>}
  </>
}
