'use client';

import React,{useEffect,useState}from'react';

const SB='https://cxdqkjvtpilvouwtbgdy.supabase.co';
const SK='sb_publishable_x_QDbPwZuhbqB1bd58MLvg_ADSiFODN';
const headers=token=>({apikey:SK,Authorization:`Bearer ${token||SK}`,'Content-Type':'application/json'});
const getSession=()=>{try{if(typeof window==='undefined')return null;const value=JSON.parse(localStorage.getItem('sos_session'));if(!value?.access_token)return null;if(value.expires_at&&value.expires_at<Date.now()/1000)return null;return value}catch{return null}};
const callMembership=async(token,body)=>{const response=await fetch(`${SB}/functions/v1/sos-membership`,{method:'POST',headers:headers(token),body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error||'Membership request failed');return data};

export default function SOSMembershipHost(){
  const[open,setOpen]=useState(false);const[plans,setPlans]=useState([]);const[currentPlan,setCurrentPlan]=useState(null);const[subscription,setSubscription]=useState(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[readiness,setReadiness]=useState(null);const[paymentHealth,setPaymentHealth]=useState(null);

  const loadPlans=async()=>{const session=getSession();setLoading(true);setError('');try{if(session?.access_token){const data=await callMembership(session.access_token,{action:'plans'});setPlans(data.plans||[]);setCurrentPlan(data.currentPlan||null);setSubscription(data.subscription||null)}else{const response=await fetch(`${SB}/rest/v1/sos_membership_plans?select=id,name,tagline,monthly_price,included_services,discount_percent,priority_matching,household_members,features&is_active=eq.true&order=sort_order.asc`,{headers:headers()});const data=await response.json();if(!response.ok)throw new Error(data?.message||'Shield plans are unavailable');setPlans(data||[])}}catch(e){setError(e.message||'Shield plans could not be loaded.')}finally{setLoading(false)}};

  useEffect(()=>{const handler=e=>{const button=e.target?.closest?.('.sos2-membership button');if(button){e.preventDefault();e.stopPropagation();setOpen(true)}};document.addEventListener('click',handler,true);return()=>document.removeEventListener('click',handler,true)},[]);
  useEffect(()=>{if(open)loadPlans().catch(()=>{})},[open]);
  useEffect(()=>{let active=true;(async()=>{try{const[readyRes,healthRes]=await Promise.all([fetch(`${SB}/functions/v1/sos-network-readiness`,{headers:headers()}),fetch(`${SB}/functions/v1/marketplace-payments-health`,{headers:{apikey:SK},cache:'no-store'})]);const[nextReadiness,nextHealth]=await Promise.all([readyRes.json().catch(()=>null),healthRes.json().catch(()=>null)]);if(active&&nextReadiness)setReadiness(nextReadiness);if(active&&nextHealth)setPaymentHealth(nextHealth)}catch{}const params=new URLSearchParams(window.location.search);if(params.get('membership')==='success'&&params.get('session_id')){const session=getSession();if(session?.access_token){setOpen(true);setLoading(true);try{const data=await callMembership(session.access_token,{action:'verify',sessionId:params.get('session_id')});if(active&&data.verified){setNotice(`${data.plan?.name||'Shield'} is active.`);await loadPlans()}}catch(e){if(active)setError(e.message)}finally{if(active)setLoading(false);const url=new URL(window.location.href);url.searchParams.delete('membership');url.searchParams.delete('session_id');history.replaceState({},'',url.pathname+url.search+url.hash)}}}else if(params.get('membership')==='canceled'){setNotice('Membership checkout was canceled. No plan change was made.');setOpen(true);const url=new URL(window.location.href);url.searchParams.delete('membership');history.replaceState({},'',url.pathname+url.search+url.hash)}})();return()=>{active=false}},[]);

  const checkout=async plan=>{const session=getSession();if(!session?.access_token){setError('Sign in or create your S.O.S. account first, then activate Shield from the home screen.');return}if(paymentHealth?.ready===false){setError('Shield enrollment is temporarily unavailable because the secure payment runtime is not configured. No charge was attempted.');return}setLoading(true);setError('');setNotice('');try{const data=await callMembership(session.access_token,{action:'checkout',planId:plan.id});if(!data?.url)throw new Error('Secure membership checkout is unavailable.');window.location.assign(data.url)}catch(e){setError(e.message)}finally{setLoading(false)}};

  return <>
    {readiness&&<div className="sosx-readiness"><span className={Number(readiness.on_duty_heroes||0)>0?'live':'building'}/><div><strong>{Number(readiness.on_duty_heroes||0)>0?`${readiness.on_duty_heroes} Heroes online`:'Network activation in progress'}</strong><small>{readiness.active_heroes||0} verified Heroes · {readiness.recruiting_candidates||0} candidates · {readiness.passed_checks||0}/{readiness.verification_checks||0} checks passed</small></div></div>}
    {open&&<div className="sosx-backdrop" onMouseDown={()=>setOpen(false)}><section className="sosx-sheet" onMouseDown={e=>e.stopPropagation()}><div className="sosx-handle"/><header><div><span>SHIELD MEMBERSHIP</span><h2>Roadside confidence,<br/>built around you.</h2><p>Priority matching, member pricing, and included roadside coverage with live plan status.</p></div><button onClick={()=>setOpen(false)} aria-label="Close Shield">×</button></header>{loading&&<div className="sosx-progress">Connecting to Shield…</div>}{paymentHealth?.ready===false&&<div className="sosx-error">Secure enrollment is temporarily offline because the Stripe server credential is not configured. Plans remain visible; no charge can be attempted.</div>}{error&&<div className="sosx-error">{error}</div>}{notice&&<div className="sosx-notice">{notice}</div>}<div className="sosx-plans">{plans.map((plan,index)=>{const active=currentPlan===plan.id;const featured=!currentPlan&&index===1;const disabled=loading||active||paymentHealth?.ready===false;return <article key={plan.id} className={active?'active':featured?'featured':''}>{active?<b>YOUR PLAN</b>:featured&&<b>MOST POPULAR</b>}<small>S.O.S. {plan.name.toUpperCase()}</small><h3>{plan.name}</h3><p>{plan.tagline}</p><div className="sosx-price"><strong>${Number(plan.monthly_price).toFixed(2)}</strong><span>/month</span></div><ul>{(plan.features||[]).map(feature=><li key={feature}>✓ {feature}</li>)}</ul><button disabled={disabled} onClick={()=>checkout(plan)}>{active?'Active':paymentHealth?.ready===false?'Payments offline':`Choose ${plan.name}`}</button></article>})}</div>{subscription?.current_period_end&&<p className="sosx-period">Current period ends {new Date(subscription.current_period_end).toLocaleDateString()}.</p>}<p className="sosx-truth">Membership does not replace emergency services. For a life-threatening emergency, call 911.</p></section></div>}
  </>;
}
