'use client';

import React,{useEffect,useMemo,useState}from'react';
import{createClient}from'@supabase/supabase-js';
const SB='https://cxdqkjvtpilvouwtbgdy.supabase.co';
const SK='sb_publishable_x_QDbPwZuhbqB1bd58MLvg_ADSiFODN';
const realtime=createClient(SB,SK,{auth:{persistSession:false,autoRefreshToken:false}});
const stored=()=>{try{const s=JSON.parse(localStorage.getItem('sos_session'));if(!s?.access_token||!s?.user)return null;if(s.expires_at&&s.expires_at<Date.now()/1000)return null;return s}catch{return null}};
const request=async(path,{method='GET',token,body}={})=>{const r=await fetch(`${SB}${path}`,{method,headers:{apikey:SK,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||d?.error_description||d?.error||'Request failed');return d};
const label=type=>({message:'MESSAGE',mission_offer:'MISSION OFFER',mission_accepted:'MISSION',hero_en_route:'TRACKING',hero_arrived:'ARRIVAL',mission_complete:'COMPLETE',hero_reassigned:'REASSIGNMENT',hero_timeout:'RELIABILITY',payment_received:'PAYMENT',payout_sent:'PAYOUT',system:'SYSTEM'}[type]||String(type||'UPDATE').replaceAll('_',' ').toUpperCase());

export default function SOSNotificationInboxHost(){
 const[userId,setUserId]=useState(''),[items,setItems]=useState([]),[open,setOpen]=useState(false),[error,setError]=useState('');
 const load=async(uid=userId)=>{const s=stored();if(!s||!uid)return;const rows=await request(`/rest/v1/sos_notifications?user_id=eq.${uid}&select=id,user_id,type,title,body,data,channel,read,read_at,created_at&order=created_at.desc&limit=100`,{token:s.access_token});setItems(rows||[])};
 useEffect(()=>{let disposed=false;let channel=null;const connect=async()=>{const s=stored();if(!s)return;const us=await request(`/rest/v1/sos_users?auth_id=eq.${s.user.id}&select=id&limit=1`,{token:s.access_token});const u=us?.[0];if(!u||disposed)return;setUserId(u.id);await load(u.id);realtime.realtime.setAuth(s.access_token);channel=realtime.channel(`sos-notification-inbox:${u.id}`).on('postgres_changes',{event:'*',schema:'public',table:'sos_notifications',filter:`user_id=eq.${u.id}`},()=>load(u.id).catch(()=>{})).subscribe()};connect().catch(()=>{});return()=>{disposed=true;if(channel)realtime.removeChannel(channel)}},[]);
 const unread=useMemo(()=>items.filter(x=>!x.read).length,[items]);
 const mark=async(ids)=>{const s=stored();if(!s)return;setError('');try{await request('/rest/v1/rpc/sos_mark_notifications_read',{method:'POST',token:s.access_token,body:{p_notification_ids:ids?.length?ids:null}});await load()}catch(e){setError(e.message)}};
 const openNotice=async item=>{if(!item.read)await mark([item.id]);setOpen(false)};
 if(!userId)return null;
 return <>
  <button type="button" onClick={()=>setOpen(true)} style={{position:'fixed',right:16,top:76,zIndex:1650,border:'1px solid rgba(255,255,255,.13)',borderRadius:999,padding:'9px 12px',background:'rgba(17,27,37,.95)',color:'#fff',fontSize:9,fontWeight:900,letterSpacing:'.08em',boxShadow:'0 12px 34px rgba(0,0,0,.3)',backdropFilter:'blur(12px)'}}>INBOX{unread>0?<span style={{marginLeft:7,padding:'2px 6px',borderRadius:999,background:'#ff6b35'}}>{unread>99?'99+':unread}</span>:null}</button>
  {open&&<div role="dialog" aria-modal="true" style={{position:'fixed',inset:0,zIndex:2350,background:'rgba(3,8,15,.56)',display:'grid',justifyItems:'end',backdropFilter:'blur(7px)'}}><section style={{width:'min(430px,94vw)',height:'100dvh',background:'#f7f9fc',boxShadow:'-24px 0 80px rgba(0,0,0,.4)',display:'grid',gridTemplateRows:'auto 1fr'}}>
   <header style={{padding:'18px 16px 14px',background:'#101922',color:'#fff'}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:10}}><div><small style={{fontSize:9,fontWeight:900,letterSpacing:'.13em',color:'#ff8a5b'}}>S.O.S. INBOX</small><h2 style={{fontSize:23,margin:'4px 0 0'}}>Mission updates, kept.</h2></div><button type="button" onClick={()=>setOpen(false)} style={{width:36,height:36,border:0,borderRadius:12,background:'rgba(255,255,255,.09)',color:'#fff',fontSize:20}}>×</button></div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:13}}><span style={{fontSize:10,color:'rgba(255,255,255,.62)'}}>{unread} unread · {items.length} recent</span>{unread>0&&<button type="button" onClick={()=>mark()} style={{border:0,background:'transparent',color:'#ffad87',fontSize:9,fontWeight:900}}>MARK ALL READ</button>}</div></header>
   <div style={{overflowY:'auto',padding:12}}>{error&&<div style={{padding:10,borderRadius:12,background:'#fff0f0',color:'#b42318',fontSize:10,marginBottom:9}}>{error}</div>}{items.length===0?<div style={{padding:'60px 18px',textAlign:'center',color:'#7c8798'}}><strong style={{display:'block',fontSize:17,color:'#334155'}}>No updates yet.</strong><span style={{fontSize:11,display:'block',marginTop:5}}>Offers, tracking, messages, payments and mission changes will stay here.</span></div>:items.map(item=><button type="button" key={item.id} onClick={()=>openNotice(item)} style={{width:'100%',textAlign:'left',border:'1px solid #e4e9f0',borderRadius:16,padding:'12px 13px',background:item.read?'#fff':'#fff3ed',marginBottom:8,cursor:'pointer',boxShadow:item.read?'none':'0 8px 24px rgba(255,107,53,.08)'}}><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'flex-start'}}><div><small style={{fontSize:8,fontWeight:900,letterSpacing:'.1em',color:item.read?'#8b96a8':'#e85826'}}>{label(item.type)}</small><strong style={{display:'block',fontSize:13,color:'#172033',marginTop:3}}>{item.title}</strong></div>{!item.read&&<i style={{width:8,height:8,borderRadius:'50%',background:'#ff6b35',flex:'0 0 auto',marginTop:4}}/>}</div><span style={{display:'block',fontSize:10.5,lineHeight:1.48,color:'#67758a',marginTop:5}}>{item.body}</span><small style={{display:'block',fontSize:8,color:'#9aa4b5',marginTop:7}}>{new Date(item.created_at).toLocaleString([],{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</small></button>)}</div>
  </section></div>}
 </>;
}
