'use client';

import React,{useEffect,useMemo,useState}from'react';

const SB='https://cxdqkjvtpilvouwtbgdy.supabase.co';
const SK='sb_publishable_x_QDbPwZuhbqB1bd58MLvg_ADSiFODN';
const headers=token=>({apikey:SK,Authorization:`Bearer ${token}`,'Content-Type':'application/json'});
const stored=()=>{try{const s=JSON.parse(localStorage.getItem('sos_ops_session'));return s?.access_token&&s?.user?s:null}catch{return null}};
const api=async(path,{method='GET',token,body}={})=>{const r=await fetch(`${SB}${path}`,{method,headers:headers(token||SK),body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||d?.error_description||d?.error||'Request failed');return d};
const pretty=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const stages=['prospect','qualified','contacted','screening','training','account_setup','test_mission','approved','rejected','withdrawn'];
const outreach=['not_queued','queued','in_progress','sent','responded','failed','paused'];
const checkStatuses=['pending','submitted','under_review','passed','failed','waived','expired'];

export default function SOSOperationsCommand(){
 const[session,setSession]=useState(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[snapshot,setSnapshot]=useState({counts:{},candidates:[],tickets:[]}),[tab,setTab]=useState('candidates'),[selected,setSelected]=useState(null),[notes,setNotes]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=async ss=>{const s=ss||session||stored();if(!s)return;setError('');const data=await api('/rest/v1/rpc/sos_ops_snapshot',{method:'POST',token:s.access_token,body:{}});setSnapshot(data||{counts:{},candidates:[],tickets:[]});if(selected?.id){const next=(data?.candidates||[]).find(x=>x.id===selected.id)||(data?.tickets||[]).find(x=>x.id===selected.id);if(next)setSelected(next)}};
 useEffect(()=>{const s=stored();if(s){setSession(s);load(s).catch(e=>{setError(e.message);if(/operator|jwt|token|auth/i.test(e.message))localStorage.removeItem('sos_ops_session')})}},[]);
 const login=async e=>{e.preventDefault();setBusy('login');setError('');try{const s=await api('/auth/v1/token?grant_type=password',{method:'POST',body:{email:email.trim().toLowerCase(),password}});localStorage.setItem('sos_ops_session',JSON.stringify(s));setSession(s);await load(s)}catch(e){setError(e.message)}finally{setBusy('')}};
 const logout=()=>{localStorage.removeItem('sos_ops_session');setSession(null);setSnapshot({counts:{},candidates:[],tickets:[]});setSelected(null)};
 const updateCandidate=async(nextStage,nextOutreach)=>{if(!selected||busy)return;setBusy('candidate');setError('');setNotice('');try{await api('/rest/v1/rpc/sos_ops_update_candidate',{method:'POST',token:session.access_token,body:{p_candidate_id:selected.id,p_pipeline_stage:nextStage||selected.pipeline_stage,p_outreach_status:nextOutreach||selected.outreach_status,p_notes:notes||selected.notes||null,p_next_action_at:selected.next_action_at||null}});setNotice('Candidate pipeline updated.');await load()}catch(e){setError(e.message)}finally{setBusy('')}};
 const reviewCheck=async(type,status)=>{if(!selected||busy)return;setBusy(type);setError('');setNotice('');try{await api('/rest/v1/rpc/sos_ops_review_verification_check',{method:'POST',token:session.access_token,body:{p_hero_id:selected.source_hero_id,p_check_type:type,p_status:status,p_notes:notes||null}});setNotice(`${pretty(type)} marked ${pretty(status)}.`);await load()}catch(e){setError(e.message)}finally{setBusy('')}};
 const updateTicket=async status=>{if(!selected||busy)return;setBusy('ticket');setError('');setNotice('');try{await api('/rest/v1/rpc/sos_ops_update_support_ticket',{method:'POST',token:session.access_token,body:{p_ticket_id:selected.id,p_status:status}});setNotice(`Ticket marked ${pretty(status)}.`);await load()}catch(e){setError(e.message)}finally{setBusy('')}};
 const candidates=snapshot.candidates||[],tickets=snapshot.tickets||[];
 const verification=useMemo(()=>candidates.filter(c=>Object.values(c.checks||{}).some(v=>['pending','submitted','under_review'].includes(String(v)))),[candidates]);
 const list=tab==='support'?tickets:tab==='verification'?verification:candidates;
 if(!session)return <main className="soso-auth"><section><div className="soso-mark">SOS</div><span>OPERATIONS COMMAND</span><h1>Activate the network.<br/>Work the truth.</h1><p>Candidate activation, verification review, and citizen support—without pretending stored Hero records are live supply.</p></section><form onSubmit={login}><h2>Operator sign in</h2><p>Only approved marketplace operators can enter this workspace.</p><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input required type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="soso-error">{error}</div>}<button disabled={busy==='login'}>{busy==='login'?'Connecting…':'Enter S.O.S. Operations'}</button><a href="/hero">← Hero Command</a></form></main>;
 return <div className="soso-app"><header><div><div className="soso-mark">SOS</div><span><strong>S.O.S.</strong><small>OPERATIONS COMMAND</small></span></div><div><button onClick={()=>load().catch(e=>setError(e.message))}>Refresh</button><button onClick={logout}>Sign out</button></div></header><main><section className="soso-hero"><div><span>NETWORK ACTIVATION</span><h1>Turn qualified records<br/>into real supply.</h1><p>The console shows what is stored, what is verified, what is authenticated, and what still needs human action.</p></div><div className="soso-metrics"><div><strong>{snapshot.counts?.candidates||0}</strong><span>Candidates</span></div><div><strong>{snapshot.counts?.qualified||0}</strong><span>Qualified</span></div><div><strong>{snapshot.counts?.verification_pending||0}</strong><span>Checks to review</span></div><div><strong>{snapshot.counts?.tickets_open||0}</strong><span>Open support</span></div></div></section>{error&&<div className="soso-error">{error}</div>}{notice&&<div className="soso-notice">{notice}</div>}<nav className="soso-tabs"><button className={tab==='candidates'?'active':''} onClick={()=>{setTab('candidates');setSelected(null)}}>Candidates <b>{candidates.length}</b></button><button className={tab==='verification'?'active':''} onClick={()=>{setTab('verification');setSelected(null)}}>Verification <b>{verification.length}</b></button><button className={tab==='support'?'active':''} onClick={()=>{setTab('support');setSelected(null)}}>Support <b>{tickets.length}</b></button></nav><section className="soso-work"><div className="soso-list">{list.length===0?<div className="soso-empty">Nothing in this queue.</div>:list.map(item=><button key={item.id} className={selected?.id===item.id?'active':''} onClick={()=>{setSelected(item);setNotes(item.notes||'')}}>{tab==='support'?<><div><span>{item.ticket_number}</span><strong>{item.subject}</strong><small>{pretty(item.priority)} · {pretty(item.status)} · {item.email}</small></div><em>{pretty(item.category)}</em></>:<><div><span>{item.auth_linked?'AUTH LINKED':'CLAIM NEEDED'}</span><strong>{item.first_name} {item.last_name}</strong><small>{item.email} · {pretty(item.pipeline_stage)} · {pretty(item.outreach_status)}</small></div><em className={item.verification_status}>{pretty(item.verification_status)}</em></>}</button>)}</div><aside>{!selected?<div className="soso-empty detail">Select an item to work.</div>:tab==='support'?<SupportDetail item={selected} busy={busy} update={updateTicket}/>:<CandidateDetail item={selected} notes={notes} setNotes={setNotes} busy={busy} updateCandidate={updateCandidate} reviewCheck={reviewCheck} verificationOnly={tab==='verification'}/>}</aside></section></main></div>;
}

function CandidateDetail({item,notes,setNotes,busy,updateCandidate,reviewCheck,verificationOnly}){return <><div className="soso-detail-head"><span>{item.auth_linked?'AUTHENTICATED HERO ACCOUNT LINKED':'ACCOUNT CLAIM STILL REQUIRED'}</span><h2>{item.first_name} {item.last_name}</h2><p>{item.email} · {item.phone||'No phone'} · {item.target_zone||'No zone'}</p></div><div className="soso-facts"><div><span>HERO STATUS</span><strong>{pretty(item.verification_status)}</strong></div><div><span>PIPELINE</span><strong>{pretty(item.pipeline_stage)}</strong></div><div><span>OUTREACH</span><strong>{pretty(item.outreach_status)}</strong></div><div><span>PAYOUT</span><strong>{item.stripe_connect_id?'Connected':'Not connected'}</strong></div></div><div className="soso-checks"><span>VERIFICATION CHECKS</span>{Object.entries(item.checks||{}).sort().map(([type,status])=><article key={type}><div><strong>{pretty(type)}</strong><small>{pretty(status)}</small></div>{['pending','submitted','under_review'].includes(String(status))&&<div><button disabled={Boolean(busy)} onClick={()=>reviewCheck(type,'under_review')}>Review</button><button className="fail" disabled={Boolean(busy)} onClick={()=>reviewCheck(type,'failed')}>Fail</button><button className="pass" disabled={Boolean(busy)} onClick={()=>reviewCheck(type,'passed')}>Pass</button></div>}</article>)}</div><label className="soso-notes">OPERATOR NOTES<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Screening notes, verification context, follow-up…"/></label>{!verificationOnly&&<><div className="soso-selects"><label>Pipeline<select value={item.pipeline_stage} onChange={e=>updateCandidate(e.target.value,null)}>{stages.map(s=><option key={s} value={s}>{pretty(s)}</option>)}</select></label><label>Outreach<select value={item.outreach_status} onChange={e=>updateCandidate(null,e.target.value)}>{outreach.map(s=><option key={s} value={s}>{pretty(s)}</option>)}</select></label></div><button className="soso-primary" disabled={Boolean(busy)} onClick={()=>updateCandidate(null,null)}>Save notes / status</button></>}</>}
function SupportDetail({item,busy,update}){return <><div className="soso-detail-head"><span>{item.ticket_number} · {pretty(item.priority)}</span><h2>{item.subject}</h2><p>{[item.first_name,item.last_name].filter(Boolean).join(' ')||item.email} · {item.email}</p></div><div className="soso-ticket-body"><span>{pretty(item.category)}</span><p>{item.description}</p>{item.mission_id&&<small>Mission: {item.mission_id}</small>}</div><div className="soso-ticket-actions">{['reviewing','waiting_customer','resolved','closed'].map(s=><button key={s} disabled={Boolean(busy)||item.status===s} className={s==='resolved'?'pass':s==='closed'?'fail':''} onClick={()=>update(s)}>{pretty(s)}</button>)}</div></>}
