'use client';

import {useEffect,useState} from 'react';
import styles from './SOSPasswordRecoveryHost.module.css';

const SB='https://cxdqkjvtpilvouwtbgdy.supabase.co';
const SK='sb_publishable_x_QDbPwZuhbqB1bd58MLvg_ADSiFODN';
const recovery=()=>{try{const value=JSON.parse(localStorage.getItem('sos_password_recovery'));if(!value?.access_token)return null;if(value.expires_at&&value.expires_at<Date.now()/1000){localStorage.removeItem('sos_password_recovery');return null}return value}catch{return null}};

export default function SOSPasswordRecoveryHost(){
 const[visible,setVisible]=useState(false),[open,setOpen]=useState(false),[mode,setMode]=useState('request'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{const detect=()=>{const path=window.location.pathname;const login=Boolean(document.querySelector('.sos2-auth-panel,.shc-auth-card'))||path.startsWith('/hero/claim');setVisible(login&&['/app','/hero','/hero/claim'].some(prefix=>path.startsWith(prefix)))};detect();const observer=new MutationObserver(detect);observer.observe(document.body,{subtree:true,childList:true});const start=()=>{if(recovery()){setMode('update');setOpen(true);setVisible(false);setError('');setNotice('Recovery link verified. Choose a new password for this S.O.S. account.')}};start();window.addEventListener('sos-password-recovery',start);return()=>{observer.disconnect();window.removeEventListener('sos-password-recovery',start)}},[]);
 const request=async event=>{event.preventDefault();if(busy)return;setBusy(true);setError('');setNotice('');try{const normalized=email.trim().toLowerCase();if(!normalized)throw new Error('Enter the email on your S.O.S. account.');const path=window.location.pathname.startsWith('/hero')?'/hero':'/app';const redirect=`https://thesuperherosonstandby.com${path}`;const r=await fetch(`${SB}/auth/v1/recover?redirect_to=${encodeURIComponent(redirect)}`,{method:'POST',headers:{apikey:SK,'Content-Type':'application/json'},body:JSON.stringify({email:normalized})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.msg||d?.error_description||d?.message||d?.error||'Password reset email could not be sent');setNotice('Password reset email sent. Open the recovery link in that email to choose a new password.')}catch(e){setError(e.message||'Password reset email could not be sent')}finally{setBusy(false)}};
 const update=async event=>{event.preventDefault();if(busy)return;setBusy(true);setError('');setNotice('');try{if(password.length<8)throw new Error('Use at least 8 characters for the new password.');if(password!==confirm)throw new Error('The new passwords do not match.');const token=recovery();if(!token)throw new Error('Recovery session expired. Request a new reset email.');const r=await fetch(`${SB}/auth/v1/user`,{method:'PUT',headers:{apikey:SK,Authorization:`Bearer ${token.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({password})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.msg||d?.error_description||d?.message||d?.error||'Password could not be updated');localStorage.removeItem('sos_password_recovery');setNotice('Password updated. Sign in with your new password.');window.setTimeout(()=>{setOpen(false);setMode('request');setPassword('');setConfirm('')},900)}catch(e){setError(e.message||'Password could not be updated')}finally{setBusy(false)}};
 if(!open&&!visible)return null;
 return <>{visible&&!open&&<button className={styles.launch} onClick={()=>{setMode('request');setOpen(true);setError('');setNotice('')}}>Forgot password?</button>}{open&&<div className={styles.backdrop}><section className={styles.card} role="dialog" aria-modal="true"><button className={styles.close} onClick={()=>setOpen(false)}>×</button><div className={styles.mark}>SOS</div><span>{mode==='request'?'ACCOUNT RECOVERY':'SET NEW PASSWORD'}</span><h2>{mode==='request'?'Recover S.O.S.':'Choose a new password.'}</h2><p>{mode==='request'?'We’ll send a secure recovery link to the email on your account.':'This recovery session came from your password-reset email.'}</p>{mode==='request'?<form onSubmit={request}><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label>{error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}<button className={styles.primary} disabled={busy}>{busy?'Sending…':'Send reset link'}</button></form>:<form onSubmit={update}><label>New password<input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></label><label>Confirm password<input required minLength={8} type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password"/></label>{error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}<button className={styles.primary} disabled={busy}>{busy?'Updating…':'Update password'}</button></form>}<small>Recovery changes only your login password. Hero approval, verification, missions, and payout state remain unchanged.</small></section></div>}</>;
}
