'use client';

import React,{useEffect,useMemo,useState}from'react';

const SB='https://cxdqkjvtpilvouwtbgdy.supabase.co';
const SK='sb_publishable_x_QDbPwZuhbqB1bd58MLvg_ADSiFODN';
const session=()=>{try{if(typeof window==='undefined')return null;const s=JSON.parse(localStorage.getItem('sos_session'));return s?.access_token&&s?.user?s:null}catch{return null}};
const headers=token=>({apikey:SK,Authorization:`Bearer ${token}`,'Content-Type':'application/json'});
const api=async(path,{method='GET',token,body}={})=>{const r=await fetch(`${SB}${path}`,{method,headers:headers(token),body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||d?.error||'Request failed');return d};
const emptyVehicle={id:null,make:'',model:'',year:'',trim:'',color:'',plate:'',vin:'',is_ev:false,is_default:false,notes:''};
const categories=[['account','Account'],['vehicle','Vehicle'],['payment','Payment'],['membership','Membership'],['mission','Mission'],['safety','Safety'],['technical','Technical'],['other','Other']];

export default function SOSProfileToolsHost(){
 const[tool,setTool]=useState(null),[vehicles,setVehicles]=useState([]),[vehicle,setVehicle]=useState(emptyVehicle),[payments,setPayments]=useState([]),[health,setHealth]=useState(null),[tickets,setTickets]=useState([]),[support,setSupport]=useState({category:'account',priority:'normal',subject:'',description:''}),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const s=useMemo(()=>session(),[tool]);
 const close=()=>{setTool(null);setVehicle(emptyVehicle);setError('');setNotice('')};
 const loadVehicles=async()=>{const ss=session();if(!ss)return;const rows=await api('/rest/v1/sos_vehicles?select=id,make,model,year,trim,color,plate,vin,is_ev,is_default,notes,created_at&order=is_default.desc,created_at.asc',{token:ss.access_token});setVehicles(rows||[])};
 const loadPayments=async()=>{const ss=session();if(!ss)return;const [rows,h]=await Promise.all([api('/rest/v1/sos_payments?select=id,mission_id,amount,platform_fee,hero_payout,tip,refund_amount,payment_status,escrow_status,settlement_type,cancellation_fee,created_at,updated_at&order=created_at.desc&limit=30',{token:ss.access_token}),fetch(`${SB}/functions/v1/marketplace-payments-health`,{headers:{apikey:SK},cache:'no-store'}).then(r=>r.json()).catch(()=>null)]);setPayments(rows||[]);setHealth(h)};
 const loadTickets=async()=>{const ss=session();if(!ss)return;const rows=await api('/rest/v1/sos_support_tickets?select=id,ticket_number,category,priority,subject,status,created_at,updated_at&order=created_at.desc&limit=20',{token:ss.access_token});setTickets(rows||[])};
 useEffect(()=>{const capture=e=>{const button=e.target?.closest?.('.sos2-profile-menu button,.sos2-membership button');if(!button)return;const label=String(button.querySelector?.('strong')?.textContent||button.textContent||'').trim();if(label==='Vehicles'){e.preventDefault();e.stopPropagation();setTool('vehicles')}else if(label==='Payment methods'){e.preventDefault();e.stopPropagation();setTool('payments')}else if(label==='Shield membership'||label==='Explore Shield'){e.preventDefault();e.stopPropagation();window.dispatchEvent(new Event('sos:open-shield'))}else if(label==='Safety & support'){e.preventDefault();e.stopPropagation();setTool('support')}};document.addEventListener('click',capture,true);return()=>document.removeEventListener('click',capture,true)},[]);
 useEffect(()=>{if(tool==='vehicles')loadVehicles().catch(e=>setError(e.message));if(tool==='payments')loadPayments().catch(e=>setError(e.message));if(tool==='support')loadTickets().catch(e=>setError(e.message))},[tool]);
 const saveVehicle=async()=>{const ss=session();if(!ss||busy)return;setBusy('vehicle');setError('');setNotice('');try{await api('/rest/v1/rpc/sos_upsert_vehicle',{method:'POST',token:ss.access_token,body:{p_vehicle_id:vehicle.id||null,p_make:vehicle.make,p_model:vehicle.model,p_year:vehicle.year?Number(vehicle.year):null,p_trim:vehicle.trim||null,p_color:vehicle.color||null,p_plate:vehicle.plate||null,p_vin:vehicle.vin||null,p_is_ev:Boolean(vehicle.is_ev),p_is_default:Boolean(vehicle.is_default),p_notes:vehicle.notes||null}});setVehicle(emptyVehicle);await loadVehicles();setNotice('Vehicle saved.')}catch(e){setError(e.message)}finally{setBusy('')}};
 const removeVehicle=async id=>{const ss=session();if(!ss||busy||!window.confirm('Remove this vehicle from your S.O.S. account?'))return;setBusy(id);setError('');try{await api('/rest/v1/rpc/sos_delete_vehicle',{method:'POST',token:ss.access_token,body:{p_vehicle_id:id}});await loadVehicles();if(vehicle.id===id)setVehicle(emptyVehicle);setNotice('Vehicle removed.')}catch(e){setError(e.message)}finally{setBusy('')}};
 const makeDefault=async id=>{const ss=session();if(!ss||busy)return;setBusy(id);setError('');try{await api('/rest/v1/rpc/sos_set_default_vehicle',{method:'POST',token:ss.access_token,body:{p_vehicle_id:id}});await loadVehicles();setNotice('Default vehicle updated.')}catch(e){setError(e.message)}finally{setBusy('')}};
 const submitSupport=async()=>{const ss=session();if(!ss||busy)return;setBusy('support');setError('');setNotice('');try{const rows=await api('/rest/v1/rpc/sos_open_support_ticket',{method:'POST',token:ss.access_token,body:{p_category:support.category,p_subject:support.subject,p_description:support.description,p_priority:support.priority,p_mission_id:null}});const row=Array.isArray(rows)?rows[0]:rows;setSupport({category:'account',priority:'normal',subject:'',description:''});await loadTickets();setNotice(row?.ticket_number?`Support case ${row.ticket_number} opened.`:'Support case opened.')}catch(e){setError(e.message)}finally{setBusy('')}};
 if(!tool)return null;
 return <div className="sosp-backdrop" role="dialog" aria-modal="true" aria-label="S.O.S. account tools" onMouseDown={close}><section className="sosp-sheet" onMouseDown={e=>e.stopPropagation()}><div className="sosp-handle"/><header><div><small>CITIZEN ACCOUNT</small><h2>{tool==='vehicles'?'Your vehicles':tool==='payments'?'Payments': 'Safety & support'}</h2><p>{tool==='vehicles'?'Save the vehicles you actually drive so roadside requests can move faster.':tool==='payments'?'Mission charges stay attached to your live S.O.S. payment ledger. Cards are handled by Stripe, not stored in this app.':'Open a real support case and track its current status.'}</p></div><button onClick={close} aria-label="Close">×</button></header>{error&&<div className="sosp-error">{error}</div>}{notice&&<div className="sosp-notice">{notice}</div>}
 {tool==='vehicles'&&<><div className="sosp-vehicle-grid">{vehicles.map(v=><article key={v.id} className={v.is_default?'default':''}><div className="sosp-vehicle-icon">{v.is_ev?'EV':'CAR'}</div><div><small>{v.is_default?'DEFAULT VEHICLE':'SAVED VEHICLE'}</small><strong>{[v.year,v.make,v.model].filter(Boolean).join(' ')}</strong><span>{[v.trim,v.color,v.plate].filter(Boolean).join(' · ')||'Vehicle details saved'}</span></div><div className="sosp-actions"><button onClick={()=>setVehicle({...emptyVehicle,...v,year:v.year||''})}>Edit</button>{!v.is_default&&<button onClick={()=>makeDefault(v.id)}>Make default</button>}<button className="danger" onClick={()=>removeVehicle(v.id)}>Remove</button></div></article>)}</div>{vehicles.length===0&&<div className="sosp-empty"><b>CAR</b><strong>No saved vehicles yet.</strong><span>Add the vehicle you use most often.</span></div>}<div className="sosp-form"><label>Make<input value={vehicle.make} onChange={e=>setVehicle({...vehicle,make:e.target.value})} placeholder="Toyota"/></label><label>Model<input value={vehicle.model} onChange={e=>setVehicle({...vehicle,model:e.target.value})} placeholder="Camry"/></label><label>Year<input type="number" min="1900" max={new Date().getFullYear()+2} value={vehicle.year} onChange={e=>setVehicle({...vehicle,year:e.target.value})} placeholder="2024"/></label><label>Trim<input value={vehicle.trim} onChange={e=>setVehicle({...vehicle,trim:e.target.value})} placeholder="XSE"/></label><label>Color<input value={vehicle.color} onChange={e=>setVehicle({...vehicle,color:e.target.value})} placeholder="Black"/></label><label>Plate<input value={vehicle.plate} onChange={e=>setVehicle({...vehicle,plate:e.target.value})} placeholder="ABC123"/></label><label className="wide">VIN <span>(optional)</span><input value={vehicle.vin} onChange={e=>setVehicle({...vehicle,vin:e.target.value})} placeholder="Vehicle identification number"/></label><label className="check"><input type="checkbox" checked={vehicle.is_ev} onChange={e=>setVehicle({...vehicle,is_ev:e.target.checked})}/> Electric vehicle</label><label className="check"><input type="checkbox" checked={vehicle.is_default} onChange={e=>setVehicle({...vehicle,is_default:e.target.checked})}/> Make default</label><label className="wide">Notes<textarea value={vehicle.notes} onChange={e=>setVehicle({...vehicle,notes:e.target.value})} placeholder="Anything a Hero should know about this vehicle"/></label><button className="sosp-primary wide" disabled={busy==='vehicle'||!vehicle.make.trim()||!vehicle.model.trim()} onClick={saveVehicle}>{busy==='vehicle'?'Saving…':vehicle.id?'Update vehicle':'Add vehicle'}</button>{vehicle.id&&<button className="sosp-secondary wide" onClick={()=>setVehicle(emptyVehicle)}>Cancel edit</button>}</div></>}
 {tool==='payments'&&<><div className={`sosp-payment-health ${health?.ready?'ready':'offline'}`}><b>{health?.ready?'SECURE PAYMENTS ONLINE':'PAYMENTS OFFLINE'}</b><strong>{health?.ready?'Stripe authorization is available.':'No charge can be attempted right now.'}</strong><span>{health?.message||'Payment runtime status is unavailable.'}</span></div><div className="sosp-payment-info"><strong>How payment methods work</strong><p>You choose or enter a payment method during secure mission authorization. S.O.S. stores the payment state and Stripe reference—not your full card number. There is no fake in-app card wallet.</p></div><div className="sosp-ledger">{payments.map(p=><article key={p.id}><div><small>{String(p.settlement_type||'service').replaceAll('_',' ').toUpperCase()}</small><strong>${Number(p.amount||0).toFixed(2)}</strong><span>{new Date(p.created_at).toLocaleString()}</span></div><em>{String(p.payment_status||'pending').replaceAll('_',' ')}</em></article>)}</div>{payments.length===0&&<div className="sosp-empty"><b>$</b><strong>No payment history yet.</strong><span>Authorized mission payments will appear here.</span></div>}</>}
 {tool==='support'&&<><div className="sosp-form"><label>Category<select value={support.category} onChange={e=>setSupport({...support,category:e.target.value})}>{categories.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Priority<select value={support.priority} onChange={e=>setSupport({...support,priority:e.target.value})}><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><label className="wide">Subject<input value={support.subject} onChange={e=>setSupport({...support,subject:e.target.value})} placeholder="What do you need help with?"/></label><label className="wide">Details<textarea value={support.description} onChange={e=>setSupport({...support,description:e.target.value})} placeholder="Describe the issue and what you need S.O.S. to do."/></label><button className="sosp-primary wide" disabled={busy==='support'||support.subject.trim().length<3||support.description.trim().length<5} onClick={submitSupport}>{busy==='support'?'Opening case…':'Open support case'}</button></div><div className="sosp-ticket-list">{tickets.map(t=><article key={t.id}><div><small>{t.ticket_number}</small><strong>{t.subject}</strong><span>{t.category} · {new Date(t.created_at).toLocaleString()}</span></div><em className={t.status}>{t.status.replaceAll('_',' ')}</em></article>)}</div>{tickets.length===0&&<div className="sosp-empty"><b>?</b><strong>No support cases.</strong><span>Open a case above when you need operations help.</span></div>}<p className="sosp-emergency">S.O.S. is not emergency services. For a life-threatening emergency, call 911.</p></>}
 </section></div>;
}
