'use client';

import React,{useEffect,useState}from'react';
import { sosSupabase } from '../lib/sosSupabaseClient';

export default function SOSRecoveryHost({audience='customer'}){
  const[visible,setVisible]=useState(false);const[open,setOpen]=useState(false);const[email,setEmail]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');
  useEffect(()=>{try{const stored=JSON.parse(localStorage.getItem('sos_session'));setVisible(!stored?.access_token)}catch{setVisible(true)}},[]);
  if(!visible)return null;
  const submit=async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');setNotice('');try{const redirectTo=`https://thesuperherosonstandby.com/auth/reset?portal=${audience==='hero'?'hero':'app'}`;const{error:resetError}=await sosSupabase.auth.resetPasswordForEmail(email.trim(),{redirectTo});if(resetError)throw resetError;setNotice('Password reset email sent. Use the secure link to choose a new password.')}catch(e){setError(e?.message||'Password reset could not be started.')}finally{setBusy(false)}};
  return <><button type="button" onClick={()=>setOpen(true)} style={{position:'fixed',right:16,bottom:16,zIndex:2400,border:'1px solid rgba(255,255,255,.14)',borderRadius:999,padding:'10px 14px',background:'rgba(8,13,21,.92)',color:'#fff',fontSize:11,fontWeight:800,boxShadow:'0 12px 35px rgba(0,0,0,.3)'}}>Forgot password?</button>{open&&<div onMouseDown={()=>setOpen(false)} style={{position:'fixed',inset:0,zIndex:2600,background:'rgba(0,0,0,.72)',backdropFilter:'blur(12px)',display:'grid',placeItems:'center',padding:18}}><form onSubmit={submit} onMouseDown={e=>e.stopPropagation()} style={{width:'min(440px,100%)',borderRadius:24,padding:22,background:'#0c1624',border:'1px solid rgba(255,138,76,.2)',color:'#fff',boxShadow:'0 30px 90px rgba(0,0,0,.5)'}}><div style={{display:'flex',justifyContent:'space-between',gap:16}}><div><small style={{color:'#ffbd63',fontWeight:900,letterSpacing:'.12em'}}>ACCOUNT RECOVERY</small><h2 style={{margin:'8px 0 4px',fontSize:28}}>Reset your S.O.S. password</h2><p style={{margin:0,color:'rgba(235,241,248,.6)',fontSize:12,lineHeight:1.5}}>Use the email attached to your S.O.S. account. The reset link returns to the correct portal.</p></div><button type="button" onClick={()=>setOpen(false)} style={{width:38,height:38,borderRadius:12,border:'1px solid rgba(255,255,255,.12)',background:'transparent',color:'#fff',fontSize:20}}>×</button></div><label style={{display:'grid',gap:6,marginTop:18,fontSize:10,color:'#ffbd63',fontWeight:800}}>EMAIL<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} style={{height:48,borderRadius:13,border:'1px solid rgba(255,255,255,.12)',background:'#08111d',color:'#fff',padding:'0 12px'}}/></label>{error&&<div style={{marginTop:10,padding:10,borderRadius:12,background:'rgba(239,68,68,.12)',color:'#ff9c92',fontSize:11}}>{error}</div>}{notice&&<div style={{marginTop:10,padding:10,borderRadius:12,background:'rgba(33,199,122,.12)',color:'#78e8ad',fontSize:11}}>{notice}</div>}<button disabled={busy} style={{width:'100%',height:48,marginTop:14,border:0,borderRadius:13,background:'#ff7a42',color:'#fff',fontWeight:900}}>{busy?'Sending…':'Send secure reset link'}</button></form></div>}</>;
}
