'use client';

import React,{useEffect,useMemo,useState}from'react';

const SB='https://cxdqkjvtpilvouwtbgdy.supabase.co';
const SK='sb_publishable_x_QDbPwZuhbqB1bd58MLvg_ADSiFODN';
const headers={apikey:SK,Authorization:`Bearer ${SK}`};
const text=element=>String(element?.textContent||'').replace(/\s+/g,' ').trim().toLowerCase();

export default function SOSSubcategoryRestoreHost(){
  const[categories,setCategories]=useState([]);const[services,setServices]=useState([]);const[open,setOpen]=useState(false);const[active,setActive]=useState('all');const[mounted,setMounted]=useState(false);
  useEffect(()=>{let alive=true;Promise.all([
    fetch(`${SB}/rest/v1/sos_categories?select=id,name,description,sort_order&is_active=eq.true&order=sort_order.asc`,{headers}).then(r=>r.ok?r.json():[]),
    fetch(`${SB}/rest/v1/sos_subcategories?select=id,category_id,name,description,base_fee,eta_band,sort_order&is_active=eq.true&order=category_id.asc,sort_order.asc`,{headers}).then(r=>r.ok?r.json():[]),
  ]).then(([nextCategories,nextServices])=>{if(!alive)return;setCategories(Array.isArray(nextCategories)?nextCategories:[]);setServices(Array.isArray(nextServices)?nextServices:[])});
    const sync=()=>setMounted(Boolean(document.querySelector('.sos2-app')));sync();const observer=new MutationObserver(sync);observer.observe(document.body,{childList:true,subtree:true});return()=>{alive=false;observer.disconnect()};
  },[]);
  const visible=useMemo(()=>active==='all'?services:services.filter(service=>service.category_id===active),[active,services]);
  const openService=service=>{const categoryName=categories.find(category=>category.id===service.category_id)?.name||'';setOpen(false);const nav=[...document.querySelectorAll('.sos2-nav button')].find(button=>text(button).includes('services'));nav?.click();window.setTimeout(()=>{const filter=[...document.querySelectorAll('.sos2-filter-rail button')].find(button=>text(button)===categoryName.toLowerCase());filter?.click();window.setTimeout(()=>{const card=[...document.querySelectorAll('.sos2-service-list > button')].find(button=>String(button.querySelector('strong')?.textContent||'').trim()===service.name);card?.scrollIntoView({behavior:'smooth',block:'center'});card?.click()},120)},120)};
  if(!mounted||!services.length)return null;
  return <><style>{`
    .sos-subcat-launch{position:fixed;right:14px;bottom:91px;z-index:88;border:1px solid rgba(255,139,73,.35);border-radius:999px;background:rgba(8,12,20,.95);color:#fff;padding:9px 12px;font:900 8px Inter,sans-serif;letter-spacing:.08em;box-shadow:0 12px 35px rgba(0,0,0,.38);backdrop-filter:blur(18px)}.sos-subcat-launch b{color:#ff9a5f;margin-left:5px}
    .sos-subcat-backdrop{position:fixed;inset:0;z-index:220;background:rgba(3,6,11,.84);backdrop-filter:blur(18px);display:flex;align-items:flex-end;justify-content:center}.sos-subcat-sheet{width:min(100%,460px);max-height:86dvh;overflow:auto;border-radius:28px 28px 0 0;padding:10px 16px calc(24px + env(safe-area-inset-bottom));background:linear-gradient(155deg,#1c1716,#080c14 72%);border-top:1px solid rgba(255,139,73,.24);color:#fff;box-shadow:0 -30px 80px rgba(0,0,0,.55)}
    .sos-subcat-handle{width:42px;height:4px;border-radius:99px;background:rgba(255,255,255,.24);margin:0 auto 18px}.sos-subcat-head{display:flex;gap:12px;align-items:flex-start;justify-content:space-between}.sos-subcat-head span{font-size:8px;letter-spacing:.16em;color:#ff9a5f;font-weight:900}.sos-subcat-head h2{font:900 30px/1 Inter,sans-serif;letter-spacing:-.045em;margin:6px 0}.sos-subcat-head p{margin:0;color:rgba(255,255,255,.58);font-size:9px;line-height:1.5}.sos-subcat-close{width:38px;height:38px;border:1px solid rgba(255,255,255,.12);border-radius:13px;background:rgba(255,255,255,.04);color:#fff;font-size:20px}
    .sos-subcat-filters{display:flex;gap:7px;overflow:auto;padding:17px 0 12px;scrollbar-width:none}.sos-subcat-filters button{white-space:nowrap;border:1px solid rgba(255,255,255,.12);border-radius:999px;background:#101722;color:rgba(255,255,255,.58);padding:8px 11px;font-size:8px}.sos-subcat-filters button.active{background:#ff6b35;color:#fff;border-color:#ff6b35;font-weight:900}.sos-subcat-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.sos-subcat-card{min-height:106px;border:1px solid rgba(255,255,255,.1);border-radius:17px;background:linear-gradient(150deg,#171c27,#0b1019);color:#fff;padding:12px;text-align:left;display:flex;flex-direction:column;gap:5px}.sos-subcat-card small{font-size:7px;color:#ff9a5f;letter-spacing:.08em}.sos-subcat-card strong{font-size:10px}.sos-subcat-card p{font-size:7px;line-height:1.4;color:rgba(255,255,255,.54);margin:0;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.sos-subcat-card em{margin-top:auto;font-style:normal;color:#ffb347;font-size:12px;font-weight:900}@media(max-width:370px){.sos-subcat-grid{grid-template-columns:1fr}}
  `}</style><button type="button" className="sos-subcat-launch" onClick={()=>setOpen(true)}>SUBCATEGORIES <b>{services.length}</b></button>{open&&<div className="sos-subcat-backdrop" onMouseDown={()=>setOpen(false)}><section className="sos-subcat-sheet" onMouseDown={event=>event.stopPropagation()} role="dialog" aria-modal="true"><div className="sos-subcat-handle"/><div className="sos-subcat-head"><div><span>S.O.S. SERVICE DIRECTORY</span><h2>Choose your subcategory.</h2><p>{categories.length} categories · {services.length} active roadside subcategories. Tap one to open dispatch.</p></div><button className="sos-subcat-close" onClick={()=>setOpen(false)}>×</button></div><div className="sos-subcat-filters"><button className={active==='all'?'active':''} onClick={()=>setActive('all')}>All</button>{categories.map(category=><button key={category.id} className={active===category.id?'active':''} onClick={()=>setActive(category.id)}>{category.name}</button>)}</div><div className="sos-subcat-grid">{visible.map(service=><button className="sos-subcat-card" key={service.id} onClick={()=>openService(service)}><small>{categories.find(category=>category.id===service.category_id)?.name||'S.O.S.'}</small><strong>{service.name}</strong><p>{service.description||'Verified roadside and vehicle support.'}</p><em>{Number(service.base_fee||0)>0?`$${Number(service.base_fee).toFixed(0)}+`:'QUOTE'} · {service.eta_band||'LIVE MATCH'}</em></button>)}</div></section></div>}</>;
}
