'use client';

import React,{useEffect,useState}from'react';
const SB='https://cxdqkjvtpilvouwtbgdy.supabase.co';
const SK='sb_publishable_x_QDbPwZuhbqB1bd58MLvg_ADSiFODN';
const stored=()=>{try{const s=JSON.parse(localStorage.getItem('sos_session'));if(!s?.access_token||!s?.user)return null;if(s.expires_at&&s.expires_at<Date.now()/1000)return null;return s}catch{return null}};
const request=async(path,{method='GET',token,body}={})=>{const r=await fetch(`${SB}${path}`,{method,headers:{apikey:SK,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||d?.error_description||d?.error||'Request failed');return d};

export default function SOSShareTrackingHost(){
 const[mission,setMission]=useState(null),[share,setShare]=useState(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const load=async()=>{const s=stored();if(!s){setMission(null);return}const us=await request(`/rest/v1/sos_users?auth_id=eq.${s.user.id}&select=id,role&limit=1`,{token:s.access_token});const u=us?.[0];if(!u||u.role==='hero'){setMission(null);return}const rows=await request(`/rest/v1/sos_missions?citizen_id=eq.${u.id}&status=in.(matching,assigned,en_route,on_site,working)&select=id,status,requested_service_name&order=created_at.desc&limit=1`,{token:s.access_token});setMission(rows?.[0]||null)};
 useEffect(()=>{let disposed=false;const run=()=>{if(!disposed)load().catch(()=>{})};run();const t=setInterval(run,12000);const focus=()=>run();window.addEventListener('focus',focus);return()=>{disposed=true;clearInterval(t);window.removeEventListener('focus',focus)}},[]);
 const create=async()=>{const s=stored();if(!s||!mission||busy)return;setBusy(true);setNotice('');try{const d=await request('/rest/v1/rpc/sos_create_mission_share',{method:'POST',token:s.access_token,body:{p_mission_id:mission.id}});setShare(d)}catch(e){setNotice(e.message)}finally{setBusy(false)}};
 const revoke=async()=>{const s=stored();if(!s||!mission||busy)return;setBusy(true);setNotice('');try{await request('/rest/v1/rpc/sos_revoke_mission_shares',{method:'POST',token:s.access_token,body:{p_mission_id:mission.id}});setShare(null);setNotice('All trusted tracking links for this mission were revoked.');setTimeout(()=>setNotice(''),3500)}catch(e){setNotice(e.message)}finally{setBusy(false)}};
 const nativeShare=async()=>{if(!share)return;try{if(navigator.share)await navigator.share({title:`S.O.S. · ${mission?.requested_service_name||'Live mission'}`,text:'Follow this S.O.S. mission with my temporary trusted tracking link.',url:share.url});else{await navigator.clipboard.writeText(share.url);setNotice('Tracking link copied.')}}catch{}};
 const copy=async()=>{if(!share)return;try{await navigator.clipboard.writeText(share.url);setNotice('Tracking link copied.');setTimeout(()=>setNotice(''),2400)}catch{setNotice('Copy is unavailable on this browser.')}};
 if(!mission)return null;
 return <>
  <button type="button" onClick={()=>setOpen(true)} style={{position:'fixed',left:16,bottom:92,zIndex:1760,border:'1px solid rgba(255,255,255,.13)',borderRadius:999,padding:'10px 13px',background:'rgba(17,27,37,.96)',color:'#fff',fontSize:9,fontWeight:900,letterSpacing:'.06em',boxShadow:'0 12px 36px rgba(0,0,0,.32)',backdropFilter:'blur(12px)'}}>SHARE LIVE TRACKING</button>
  {open&&<div role="dialog" aria-modal="true" style={{position:'fixed',inset:0,zIndex:2460,background:'rgba(3,8,15,.62)',display:'grid',placeItems:'end center',padding:12,backdropFilter:'blur(8px)'}}><section style={{width:'min(560px,100%)',borderRadius:23,background:'#f7f9fc',boxShadow:'0 28px 90px rgba(0,0,0,.44)',overflow:'hidden'}}><header style={{padding:'16px 17px',background:'#101922',color:'#fff',display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><small style={{fontSize:9,fontWeight:900,letterSpacing:'.12em',color:'#ff9d77'}}>TRUSTED MISSION TRACKING</small><h3 style={{fontSize:20,margin:'4px 0 0'}}>{mission.requested_service_name||'Roadside mission'}</h3></div><button type="button" onClick={()=>setOpen(false)} style={{width:34,height:34,border:0,borderRadius:11,background:'rgba(255,255,255,.09)',color:'#fff',fontSize:20}}>×</button></header><div style={{padding:17}}><p style={{fontSize:11,lineHeight:1.55,color:'#637187',margin:'0 0 13px'}}>Share a temporary mission link with someone you trust. They can see mission status, assigned Hero and live location, but never your S.O.S. account, phone, email or payment information.</p>{share?<><div style={{padding:12,borderRadius:14,background:'#fff1e9',border:'1px solid #ffd5c4',wordBreak:'break-all',fontSize:9.5,color:'#70422e'}}>{share.url}</div><div style={{fontSize:8.5,color:'#8b97a8',marginTop:6}}>Expires {new Date(share.expires_at).toLocaleString()}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:13}}><button type="button" onClick={nativeShare} style={{border:0,borderRadius:13,padding:12,background:'#ff6b35',color:'#fff',fontSize:10,fontWeight:900}}>SHARE</button><button type="button" onClick={copy} style={{border:'1px solid #d7dee8',borderRadius:13,padding:12,background:'#fff',color:'#334155',fontSize:10,fontWeight:900}}>COPY LINK</button></div><button type="button" onClick={revoke} disabled={busy} style={{width:'100%',border:0,background:'transparent',color:'#b42318',fontSize:9,fontWeight:900,marginTop:13}}>{busy?'REVOKING…':'REVOKE ALL TRACKING LINKS'}</button></>:<button type="button" onClick={create} disabled={busy} style={{width:'100%',border:0,borderRadius:13,padding:13,background:'#ff6b35',color:'#fff',fontSize:10,fontWeight:900}}>{busy?'CREATING…':'CREATE TRUSTED TRACKING LINK'}</button>}{notice&&<div style={{fontSize:9.5,color:'#475569',marginTop:10}}>{notice}</div>}</div></section></div>}
 </>;
}
