import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.112.0";

const URL=Deno.env.get("SUPABASE_URL")||"",KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Content-Type":"application/json","Cache-Control":"no-store"};

Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
 const started=Date.now(),db=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}}),softwareProblems:string[]=[],activationBlockers:string[]=[];
 const count=async(table:string,build:(q:any)=>any=(q)=>q):Promise<number|null>=>{try{const{count:c,error}=await build(db.from(table).select("*",{count:"exact",head:true}));if(error)throw error;return c??0}catch{return null}};
 const secret=async(name:string):Promise<boolean>=>{if(Deno.env.get(name))return true;try{const{data,error}=await db.rpc("sos_get_runtime_secret",{secret_name:name});return !error&&Boolean(data)}catch{return false}};
 const fifteenMinAgo=new Date(Date.now()-15*60_000).toISOString();
 const[activeServices,activeZones,verifiedHeroes,liveHeroes,openMissions,pendingPayments,stripeReady,webhookReady,v2WebhookReady,vapidPublicReady,vapidPrivateReady,pushSubscriptions,pushDeliveries,openSupportCases]=await Promise.all([
  count("sos_subcategories",q=>q.eq("is_active",true)),count("sos_service_zones",q=>q.eq("is_active",true)),count("sos_heroes",q=>q.eq("verification_status","verified").eq("is_demo",false)),count("sos_heroes",q=>q.eq("verification_status","verified").eq("is_demo",false).eq("on_duty",true).gte("last_gps_at",fifteenMinAgo)),count("sos_missions",q=>q.in("status",["requested","matching"])),count("sos_payments",q=>q.in("payment_status",["pending","requires_action"])),secret("STRIPE_SECRET_KEY"),secret("STRIPE_WEBHOOK_SECRET"),secret("STRIPE_V2_ACCOUNT_WEBHOOK_SECRET"),secret("MARKETPLACE_VAPID_PUBLIC_KEY"),secret("MARKETPLACE_VAPID_PRIVATE_KEY"),count("marketplace_push_subscriptions"),count("marketplace_push_deliveries"),count("sos_support_tickets",q=>q.in("status",["open","reviewing","waiting_customer"]))
 ]);
 const catalogReadable=activeServices!==null&&activeZones!==null,catalogReady=catalogReadable&&Number(activeServices)>0&&Number(activeZones)>0,supplyReadable=verifiedHeroes!==null&&liveHeroes!==null,paymentsReadable=pendingPayments!==null,paymentsReady=paymentsReadable&&stripeReady&&webhookReady&&v2WebhookReady,pushReady=vapidPublicReady&&vapidPrivateReady&&pushSubscriptions!==null&&pushDeliveries!==null,supportReady=openSupportCases!==null;
 if(!catalogReadable)softwareProblems.push("catalog_unreadable");else if(!catalogReady)softwareProblems.push("catalog_not_configured");if(!supplyReadable)softwareProblems.push("supply_unreadable");if(!paymentsReadable)softwareProblems.push("payments_unreadable");if(!stripeReady)softwareProblems.push("stripe_secret_missing");if(!webhookReady)softwareProblems.push("stripe_webhook_secret_missing");if(!v2WebhookReady)softwareProblems.push("stripe_v2_account_webhook_secret_missing");if(!vapidPublicReady)softwareProblems.push("push_public_key_missing");if(!vapidPrivateReady)softwareProblems.push("push_private_key_missing");if(pushSubscriptions===null||pushDeliveries===null)softwareProblems.push("push_tables_unreadable");if(!supportReady)softwareProblems.push("support_unreadable");
 if(verifiedHeroes===0)activationBlockers.push("no_verified_heroes");if(liveHeroes===0)activationBlockers.push("no_live_heroes");
 const fatal=softwareProblems.some(p=>p.endsWith("_unreadable")),softwareStatus=fatal?"unhealthy":softwareProblems.length?"degraded":"ok",activationStatus=activationBlockers.length?"blocked":"ready";
 return new Response(JSON.stringify({app:"sos",status:softwareStatus,software_status:softwareStatus,activation_status:activationStatus,software_ready:softwareStatus==="ok",market_activation_ready:activationStatus==="ready",software_problems:softwareProblems,activation_blockers:activationBlockers,checks:{catalog:{ready:catalogReady},supply:{readable:supplyReadable,verified_supply:Boolean(verifiedHeroes&&verifiedHeroes>0),live_supply:Boolean(liveHeroes&&liveHeroes>0),demo_excluded:true},demand:{readable:openMissions!==null},payments:{ready:paymentsReady,stripe_server_credential:stripeReady,webhook_signature_secret:webhookReady,stripe_v2_account_webhook_secret:v2WebhookReady,payments_table_reachable:paymentsReadable},push:{ready:pushReady},support:{table_reachable:supportReady}},latency_ms:Date.now()-started,checked_at:new Date().toISOString()},null,2),{status:fatal?503:200,headers:cors});
});
