'use client';

import {useEffect,useMemo,useState} from 'react';
import styles from './HeroOps.module.css';

const SB='https://cxdqkjvtpilvouwtbgdy.supabase.co';
const SK='sb_publishable_x_QDbPwZuhbqB1bd58MLvg_ADSiFODN';
const headers=token=>({apikey:SK,Authorization:`Bearer ${token}`,'Content-Type':'application/json'});

export default function HeroOpsPage(){
 const[session,setSession]=useState(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[apps,setApps]=useState([]),[notes,setNotes]=useState({}),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=async token=>{const r=await fetch(`${SB}/rest/v1/rpc/sos_ops_hero_applications`,{method:'POST',headers:headers(token),body:'{}'});const d=await r.json().catch(()=>[]);if(!r.ok)throw new Error(d?.message||d?.error||'Operator queue unavailable');setApps(Array.isArray(d)?d:[])};
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem('sos_ops_session'));if(s?.access_token){setSession(s);load(s.access_token).catch(()=>{localStorage.removeItem('sos_ops_session');setSession(null)})}}catch{}},[]);
 const login=async e=>{e.preventDefault();setBusy('login');setError('');try{const r=await fetch(`${SB}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:SK,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||'Sign in failed');const check=await fetch(`${SB}/rest/v1/rpc/marketplace_operator_check`,{method:'POST',headers:headers(d.access_token),body:'{}'});const ok=await check.json();if(!check.ok||ok!==true)throw new Error('This account is not an active marketplace operator.');localStorage.setItem('sos_ops_session',JSON.stringify(d));setSession(d);await load(d.access_token)}catch(e){setError(e.message)}finally{setBusy('')}};
 const review=async(app,decision)=>{if(!session||busy)return;setBusy(app.id);setError('');setNotice('');try{const r=await fetch(`${SB}/rest/v1/rpc/sos_ops_review_hero_application`,{method:'POST',headers:headers(session.access_token),body:JSON.stringify({p_application_id:app.id,p_decision:decision,p_note:notes[app.id]||null})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||d.error||'Review failed');setNotice(d.message||`Application ${decision}.`);await load(session.access_token)}catch(e){setError(e.message)}finally{setBusy('')}};
 const stats=useMemo(()=>Object.fromEntries(['submitted','reviewing','approved','rejected'].map(s=>[s,apps.filter(a=>a.status===s).length])),[apps]);
 if(!session)return <main className={styles.page}><form className={styles.auth} onSubmit={login}><span className={styles.status}>S.O.S. OPERATIONS</span><h1>Hero application review</h1><p>Operator access only. Review real applicants and move approved people into the claim + verification pipeline.</p><label className={styles.field}>Operator email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className={styles.field}>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className={styles.error}>{error}</div>}<button className={styles.primary} disabled={busy==='login'}>{busy==='login'?'Authenticating…':'Open Hero operations'}</button></form></main>;
 return <main className={styles.page}><div className={styles.shell}><header className={styles.top}><div><span>S.O.S. HERO OPERATIONS</span><h1>Real supply pipeline.</h1><p>Demo fixtures are excluded. Approval creates a claim-ready but still unverified Hero record.</p></div><a className={styles.back} href="/hero">Hero Command →</a></header>{error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}<div className={styles.stats}>{['submitted','reviewing','approved','rejected'].map(s=><div className={styles.stat} key={s}><small>{s.toUpperCase()}</small><strong>{stats[s]||0}</strong></div>)}</div><section className={styles.list}>{apps.length===0?<div className={styles.empty}>No real Hero applications yet.</div>:apps.map(a=><article className={styles.card} key={a.id}><div className={styles.head}><div><small>{new Date(a.submitted_at).toLocaleString()}</small><h2>{a.first_name} {a.last_name}</h2><p>{a.email} · {a.phone}</p></div><span className={styles.status}>{a.status}</span></div><div className={styles.details}><div className={styles.detail}><small>MARKET</small><strong>{[a.city,a.state].filter(Boolean).join(', ')||'Not specified'}</strong></div><div className={styles.detail}><small>EXPERIENCE</small><strong>{a.years_experience||0} years</strong></div><div className={styles.detail}><small>VEHICLE</small><strong>{[a.vehicle_year,a.vehicle_make,a.vehicle_model,a.vehicle_type].filter(Boolean).join(' ')||'Not specified'}</strong></div><div className={styles.detail}><small>SERVICES</small><strong>{(a.services_requested||[]).join(' · ')||'None selected'}</strong></div><div className={styles.detail}><small>TOOLS</small><strong>{(a.tools_available||[]).join(' · ')||'None listed'}</strong></div><div className={`${styles.detail} ${styles.summary}`}><small>EXPERIENCE SUMMARY</small><strong>{a.experience_summary||'No written summary.'}</strong></div></div><div className={styles.actions}><textarea value={notes[a.id]??a.operator_note??''} onChange={e=>setNotes({...notes,[a.id]:e.target.value})} placeholder="Operator note"/><button disabled={busy===a.id} onClick={()=>review(a,'reviewing')}>Reviewing</button><button className={styles.approve} disabled={busy===a.id||a.status==='approved'} onClick={()=>review(a,'approved')}>{a.status==='approved'?'Approved':'Approve for claim'}</button><button className={styles.reject} disabled={busy===a.id||a.status==='rejected'} onClick={()=>review(a,'rejected')}>Reject</button></div></article>)}</section></div></main>;
}