import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.112.0";
import Stripe from "npm:stripe@18.5.0";
const ALLOWED_ORIGINS=new Set(["https://thesuperherosonstandby.com","https://www.thesuperherosonstandby.com","https://superherosonstandby.com","https://www.superherosonstandby.com","https://sos-app-website.vercel.app","capacitor://localhost","http://localhost","https://localhost"]);
const cors=(origin:string|null)=>({"Access-Control-Allow-Origin":origin&&ALLOWED_ORIGINS.has(origin)?origin:"https://thesuperherosonstandby.com","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-client-info","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"});
const json=(body:unknown,status=200,origin:string|null=null)=>new Response(JSON.stringify(body),{status,headers:{...cors(origin),"Content-Type":"application/json"}});
const env=(name:string)=>{const value=Deno.env.get(name);if(!value)throw new Error(`${name} is not configured`);return value};
const admin=()=>createClient(env("SUPABASE_URL"),env("SUPABASE_SERVICE_ROLE_KEY"),{auth:{persistSession:false,autoRefreshToken:false}});
async function stripe(client:any){let key=Deno.env.get('STRIPE_SECRET_KEY')||'';if(!key){const{data,error}=await client.rpc('sos_get_runtime_secret',{secret_name:'STRIPE_SECRET_KEY'});if(!error&&data)key=String(data)}if(!key)throw new Error('STRIPE_SECRET_KEY is not configured');return new Stripe(key,{httpClient:Stripe.createFetchHttpClient()})}
const allowedSubscriptionStatus=(status:string)=>['active','past_due','canceled','trialing','paused'].includes(status)?status:(status==='unpaid'||status==='incomplete_expired'?'canceled':'past_due');
async function persistMembership(client:any,profile:any,plan:any,subscription:any){const periodStart=subscription?.current_period_start?new Date(subscription.current_period_start*1000).toISOString():new Date().toISOString();const periodEnd=subscription?.current_period_end?new Date(subscription.current_period_end*1000).toISOString():null;const status=allowedSubscriptionStatus(String(subscription?.status||'active'));const subscriptionId=String(subscription?.id||'');if(!subscriptionId)throw new Error('Stripe subscription is unavailable');const{error}=await client.from('sos_subscriptions').upsert({user_id:profile.id,plan:plan.id,status,stripe_subscription_id:subscriptionId,monthly_price:plan.monthly_price,included_services:plan.included_services,used_services:0,discount_percent:plan.discount_percent,current_period_start:periodStart,current_period_end:periodEnd,canceled_at:status==='canceled'?new Date().toISOString():null,updated_at:new Date().toISOString()},{onConflict:'stripe_subscription_id'});if(error)throw error;if(['active','trialing'].includes(status)){const{error:userError}=await client.from('sos_users').update({shield_plan:plan.id,updated_at:new Date().toISOString()}).eq('id',profile.id);if(userError)throw userError}return status}
Deno.serve(async req=>{
 const origin=req.headers.get("origin");if(req.method==="OPTIONS")return new Response("ok",{headers:cors(origin)});if(req.method!=="POST")return json({error:"Method not allowed"},405,origin);if(origin&&!ALLOWED_ORIGINS.has(origin))return json({error:"Origin not allowed"},403,origin);
 try{const token=req.headers.get("Authorization")?.replace(/^Bearer\s+/i,"");if(!token)return json({error:"Authentication required"},401,origin);const client=admin();const{data:{user},error:authError}=await client.auth.getUser(token);if(authError||!user)return json({error:"Authentication required"},401,origin);const{data:profile,error:profileError}=await client.from("sos_users").select("id,email,stripe_customer_id,shield_plan,status").eq("auth_id",user.id).single();if(profileError||!profile||profile.status!=='active')return json({error:"Active SOS customer profile required"},403,origin);const body=await req.json().catch(()=>({}));const action=String(body.action||"plans");
 if(action==="plans"){const{data,error}=await client.from("sos_membership_plans").select("id,name,tagline,monthly_price,included_services,discount_percent,priority_matching,household_members,features").eq("is_active",true).order("sort_order");if(error)throw error;const{data:activeSub}=await client.from('sos_subscriptions').select('plan,status,current_period_end').eq('user_id',profile.id).in('status',['active','trialing']).order('created_at',{ascending:false}).limit(1).maybeSingle();return json({plans:data||[],currentPlan:activeSub?.plan||null,subscription:activeSub||null},200,origin)}
 const stripeClient=await stripe(client)
 if(action==="checkout"){const planId=String(body.planId||"");const{data:plan,error:planError}=await client.from("sos_membership_plans").select("*").eq("id",planId).eq("is_active",true).single();if(planError||!plan)return json({error:"Membership plan not found"},404,origin);let customerId=profile.stripe_customer_id as string|null;if(!customerId){const customer=await stripeClient.customers.create({email:profile.email||user.email||undefined,metadata:{brand:"SOS",sos_user_id:profile.id,auth_id:user.id}});customerId=customer.id;const{error:updateError}=await client.from("sos_users").update({stripe_customer_id:customerId,updated_at:new Date().toISOString()}).eq("id",profile.id);if(updateError)throw updateError}const amount=Math.round(Number(plan.monthly_price)*100);if(!Number.isSafeInteger(amount)||amount<50)throw new Error('Membership price is invalid');const session=await stripeClient.checkout.sessions.create({mode:"subscription",customer:customerId,line_items:[{quantity:1,price_data:{currency:"usd",unit_amount:amount,recurring:{interval:"month"},product_data:{name:`SOS ${plan.name}`,description:plan.tagline||undefined,metadata:{brand:"SOS",plan_id:plan.id}}}}],success_url:"https://thesuperherosonstandby.com/app?membership=success&session_id={CHECKOUT_SESSION_ID}",cancel_url:"https://thesuperherosonstandby.com/app?membership=canceled",metadata:{brand:"SOS",flow:"membership",plan_id:plan.id,sos_user_id:profile.id},subscription_data:{metadata:{brand:"SOS",flow:"membership",plan_id:plan.id,sos_user_id:profile.id}}},{idempotencyKey:`sos-membership-${profile.id}-${plan.id}-checkout-v3`});return json({url:session.url},200,origin)}
 if(action==="verify"){const sessionId=String(body.sessionId||"");if(!sessionId)return json({error:"sessionId is required"},422,origin);const session=await stripeClient.checkout.sessions.retrieve(sessionId,{expand:["subscription"]});if(session.customer!==profile.stripe_customer_id||session.metadata?.sos_user_id!==profile.id||session.metadata?.flow!=='membership')return json({error:"Membership checkout not found"},404,origin);if(session.status!=="complete")return json({verified:false,status:session.status},200,origin);const planId=session.metadata?.plan_id||"";const{data:plan,error:planError}=await client.from("sos_membership_plans").select("*").eq("id",planId).eq('is_active',true).single();if(planError||!plan)return json({error:"Membership plan unavailable"},409,origin);const subscription=typeof session.subscription==="string"?await stripeClient.subscriptions.retrieve(session.subscription):session.subscription;const status=await persistMembership(client,profile,plan,subscription);return json({verified:['active','trialing'].includes(status),status,plan:{id:plan.id,name:plan.name}},200,origin)}
 return json({error:"Unsupported action"},422,origin)
 }catch(error){console.error("sos-membership",error);const message=error instanceof Error?error.message:"Unexpected error";return json({error:message.endsWith("is not configured")?"Membership payments are not configured for this release.":message},message.endsWith("is not configured")?503:400,origin)}
});