import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import Stripe from 'npm:stripe@18.5.0';
import { createClient } from 'npm:@supabase/supabase-js@2.112.0';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type, x-client-info','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}});
Deno.serve(async(req)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'Method not allowed'},405);
 try{
  const token=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'');if(!token)throw new Error('Authentication required');
  const url=Deno.env.get('SUPABASE_URL')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const{data:{user}}=await admin.auth.getUser(token);if(!user)throw new Error('Authentication required');
  let stripeKey=Deno.env.get('STRIPE_SECRET_KEY')||'';if(!stripeKey){const{data,error}=await admin.rpc('sos_get_runtime_secret',{secret_name:'STRIPE_SECRET_KEY'});if(!error&&data)stripeKey=String(data)}
  const{missionId,action='quote',expectedFeeAmount}=await req.json();if(typeof missionId!=='string')return json({error:'missionId is required'},422);
  const{data:u}=await admin.from('sos_users').select('id,role').eq('auth_id',user.id).maybeSingle();if(!u||u.role!=='hero')throw new Error('Hero account required');const{data:h}=await admin.from('sos_heroes').select('id,stripe_connect_id').eq('user_id',u.id).maybeSingle();if(!h)throw new Error('Hero account required');const{data:m}=await admin.from('sos_missions').select('*').eq('id',missionId).eq('hero_id',h.id).maybeSingle();if(!m)throw new Error('Assigned mission not found');
  const{data:cfgRow}=await admin.from('sos_system_config').select('config_value').eq('config_key','cancellation_policy').eq('is_active',true).maybeSingle();const cfg=cfgRow?.config_value||{};const wait=Math.max(1,Number(cfg.customer_no_show_wait_minutes||10));const total=Number(m.final_price||m.estimated_price||m.client_estimate_amount||0),pct=Number(cfg.on_site?.percent||20),min=Number(cfg.on_site?.minimum||15),max=Number(cfg.on_site?.maximum||40),share=Number(cfg.hero_share_percent||80);const fee=Math.min(max,Math.max(min,Math.round(total*pct)/100));const heroComp=Math.round(fee*share)/100,platformFee=Math.max(0,fee-heroComp);
  const waitSeconds=wait*60,elapsedSeconds=m.arrived_at?Math.max(0,Math.floor((Date.now()-new Date(m.arrived_at).getTime())/1000)):0,remainingSeconds=Math.max(0,waitSeconds-elapsedSeconds);const{data:pay}=await admin.from('sos_payments').select('*').eq('mission_id',missionId).maybeSingle();const canSettle=m.status==='on_site'&&Boolean(m.arrived_at)&&remainingSeconds===0&&pay?.payment_status==='authorized'&&Boolean(pay?.stripe_payment_intent_id)&&Boolean(h.stripe_connect_id);
  const quote={missionId,status:m.status,canSettle,waitMinutes:wait,secondsRemaining:remainingSeconds,remainingMinutes:Math.ceil(remainingSeconds/60),feeAmount:fee,fee,heroCompensation:heroComp,reason:m.status!=='on_site'?'No-show settlement unlocks after arrival':remainingSeconds>0?`Wait ${Math.ceil(remainingSeconds/60)} more minute${Math.ceil(remainingSeconds/60)===1?'':'s'}`:pay?.payment_status!=='authorized'?'Customer payment authorization is required':!h.stripe_connect_id?'Hero payout setup is required':'Eligible for customer no-show settlement'};
  if(action==='quote')return json(quote);if(action!=='settle')return json({error:'action must be quote or settle'},422);if(!canSettle)throw new Error(quote.reason);if(expectedFeeAmount!=null&&Math.abs(Number(expectedFeeAmount)-fee)>0.009)throw new Error('No-show quote changed. Review the latest amount before confirming.');if(!stripeKey)throw new Error('STRIPE_SECRET_KEY is not configured');
  await admin.from('sos_payments').update({settlement_type:'customer_no_show',cancellation_fee:fee,original_platform_fee:pay.original_platform_fee??pay.platform_fee,original_hero_payout:pay.original_hero_payout??pay.hero_payout,platform_fee:platformFee,hero_payout:heroComp,updated_at:new Date().toISOString()}).eq('id',pay.id);
  const stripe=new Stripe(stripeKey,{httpClient:Stripe.createFetchHttpClient()});const pi=await stripe.paymentIntents.capture(pay.stripe_payment_intent_id,{amount_to_capture:Math.round(fee*100),final_capture:true,metadata:{settlement_type:'customer_no_show',cancellation_fee:String(fee)}},{idempotencyKey:`sos-no-show-${pay.id}-${Math.round(fee*100)}-v2`});const chargeId=typeof pi.latest_charge==='string'?pi.latest_charge:pi.latest_charge?.id||pay.stripe_charge_id||null;const capturedAt=new Date().toISOString();
  if(heroComp>0&&h.stripe_connect_id&&chargeId){try{const transfer=await stripe.transfers.create({amount:Math.round(heroComp*100),currency:pay.currency||'usd',destination:h.stripe_connect_id,source_transaction:chargeId,transfer_group:`sos_mission_${missionId}`,metadata:{mission_id:missionId,settlement_type:'customer_no_show'}},{idempotencyKey:`sos-customer-no-show-transfer-${missionId}-v1`});await admin.from('sos_payments').update({payment_status:'released',escrow_status:'released_to_hero',stripe_charge_id:chargeId,stripe_transfer_id:transfer.id,captured_at:capturedAt,released_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',pay.id)}catch(error){console.error('SOS no-show compensation transfer failed',{missionId,error:String(error)});await admin.from('sos_payments').update({payment_status:'transfer_pending',escrow_status:'held_for_release',stripe_charge_id:chargeId,captured_at:capturedAt,updated_at:new Date().toISOString()}).eq('id',pay.id)}}else await admin.from('sos_payments').update({payment_status:'captured',escrow_status:'held_for_release',stripe_charge_id:chargeId,captured_at:capturedAt,updated_at:new Date().toISOString()}).eq('id',pay.id);
  await admin.from('sos_missions').update({status:'canceled_by_system',canceled_at:new Date().toISOString(),cancel_reason:'customer_no_show',cancellation_fee:fee,cancellation_hero_compensation:heroComp,cancellation_policy_version:Number(cfg.version||1),updated_at:new Date().toISOString()}).eq('id',missionId);await admin.from('sos_mission_events').insert({mission_id:missionId,event_type:'system_note',old_status:'on_site',new_status:'canceled_by_system',payload:{reliability_event:'customer_no_show',wait_minutes:wait,cancellation_fee:fee,hero_compensation:heroComp},actor:'system'});return json({...quote,ok:true});
 }catch(e){const m=e instanceof Error?e.message:'Unexpected error';const config=m.endsWith('is not configured');return json({error:config?'Payments are not configured for this release.':m},config?503:m==='Authentication required'?401:400)}
});