import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import Stripe from 'npm:stripe@18.5.0'
import { createClient } from 'npm:@supabase/supabase-js@2.112.0'

const allowedSubscriptionStatus=(status:string)=>['active','past_due','canceled','trialing','paused'].includes(status)?status:(status==='unpaid'||status==='incomplete_expired'?'canceled':'past_due')
const period=(subscription:any,key:'start'|'end')=>{const direct=key==='start'?subscription?.current_period_start:subscription?.current_period_end;const item=key==='start'?subscription?.items?.data?.[0]?.current_period_start:subscription?.items?.data?.[0]?.current_period_end;const value=direct||item;return value?new Date(value*1000).toISOString():null}
const ocCapturedOrLater=(s:string)=>['capture_pending','captured','transfer_pending','transferred','partially_refunded','refunded','disputed'].includes(s)
const ocTerminal=(s:string)=>['transferred','partially_refunded','refunded','disputed'].includes(s)
const sosCapturedOrLater=(s:string)=>['captured','transfer_pending','released','partially_refunded','refunded','disputed'].includes(s)
const sosTerminal=(s:string)=>['released','partially_refunded','refunded','disputed'].includes(s)

Deno.serve(async(req)=>{
 if(req.method!=='POST')return new Response('Method not allowed',{status:405})
 const url=Deno.env.get('SUPABASE_URL')||'',service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';if(!url||!service)return new Response('Webhook database runtime is not configured',{status:503})
 const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}})
 const readSecret=async(name:string)=>{const env=Deno.env.get(name);if(env)return env;const{data,error}=await admin.rpc('sos_get_runtime_secret',{secret_name:name});return error||!data?'':String(data)}
 const webhookSecret=await readSecret('STRIPE_WEBHOOK_SECRET')||await readSecret('sos_stripe_webhook_secret');if(!webhookSecret)return new Response('Stripe webhook signing secret is unavailable',{status:503})
 const stripeKey=await readSecret('STRIPE_SECRET_KEY');const stripe=new Stripe(stripeKey||'sk_test_webhook_verification_only',{httpClient:Stripe.createFetchHttpClient()})
 const body=await req.text(),sig=req.headers.get('stripe-signature')||'';let event:Stripe.Event
 try{event=await stripe.webhooks.constructEventAsync(body,sig,webhookSecret)}catch{return new Response('Invalid signature',{status:400})}
 const object=event.data.object as any
 const intentId=object?.object==='payment_intent'?object.id:(typeof object?.payment_intent==='string'?object.payment_intent:null)
 const accountId=event.type==='account.updated'&&object?.id?String(object.id):null
 const bookingId=String(object?.metadata?.booking_id||'')
 const checkoutId=object?.object==='checkout.session'?String(object.id||''):''
 const onCallByMetadata=object?.metadata?.brand==='ON_CALL'||object?.metadata?.brand==='on_call'||Boolean(bookingId)
 let ocPayment:any=null
 if(intentId){const{data}=await admin.from('oc_booking_payments').select('*,provider:oc_provider_profiles!oc_booking_payments_provider_id_fkey(stripe_account_id,stripe_payouts_enabled,stripe_account_api_version,stripe_transfer_status)').eq('stripe_payment_intent_id',intentId).maybeSingle();ocPayment=data}
 if(!ocPayment&&bookingId){const{data}=await admin.from('oc_booking_payments').select('*,provider:oc_provider_profiles!oc_booking_payments_provider_id_fkey(stripe_account_id,stripe_payouts_enabled,stripe_account_api_version,stripe_transfer_status)').eq('booking_id',bookingId).maybeSingle();ocPayment=data}
 if(!ocPayment&&checkoutId){const{data}=await admin.from('oc_booking_payments').select('*,provider:oc_provider_profiles!oc_booking_payments_provider_id_fkey(stripe_account_id,stripe_payouts_enabled,stripe_account_api_version,stripe_transfer_status)').eq('stripe_checkout_session_id',checkoutId).maybeSingle();ocPayment=data}
 const [{data:ocAccountProvider},{data:sosAccountHero}]=accountId?await Promise.all([admin.from('oc_provider_profiles').select('id,stripe_account_api_version').eq('stripe_account_id',accountId).maybeSingle(),admin.from('sos_heroes').select('id,stripe_connect_api_version').eq('stripe_connect_id',accountId).maybeSingle()]):[{data:null},{data:null}]
 const isOnCall=onCallByMetadata||Boolean(ocPayment)||Boolean(ocAccountProvider)||(event.type==='account.updated'&&(object?.metadata?.brand==='ON_CALL'||object?.metadata?.brand==='on_call'))
 if(isOnCall){
  let duplicate=false;const{error:eventError}=await admin.from('oc_payment_events').insert({stripe_event_id:event.id,event_type:event.type,payment_id:ocPayment?.id??null,livemode:event.livemode,payload:event});if(eventError?.code==='23505')duplicate=true;else if(eventError)return new Response('ON CALL event ledger unavailable',{status:500})
  if(event.type==='account.updated'&&accountId){const provider=ocAccountProvider;if(provider?.stripe_account_api_version==='v2')return Response.json({received:true,duplicate,brand:'ON_CALL',account_api:'v2',ignored_legacy_account_snapshot:true});await admin.from('oc_provider_profiles').update({stripe_charges_enabled:Boolean(object.charges_enabled),stripe_payouts_enabled:Boolean(object.payouts_enabled),stripe_onboarding_complete:Boolean(object.details_submitted&&object.payouts_enabled),updated_at:new Date().toISOString()}).eq('stripe_account_id',accountId);return Response.json({received:true,duplicate,brand:'ON_CALL',legacy_account_sync:true})}
  if(event.type==='checkout.session.completed'&&bookingId){const pi=typeof object.payment_intent==='string'?object.payment_intent:object.payment_intent?.id||null;const patch:any={stripe_checkout_session_id:object.id,updated_at:new Date().toISOString()};if(pi)patch.stripe_payment_intent_id=pi;const{data:updated}=await admin.from('oc_booking_payments').update(patch).eq('booking_id',bookingId).select('*,provider:oc_provider_profiles!oc_booking_payments_provider_id_fkey(stripe_account_id,stripe_payouts_enabled,stripe_account_api_version,stripe_transfer_status)').maybeSingle();if(updated)ocPayment=updated}
  if(ocPayment&&object?.object==='payment_intent'&&intentId&&ocPayment.stripe_payment_intent_id!==intentId){await admin.from('oc_booking_payments').update({stripe_payment_intent_id:intentId,updated_at:new Date().toISOString()}).eq('id',ocPayment.id);ocPayment={...ocPayment,stripe_payment_intent_id:intentId}}
  if(ocPayment){
   if(event.type==='payment_intent.amount_capturable_updated'){
    let charge:any=null;if(stripeKey&&object.latest_charge){try{charge=await stripe.charges.retrieve(typeof object.latest_charge==='string'?object.latest_charge:object.latest_charge.id)}catch{}}
    const patch:any={authorized_at:ocPayment.authorized_at??new Date().toISOString(),stripe_payment_intent_id:object.id,stripe_charge_id:charge?.id??(typeof object.latest_charge==='string'?object.latest_charge:ocPayment.stripe_charge_id),capture_by:charge?.payment_method_details?.card?.capture_before?new Date(charge.payment_method_details.card.capture_before*1000).toISOString():ocPayment.capture_by,updated_at:new Date().toISOString()};if(!ocCapturedOrLater(String(ocPayment.status||'')))patch.status='authorized';await admin.from('oc_booking_payments').update(patch).eq('id',ocPayment.id)
   }else if(event.type==='payment_intent.succeeded'){
    const patch:any={stripe_payment_intent_id:object.id,amount_captured:object.amount_received??object.amount??ocPayment.amount_authorized,captured_at:ocPayment.captured_at??new Date().toISOString(),stripe_charge_id:typeof object.latest_charge==='string'?object.latest_charge:ocPayment.stripe_charge_id,updated_at:new Date().toISOString()};if(!ocTerminal(String(ocPayment.status||'')))patch.status=ocPayment.stripe_transfer_id?'transferred':'transfer_pending';await admin.from('oc_booking_payments').update(patch).eq('id',ocPayment.id)
    const providerReady=ocPayment.provider?.stripe_account_api_version==='v2'?ocPayment.provider?.stripe_transfer_status==='active':ocPayment.provider?.stripe_payouts_enabled;if(ocPayment.provider?.stripe_account_id&&providerReady&&!ocPayment.stripe_transfer_id){if(!stripeKey)return new Response('Payment captured; provider transfer pending Stripe API credential restoration',{status:503});try{const transfer=await stripe.transfers.create({amount:ocPayment.provider_amount,currency:ocPayment.currency,destination:ocPayment.provider.stripe_account_id,transfer_group:`oc_booking_${ocPayment.booking_id}`,metadata:{brand:'ON_CALL',booking_id:ocPayment.booking_id,payment_id:ocPayment.id}},{idempotencyKey:`oc-payment-${ocPayment.id}-transfer-v2`});await admin.from('oc_booking_payments').update({status:'transferred',stripe_transfer_id:transfer.id,transferred_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',ocPayment.id)}catch(error){console.error('ON CALL webhook transfer failed',error);return new Response('Provider transfer retry required',{status:503})}}
   }else if(event.type==='payment_intent.payment_failed'){if(!ocCapturedOrLater(String(ocPayment.status||'')))await admin.from('oc_booking_payments').update({status:'failed',stripe_payment_intent_id:object.id,failure_code:object.last_payment_error?.code??null,failure_message:object.last_payment_error?.message??null,updated_at:new Date().toISOString()}).eq('id',ocPayment.id)}
   else if(event.type==='payment_intent.canceled'){if(!ocCapturedOrLater(String(ocPayment.status||'')))await admin.from('oc_booking_payments').update({status:'authorization_canceled',stripe_payment_intent_id:object.id,canceled_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',ocPayment.id)}
   else if(event.type==='charge.dispute.created')await admin.from('oc_booking_payments').update({status:'disputed',updated_at:new Date().toISOString()}).eq('id',ocPayment.id)
   else if(event.type==='charge.refunded'){const refunded=object.amount_refunded??0;await admin.from('oc_booking_payments').update({amount_refunded:refunded,status:refunded>=ocPayment.amount_captured?'refunded':'partially_refunded',updated_at:new Date().toISOString()}).eq('id',ocPayment.id)}
  }
  return Response.json({received:true,duplicate,brand:'ON_CALL',stripe_api_ready:Boolean(stripeKey)})
 }
 let duplicate=false;const{error:ledgerError}=await admin.from('sos_stripe_events').insert({event_id:event.id,event_type:event.type,livemode:event.livemode,object_id:object?.id,payload:{created:event.created}});if(ledgerError?.code==='23505')duplicate=true;else if(ledgerError)return new Response('Event ledger unavailable',{status:500})
 if(event.type==='account.updated'&&accountId&&sosAccountHero&&sosAccountHero.stripe_connect_api_version==='v2')return Response.json({received:true,duplicate,brand:'SOS',account_api:'v2',ignored_legacy_account_snapshot:true})
 const membershipFlow=object?.metadata?.brand==='SOS'&&object?.metadata?.flow==='membership'
 if(membershipFlow&&(event.type==='checkout.session.completed'||event.type==='customer.subscription.created'||event.type==='customer.subscription.updated'||event.type==='customer.subscription.deleted')){try{let subscription:any=object;let userId=String(object?.metadata?.sos_user_id||''),planId=String(object?.metadata?.plan_id||'');if(event.type==='checkout.session.completed'){if(!object.subscription)throw new Error('Membership subscription missing from Checkout Session');if(!stripeKey)return new Response('Membership event recorded; subscription fetch awaits Stripe API credential restoration',{status:503});subscription=await stripe.subscriptions.retrieve(typeof object.subscription==='string'?object.subscription:object.subscription.id);userId=String(object.metadata?.sos_user_id||subscription.metadata?.sos_user_id||'');planId=String(object.metadata?.plan_id||subscription.metadata?.plan_id||'')}if(!userId||!planId)throw new Error('Membership metadata is incomplete');const{data:plan,error:planError}=await admin.from('sos_membership_plans').select('*').eq('id',planId).single();if(planError||!plan)throw new Error('Membership plan not found');const status=event.type==='customer.subscription.deleted'?'canceled':allowedSubscriptionStatus(String(subscription.status||'active')),subId=String(subscription.id||object.subscription||'');if(!subId)throw new Error('Membership subscription ID missing');const{error:upsertError}=await admin.from('sos_subscriptions').upsert({user_id:userId,plan:plan.id,status,stripe_subscription_id:subId,monthly_price:plan.monthly_price,included_services:plan.included_services,discount_percent:plan.discount_percent,current_period_start:period(subscription,'start')||new Date().toISOString(),current_period_end:period(subscription,'end'),canceled_at:status==='canceled'?new Date().toISOString():null,updated_at:new Date().toISOString()},{onConflict:'stripe_subscription_id'});if(upsertError)throw upsertError;if(['active','trialing'].includes(status))await admin.from('sos_users').update({shield_plan:plan.id,updated_at:new Date().toISOString()}).eq('id',userId);else if(status==='canceled'){const{data:other}=await admin.from('sos_subscriptions').select('plan').eq('user_id',userId).in('status',['active','trialing']).neq('stripe_subscription_id',subId).limit(1).maybeSingle();await admin.from('sos_users').update({shield_plan:other?.plan??null,updated_at:new Date().toISOString()}).eq('id',userId)}}catch(error){console.error('SOS membership webhook failed',{eventId:event.id,eventType:event.type,error:String(error)});return new Response('Membership reconciliation failed',{status:500})}return Response.json({received:true,duplicate,brand:'SOS',flow:'membership'})}

 const missionId=String(object?.metadata?.mission_id||'')
 const eventIntentId=object?.object==='payment_intent'?String(object.id||''):(typeof object?.payment_intent==='string'?object.payment_intent:(object?.payment_intent?.id?String(object.payment_intent.id):''))
 const eventChargeId=object?.object==='charge'?String(object.id||''):(typeof object?.charge==='string'?object.charge:(object?.charge?.id?String(object.charge.id):''))
 const sosPaymentSelect='id,mission_id,payment_status,escrow_status,hero_id,hero_payout,stripe_payment_intent_id,stripe_transfer_id,stripe_refund_id,stripe_charge_id,stripe_dispute_id,amount,tax,tip,refund_amount,authorized_at,captured_at'
 let sosPayment:any=null
 if(missionId){const{data}=await admin.from('sos_payments').select(sosPaymentSelect).eq('mission_id',missionId).maybeSingle();sosPayment=data}
 if(!sosPayment&&eventIntentId){const{data}=await admin.from('sos_payments').select(sosPaymentSelect).eq('stripe_payment_intent_id',eventIntentId).maybeSingle();sosPayment=data}
 if(!sosPayment&&eventChargeId){const{data}=await admin.from('sos_payments').select(sosPaymentSelect).eq('stripe_charge_id',eventChargeId).maybeSingle();sosPayment=data}
 if(sosPayment){
  const patch:any={updated_at:new Date().toISOString()}
  if(event.type==='checkout.session.completed'){patch.stripe_checkout_session_id=object.id;patch.stripe_payment_intent_id=typeof object.payment_intent==='string'?object.payment_intent:null}
  else if(event.type==='payment_intent.amount_capturable_updated'){patch.authorized_at=sosPayment.authorized_at??new Date().toISOString();patch.stripe_payment_intent_id=object.id;patch.stripe_charge_id=typeof object.latest_charge==='string'?object.latest_charge:object.latest_charge?.id||sosPayment.stripe_charge_id||null;if(!sosCapturedOrLater(String(sosPayment.payment_status||''))){patch.payment_status='authorized';patch.escrow_status='authorized_hold'}}
  else if(event.type==='payment_intent.succeeded'){patch.captured_at=sosPayment.captured_at??new Date().toISOString();patch.stripe_payment_intent_id=object.id;patch.stripe_charge_id=typeof object.latest_charge==='string'?object.latest_charge:object.latest_charge?.id||sosPayment.stripe_charge_id||null;if(!sosTerminal(String(sosPayment.payment_status||''))){if(sosPayment.stripe_transfer_id){patch.payment_status='released';patch.escrow_status='released_to_hero'}else if(Number(sosPayment.hero_payout||0)>0&&sosPayment.hero_id){patch.payment_status='transfer_pending';patch.escrow_status='held_for_release'}else{patch.payment_status='captured';patch.escrow_status='held_for_release'}}}
  else if(event.type==='payment_intent.payment_failed'){if(!sosCapturedOrLater(String(sosPayment.payment_status||''))){patch.payment_status='failed';patch.escrow_status='failed';patch.failed_at=new Date().toISOString();patch.stripe_payment_intent_id=object.id}}
  else if(event.type==='payment_intent.canceled'){if(!sosCapturedOrLater(String(sosPayment.payment_status||''))){patch.payment_status='canceled';patch.escrow_status='released_to_customer';patch.stripe_payment_intent_id=object.id}}
  else if(event.type==='charge.dispute.created'){patch.payment_status='disputed';patch.escrow_status='disputed';patch.stripe_dispute_id=object.id;patch.disputed_at=new Date().toISOString();if(eventChargeId)patch.stripe_charge_id=eventChargeId;if(eventIntentId)patch.stripe_payment_intent_id=eventIntentId}
  else if(event.type==='charge.refunded'){
   const refundedCents=Math.max(0,Number(object.amount_refunded??0)),chargeAmountCents=Math.max(0,Number(object.amount??0))
   if(refundedCents>0){
    const fullyRefunded=chargeAmountCents>0&&refundedCents>=chargeAmountCents
    const refunds=Array.isArray(object?.refunds?.data)?object.refunds.data:[],latestRefund=refunds.length?refunds[refunds.length-1]:null
    patch.refund_amount=refundedCents/100;patch.refunded_at=new Date().toISOString();if(eventChargeId)patch.stripe_charge_id=eventChargeId;if(eventIntentId)patch.stripe_payment_intent_id=eventIntentId;if(latestRefund?.id)patch.stripe_refund_id=String(latestRefund.id)
    if(String(sosPayment.payment_status||'')!=='disputed'){patch.payment_status=fullyRefunded?'refunded':'partially_refunded';patch.escrow_status=fullyRefunded?'released_to_customer':'partially_refunded'}
   }
  }
  if(Object.keys(patch).length>1){const{error:updateError}=await admin.from('sos_payments').update(patch).eq('id',sosPayment.id);if(updateError){console.error('SOS payment reconciliation update failed',{eventId:event.id,eventType:event.type,paymentId:sosPayment.id,error:updateError.message});return new Response('SOS payment reconciliation failed',{status:500})}}
 }else if(['charge.refunded','charge.dispute.created'].includes(event.type))console.warn('SOS financial event could not be linked to a mission payment',{eventId:event.id,eventType:event.type,intentId:eventIntentId||null,chargeId:eventChargeId||null})
 return Response.json({received:true,duplicate,brand:'SOS',stripe_api_ready:Boolean(stripeKey)})
})
